var Guid=function(){var d=0;return{guid:function(){return d+=1}}}(),Elm=Elm||{};
Elm.JavaScript=function(){function d(a){for(var b=["Nil"],k=a.length;k--;)b=["Cons",a[k],b];return b}function a(a){for(var b=[];"Cons"===a[0];)b.push(a[1]),a=a[2];return b}function e(a){return a.slice(1)}function h(a){return["Tuple"+a.length].concat(a)}return{castJSBoolToBool:function(a){return a},castBoolToJSBool:function(a){return a},castJSNumberToFloat:function(a){return a},castFloatToJSNumber:function(a){return a},castJSNumberToInt:function(a){return~~a},castIntToJSNumber:function(a){return a},
Experimental:{castJSElementToElement:function(a){return function(b){return function(k){return["Element",Guid.guid(),["EExternalHtml",k],a,b,1,Nothing,Nothing]}}},castElementToJSElement:function(a){return Render.render(a)}},castJSArrayToList:d,castListToJSArray:a,castJSStringToString:d,castStringToJSString:function(e){return"string"===typeof e?e:a(e).join("")},castTupleToJSTuple2:e,castTupleToJSTuple3:e,castTupleToJSTuple4:e,castTupleToJSTuple5:e,castJSTupleToTuple2:h,castJSTupleToTuple3:h,castJSTupleToTuple4:h,
castJSTupleToTuple5:h}}();var Elm=Elm||{},JSjson=JSON;
Elm.JSON=function(){function d(b,a){return function(j){return function(f){var c=h.castStringToJSString(j);return f[1].hasOwnProperty(c)&&(f=f[1][c],f[0]===b)?f[1]:a}}}function a(b){return function(a){function j(b){switch(b[0]){case "JsonNull":return null;case "JsonString":return h.castStringToJSString(b[1]);case "JsonObject":var c={},b=b[1][1],g;for(g in b)c[g]=j(b[g]);return c;case "JsonArray":c=h.castListToJSArray(b[1]);for(g=c.length;g--;)c[g]=j(c[g]);return c;default:return b[1]}}return JSjson.stringify(j(["JsonObject",
a]),null,h.castStringToJSString(b))}}function e(b){function a(b){switch(typeof b){case "string":return["JsonString",h.castJSStringToString(b)];case "number":return["JsonNumber",h.castJSNumberToFloat(b)];case "boolean":return["JsonBool",h.castJSBoolToBool(b)];case "object":if(null===b)return["JsonNull"];for(var c in b)b[c]=a(b[c]);return b instanceof Array?["JsonArray",h.castJSArrayToList(b)]:["JsonObject",["JSON",b]]}}var b=JSjson.parse(b),j;for(j in b)b[j]=a(b[j]);return["JSON",b]}var h=Elm.JavaScript,
i=["JSON",{}];return{empty:i,singleton:function(b){return function(a){var j={};j[h.castStringToJSString(b)]=a;return["JSON",j]}},insert:function(b){return function(a){return function(j){var j=j[1],f={},c;for(c in j)f[c]=j[c];f[h.castStringToJSString(b)]=a;return["JSON",f]}}},lookup:function(b){return function(a){var j=h.castStringToJSString(b);return a[1].hasOwnProperty(j)?Just(a[1][j]):Nothing}},findString:d("JsonString",["Nil"]),findObject:d("JsonObject",i),findArray:d("JsonArray",["Nil"]),findWithDefault:function(b){return function(a){return function(j){var f=
h.castStringToJSString(a);return j[1].hasOwnProperty(f)?j[1][f]:b}}},remove:function(b){return function(a){var a=a[1],j={},f;for(f in a)j[f]=a[f];delete j[h.castStringToJSString(b)];return["JSON",j]}},toPrettyJSString:a,toJSString:a(""),fromJSString:e,toPrettyString:function(b){return function(e){return h.castJSStringToString(a(b)(e))}},toString:function(b){return h.castJSStringToString(a("")(b))},fromString:function(b){return e(h.castStringToJSString(b))},toList:function(b){var b=b[1],a=[],j;for(j in b)a.push(Value.Tuple(h.castJSStringToString(j),
b[j]));return h.castJSArrayToList(a)},fromList:function(b){for(var b=h.castListToJSArray(b),a={},j=b.length;j--;)a[h.castStringToJSString(b[j][1])]=b[j][2];return["JSON",a]},JsonString:function(b){return["JsonString",b]},JsonNumber:function(b){return["JsonNumber",b]},JsonBool:function(b){return["JsonBool",b]},JsonNull:["JsonNull"],JsonArray:function(b){return["JsonArray",b]},JsonObject:function(b){return["JsonObject",b]}}}();
var Value=function(){function d(b){if(0==b.length)return b;for(var b=b.replace(/"/g,"&#34;").replace(/'/g,"&#39;").replace(/</g,"&#60;").replace(/>/g,"&#62;").replace(/\n/g,"<br/>"),b=b.split("<br/>"),a=b.length;a--;){var j=b,f=a,c;c=b[a];if(0!=c.length){c=c.split("");" "==c[0]&&(c[0]="&nbsp;");for(var g=c.length;--g;)" "==c[g][0]&&" "==c[g-1]&&(c[g-1]+=c[g],c[g]="");for(g=c.length;g--;)if(1<c[g].length&&" "==c[g][0]){for(var u=c[g].split(""),e=u.length-2;0<=e;e-=2)u[e]="&nbsp;";c[g]=u.join("")}c=
c.join("");c=" "===c[c.length-1]?c.slice(0,-1)+"&nbsp;":c}j[f]=c}return b.join("<br/>")}var a=function(b,e){if("object"===typeof b){if(b===e)return!0;if(b.length!==e.length)return!1;for(var j=b.length;j--;)if(!a(b[j],e[j]))return!1;return!0}return b===e},e=function(b){if("boolean"===typeof b)return b?"True":"False";if("number"!==typeof b){if("string"===typeof b&&2>b.length)return"'"+b+"'";if(b[0]){if("Tuple"===b[0].substring(0,5)){for(var a="",j=b.length;--j;)a=","+e(b[j])+a;","===a[0]&&(a=a.substring(1));
return"("+a+")"}if("Cons"===b[0])for(var j="string"===typeof b[1]?'"':"]",f="string"===typeof b[1]?"":",",c="string"===typeof b[1]?function(c){return c}:e,a=("string"===typeof b[1]?'"':"[")+c(b[1]),b=b[2];;)if("Cons"===b[0])a+=f+c(b[1]),b=b[2];else return a+j;else{if("Nil"===b[0])return"[]";if("JSON"===b[0])return"(JSON.fromList "+e(Elm.JSON.toList(b))+")";if("RBNode"===b[0]||"RBEmpty"===b[0])return"(Map.fromList "+e(Elm.Dict.fold(function(c){return function(b){return function(a){return["Cons",["Tuple2",
c,b],a]}}})(["Nil"])(b))+")";a="";for(j=b.length;--j;)a=" "+e(b[j])+a;a=b[0]+a;return 1<b.length?"("+a+")":a}}}return b+""},h=function(b){for(var a=["Nil"],e=b.length;e--;)a=["Cons",b[e],a];return a},i;i=document.addEventListener?function(b,a,e){b.addEventListener(a,e,!1)}:function(b,a,e){b.attachEvent("on"+a,e)};return{eq:a,str:h,show:function(b){return h(e(b))},Tuple:function(){var b=arguments.length,a=Array(b+1);for(a[0]="Tuple"+arguments.length;b--;)a[b+1]=arguments[b];return a},append:function(b,
a){if("string"===typeof b&&"string"===typeof a)return b.concat(a);if("Nil"===b[0])return a;for(var e=["Cons",b[1],["Nil"]],f=e,b=b[2];"Cons"===b[0];)f[2]=["Cons",b[1],["Nil"]],b=b[2],f=f[2];f[2]=a;return e},listToArray:function(b){for(var a=[];"Cons"===b[0];)a.push(b[1]),b=b[2];return a},toText:function(b){if("string"===typeof b)return d(b);for(var a=[];"Cons"===b[0];)a.push(b[1]),b=b[2];return d(a.join(""))},properEscape:d,getTextSize:function(b,a,e){var f=document.createElement("div");f.innerHTML=
e;f.style.textAlign="left";0<b&&(f.style.width=b+"px");f.style.visibility="hidden";f.style.styleFloat="left";f.style.cssFloat="left";document.body.appendChild(f);e=window.getComputedStyle(f);b=e.getPropertyValue("width").slice(0,-2)-0;e=e.getPropertyValue("height").slice(0,-2)-0;document.body.removeChild(f);delete f;return[Math.ceil(b),Math.ceil(Math.max(a,e))]},getSize:function(b){b=b.cloneNode(!0);b.style.visibility="hidden";b.style.styleFloat="left";b.style.cssFloat="left";document.body.appendChild(b);
var a=b.offsetWidth,e=b.offsetHeight;document.body.removeChild(b);delete b;return[a,e]},getExcess:function(b){b=b.cloneNode(!0);b.style.visibility="hidden";b.style.styleFloat="left";b.style.cssFloat="left";document.body.appendChild(b);var a=b.offsetWidth,e=b.offsetHeight,f=window.getComputedStyle(b),c=f.getPropertyValue("width").slice(0,-2)-0,f=f.getPropertyValue("height").slice(0,-2)-0;document.body.removeChild(b);delete b;return[a-c,e-f]},groupForms:function(b){for(var b=Elm.JavaScript.castListToJSArray(b),
a=[],e=[],f=b.length;f--;){var c=b[f];switch(c[4][0]){case "FElement":0<e.length&&(a.push(e),e=[]);a.push(c);break;default:e.push(c)}}0<e.length&&a.push(e);return a},wrap:function(a){var e=Value.getSize(a);return["Element",Guid.guid(),["EHtml",a],e[0],e[1],1,Nothing,Nothing]},addListener:i}}(),Elm=Elm||{};
Elm.List=function(){function d(a){return function(b){if("Nil"===b[0])return b;"Cons"!==b[0]&&c("map");for(var g=["Cons",a(b[1]),["Nil"]],f=g,b=b[2];"Cons"===b[0];)f[2]=["Cons",a(b[1]),["Nil"]],b=b[2],f=f[2];return g}}function a(b){return function(a){return function(g){var f=a;if("Nil"===g[0])return f;for("Cons"!==g[0]&&c("foldl");"Cons"===g[0];)f=b(g[1])(f),g=g[2];return f}}}function e(b){return function(a){return function(g){var f=a;if("Nil"===g[0])return f;"Cons"!==g[0]&&c("foldr");for(var e=[];"Cons"===
g[0];)e.push(g[1]),g=g[2];for(g=e.length;g--;)f=b(e[g])(f);return f}}}function h(c){return function(b){var g;"Cons"!==b[0]?g=void 0:(g=b[1],b=b[2],g=a(c)(g)(b));return g}}function i(b){return function(a){return function(g){if("Nil"===g[0])return["Cons",a,["Nil"]];"Cons"!==g[0]&&c("scanl");for(var f=[a];"Cons"===g[0];)a=b(g[1])(a),f.push(a),g=g[2];for(var g=["Nil"],e=f.length;e--;)g=["Cons",f[e],g];return g}}}function b(c){return function(a){a:{for(var g=[function(c){return"Nil"!==c[0]?void 0:["Tuple2",
["Nil"],["Nil"]]},function(a){if("Cons"===a[0]){var g=a[1],a=a[2];var f=b(c)(a);"Tuple2"!==f[0]?g=void 0:(a=f[1],f=f[2],g=c(g)?["Tuple2",["Cons",g,a],f]:["Tuple2",a,["Cons",g,f]]);return g}}],f=g.length;f--;){var e=g[f](a);if(void 0!==e){a=e;break a}}a=void 0}return a}}function k(c){a:{for(var a=[function(c){return"Nil"!==c[0]?void 0:["Tuple2",["Nil"],["Nil"]]},function(c){if("Cons"!==c[0])c=void 0;else if(c=["Tuple2",c[1],k(c[2])],"Tuple2"!==c[0]||"Tuple2"!==c[1][0])c=void 0;else var a=c[1][1],b=
c[1][2],c="Tuple2"!==c[2][0]?void 0:["Tuple2",["Cons",a,c[2][1]],["Cons",b,c[2][2]]];return c}],b=a.length;b--;){var g=a[b](c);if(void 0!==g){c=g;break a}}c=void 0}return c}function j(c){return function(a){a:{for(var b=[function(c){return"Nil"!==c[0]?void 0:["Nil"]},function(c){if("Cons"===c[0]){var a=c[1];return"Nil"!==c[2][0]?void 0:["Cons",a,["Nil"]]}},function(a){if("Cons"===a[0]){var b=a[1];if("Cons"===a[2][0]){var g=a[2][1],a=a[2][2];return["Cons",b,["Cons",c,j(c)(["Cons",g,a])]]}}}],g=b.length;g--;){var f=
b[g](a);if(void 0!==f){a=f;break a}}a=void 0}return a}}function f(c){return function(a){a:{for(var b=[function(c){return"Nil"!==c[0]?void 0:["Nil"]},function(c){if("Cons"===c[0]){var a=c[1];return"Nil"!==c[2][0]?void 0:a}},function(a){if("Cons"===a[0]){var b=a[1];if("Cons"===a[2][0]){var g=a[2][1],a=a[2][2];return Value.append(b,Value.append(c,f(c)(["Cons",g,a])))}}}],g=b.length;g--;){var e=b[g](a);if(void 0!==e){a=e;break a}}a=void 0}return a}}var c=function(c){throw"Function '"+c+"' expecting a list!";
},g=a(function(c){return function(a){return["Cons",c,a]}})(["Nil"]),u=e(function(c){return function(a){return Value.append(c,a)}})(["Nil"]),q=a(function(c){return function(a){return c&&a}})(!0),r=a(function(c){return function(a){return c||a}})(!1),n=a(function(c){return function(a){return c+a}})(0),l=a(function(c){return function(a){return c*a}})(1),v=h(function(c){return function(a){return Math.max(c,a)}}),s=h(function(c){return function(a){return Math.min(c,a)}});return{head:function(c){if("Cons"!==
c[0])throw"Error: 'head' only accepts lists of length greater than one.";return c[1]},tail:function(c){if("Cons"!==c[0])throw"Error: 'tail' only accepts lists of length greater than one.";return c[2]},last:function(c){if("Cons"!==c[0])throw"Error: 'last' only accepts lists of length greater than one.";for(var a=c[1];"Cons"===c[0];)a=c[1],c=c[2];return a},map:d,foldl:a,foldr:e,foldl1:h,foldr1:function(a){return function(b){if("Nil"===b[0])throw"'foldr1' requires an non-empty list.";"Cons"!==b[0]&&
c("foldr1");for(var g=[];"Cons"===b[0];)g.push(b[1]),b=b[2];for(var b=g.pop(),f=g.length;f--;)b=a(g[f])(b);return b}},scanl:i,scanl1:function(c){return function(a){if("Cons"!==a[0])throw"Error: 'scanl1' requires a list of at least length 1.";return i(c)(a[1])(a[2])}},filter:function(a){return function(b){if("Nil"===b[0])return b;"Cons"!==b[0]&&c("filter");for(var g=[];"Cons"===b[0];)a(b[1])&&g.push(b[1]),b=b[2];for(var b=["Nil"],f=g.length;f--;)b=["Cons",g[f],b];return b}},length:function(c){for(var a=
0;"Cons"===c[0];)a+=1,c=c[2];return a},reverse:g,concat:u,concatMap:function(c){return function(a){return u(d(c)(a))}},and:q,or:r,all:function(c){return a(function(a){return function(b){return b&&c(a)}})(!0)},any:function(c){return a(function(a){return function(b){return b||c(a)}})(!1)},sum:n,product:l,maximum:v,minimum:s,partition:b,zipWith:function(a){return function(b){return function(g){if("Nil"===b[0]||"Nil"===g[0])return["Nil"];("Cons"!==b[0]||"Cons"!==g[0])&&c("zipWith");for(var f=[];"Cons"===
b[0]&&"Cons"===g[0];)f.push(a(b[1])(g[1])),b=b[2],g=g[2];for(var g=["Nil"],e=f.length;e--;)g=["Cons",f[e],g];return g}}},zip:function(a){return function(b){if("Nil"===a[0]||"Nil"===b[0])return["Nil"];("Cons"!==a[0]||"Cons"!==b[0])&&c("zip");for(var g=[];"Cons"===a[0]&&"Cons"===b[0];)g.push(["Tuple2",a[1],b[1]]),a=a[2],b=b[2];for(var b=["Nil"],f=g.length;f--;)b=["Cons",g[f],b];return b}},unzip:k,intersperse:j,intercalate:f,sort:function(a){if("Nil"===a[0])return a;"Cons"!==a[0]&&c("sort");for(var b=
[];"Cons"===a[0];)b.push(a[1]),a=a[2];b.sort(function(c,a){return c-a});for(var a=["Nil"],g=b.length;g--;)a=["Cons",b[g],a];return a},take:function(a){return function(b){if(0>=a)return["Nil"];if("Nil"===b[0])return b;"Cons"!==b[0]&&c("take");var g=["Cons",b[1],["Nil"]],f=g,b=b[2];for(--a;"Cons"===b[0]&&0<a;)f[2]=["Cons",b[1],["Nil"]],f=f[2],b=b[2],--a;return g}},drop:function(a){return function(b){if("Nil"===b[0])return b;for("Cons"!==b[0]&&c("drop");"Cons"===b[0]&&0<a;)b=b[2],--a;return b}}}}();
Elm=Elm||{};
Elm.Maybe=function(){function d(a){return function(h){return"Just"===a[0]?["Cons",a[1],h]:h}}function a(a){return function(h){return function(d){var b=a(h);return"Just"===b[0]?["Cons",b[1],d]:d}}}return{Just:function(a){return["Just",a]},Nothing:["Nothing"],catMaybes:Elm.List.foldr(d)(["Nil"]),isJust:function(a){return"Just"===a[0]},isNothing:function(a){return"Nothing"===a[0]},fromMaybe:function(a){return function(d){return"Just"===d[0]?d[1]:a}},consMaybe:d,mapMaybe:function(e){return Elm.List.foldr(a(e))(["Nil"])},maybe:function(a){return function(d){return function(i){return"Just"===
i[0]?d(i[1]):a}}}}}();
(function(){for(var d in Elm)this[d]=Elm[d];if(Elm.Dict)throw"Module name collision, 'Dict' is already defined.";Elm.Dict=function(){function a(a){return function(c){return function(b){return function(g){return function(f){return["RBNode",a,c,b,g,f]}}}}}function e(a){return function(){switch(a[0]){case "RBEmpty":return A(Value.str("(min RBEmpty) is not defined"));case "RBNode":switch(a[4][0]){case "RBEmpty":return["Tuple2",a[2],a[3]]}return e(a[4])}throw"Non-exhaustive pattern match in case";}()}
function d(a){return function(c){var b;a:{switch(c[0]){case "RBEmpty":b=Nothing;break a;case "RBNode":b=function(){switch(compare(a)(c[2])[0]){case "EQ":return Just(c[3]);case "GT":return d(a)(c[5]);case "LT":return d(a)(c[4])}throw"Non-exhaustive pattern match in case";}();break a}throw"Non-exhaustive pattern match in case";}return b}}function i(a){return function(c){return function(b){var g;a:{switch(b[0]){case "RBEmpty":g=a;break a;case "RBNode":g=function(){switch(compare(c)(b[2])[0]){case "EQ":return b[3];
case "GT":return i(a)(c)(b[5]);case "LT":return i(a)(c)(b[4])}throw"Non-exhaustive pattern match in case";}();break a}throw"Non-exhaustive pattern match in case";}return g}}}function b(a){return function(c){return y(d(a)(c))}}function k(c){a:{switch(c[0]){case "RBNode":switch(c[5][0]){case "RBNode":c=a(c[1])(c[5][2])(c[5][3])(a(x)(c[2])(c[3])(c[4])(c[5][4]))(c[5][5]);break a}}c=A(Value.str("rotateLeft of a node without enough children"))}return c}function j(c){a:{switch(c[0]){case "RBNode":switch(c[4][0]){case "RBNode":c=
a(c[1])(c[4][2])(c[4][3])(c[4][4])(a(x)(c[2])(c[3])(c[4][5])(c[5]));break a}}c=A(Value.str("rotateRight of a node without enough children"))}return c}function f(c){a:{switch(c[0]){case "Black":c=x;break a;case "Red":c=C;break a}throw"Non-exhaustive pattern match in case";}return c}function c(c){a:{switch(c[0]){case "RBNode":switch(c[4][0]){case "RBNode":switch(c[5][0]){case "RBNode":c=a(f(c[1]))(c[2])(c[3])(a(f(c[4][1]))(c[4][2])(c[4][3])(c[4][4])(c[4][5]))(a(f(c[5][1]))(c[5][2])(c[5][3])(c[5][4])(c[5][5]));
break a}}}c=A(Value.str("color_flip called on a RBEmpty or RBNode with a RBEmpty child"))}return c}function g(a){a:switch(a[0]){case "RBNode":switch(a[5][0]){case "RBNode":switch(a[5][1][0]){case "Red":a=k(a);break a}}}a:switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][1][0]){case "Red":switch(a[4][4][0]){case "RBNode":switch(a[4][4][1][0]){case "Red":a=j(a);break a}}}}}a:switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][1][0]){case "Red":switch(a[5][0]){case "RBNode":switch(a[5][1][0]){case "Red":a=
c(a);break a}}}}}return a}function u(c){a:switch(c[0]){case "RBNode":switch(c[1][0]){case "Red":c=a(C)(c[2])(c[3])(c[4])(c[5]);break a}}return c}function q(c){return function(b){return function(f){var e=function(f){var u;a:{switch(f[0]){case "RBEmpty":u=a(x)(c)(b)(z)(z);break a;case "RBNode":u=function(){switch(compare(c)(f[2])[0]){case "EQ":return a(f[1])(f[2])(b)(f[4])(f[5]);case "GT":return a(f[1])(f[2])(f[3])(f[4])(e(f[5]));case "LT":return a(f[1])(f[2])(f[3])(e(f[4]))(f[5])}throw"Non-exhaustive pattern match in case";
}();u=g(u);break a}throw"Non-exhaustive pattern match in case";}return u};return u(e(f))}}}function r(c){a:{switch(c[0]){case "RBNode":switch(c[4][0]){case "RBNode":switch(c[4][1][0]){case "Red":c=!0;break a}}}c=!1}return c}function n(c){a:{switch(c[0]){case "RBNode":switch(c[4][0]){case "RBNode":switch(c[4][4][0]){case "RBNode":switch(c[4][4][1][0]){case "Red":c=!0;break a}}}}c=!1}return c}function l(b){if(not(r(b))&&not(n(b))){b=c(b);a:switch(b[0]){case "RBNode":b:switch(b[5][0]){case "RBNode":switch(b[5][4][0]){case "RBNode":switch(b[5][4][1][0]){case "Red":b=
c(k(a(b[1])(b[2])(b[3])(b[4])(j(b[5]))));break b}}}break a}}return b}function v(b){return function(f){var d;a:{switch(f[0]){case "RBEmpty":d=z;break a;case "RBNode":if("LT"===compare(b)(f[2])[0]){d=l(f);b:{switch(d[0]){case "RBEmpty":d=A(Value.str("delLT on RBEmpty"));break b;case "RBNode":d=g(a(d[1])(d[2])(d[3])(del(d[4]))(d[5]));break b}break}}else{f=r(f)?j(f):f;b:{switch(f[0]){case "RBNode":switch(f[5][0]){case "RBEmpty":f=eq(b,f[2]);break b}}f=!1}if(f)d=z;else{var f=not,h;b:{switch(d[0]){case "RBNode":switch(d[5][0]){case "RBNode":switch(d[5][1][0]){case "Red":h=
!0;break b}}}h=!1}if(f=f(h)){f=not;b:{switch(d[0]){case "RBNode":switch(d[5][0]){case "RBNode":switch(d[5][4][0]){case "RBNode":switch(d[5][4][1][0]){case "Red":h=!0;break b}}}}h=!1}f=f(h)}f&&(d=c(d),d=n(d)?c(j(d)):d);b:{switch(d[0]){case "RBNode":f=eq(b,d[2]);break b}f=!1}if(f)b:{switch(d[0]){case "RBEmpty":d=A(Value.str("delEQ called on a RBEmpty"));break b;case "RBNode":h=e(d[5]);c:{switch(h[0]){case "Tuple2":f=h[1];break c}break}c:{switch(h[0]){case "Tuple2":h=h[2];break c}break}var f=a(d[1])(f)(h)(d[4]),
i=function(c){a:{switch(c[0]){case "RBNode":switch(c[4][0]){case "RBEmpty":c=z;break a}}c=l(c);b:{switch(c[0]){case "RBEmpty":c=z;break b;case "RBNode":c=g(a(c[1])(c[2])(c[3])(i(c[4]))(c[5]));break b}throw"Non-exhaustive pattern match in case";}}return c};d=u(i(d[5]));d=g(f(d));break b}break}else b:{switch(d[0]){case "RBEmpty":d=A(Value.str("delGT called on a RBEmpty"));break b;case "RBNode":d=g(a(d[1])(d[2])(d[3])(d[4])(del(d[5])));break b}break}}}break a}throw"Non-exhaustive pattern match in case";
}return u(d)}}function s(c){return function(b){a:{switch(b[0]){case "RBEmpty":b=z;break a;case "RBNode":b=a(b[1])(b[2])(c(b[3]))(s(c)(b[4]))(s(c)(b[5]));break a}throw"Non-exhaustive pattern match in case";}return b}}function m(c){return function(a){return function(b){a:{switch(b[0]){case "RBEmpty":b=a;break a;case "RBNode":b=m(c)(c(b[2])(b[3])(m(c)(a)(b[4])))(b[5]);break a}throw"Non-exhaustive pattern match in case";}return b}}}function p(c){return function(a){return function(b){a:{switch(b[0]){case "RBEmpty":b=
a;break a;case "RBNode":b=p(c)(c(b[2])(b[3])(p(c)(a)(b[5])))(b[4]);break a}throw"Non-exhaustive pattern match in case";}return b}}}var t=[],w;for(w in Elm.Prelude)0<=t.indexOf(w)||(this[w]=Elm.Prelude[w]);var y=Elm.Maybe.isJust,x=["Red"],C=["Black"],z=["RBEmpty"],B=z,A=console.log;return{empty:B,lookup:d,findWithDefault:i,member:b,insert:q,singleton:function(c){return function(a){return q(c)(a)(z)}},remove:v,map:s,foldl:m,foldr:p,union:function(c){return function(a){return m(q)(a)(c)}},intersect:function(c){return function(a){return m(function(c){return function(g){return function(f){return b(c)(a)?
q(c)(g)(f):f}}})(B)(c)}},diff:function(c){return function(a){return m(function(c){return function(){return function(a){return v(c)(a)}}})(c)(a)}},keys:function(c){return m(function(c){return function(){return function(a){return["Cons",c,a]}}})(["Nil"])(c)},values:function(c){return m(function(){return function(c){return function(a){return["Cons",c,a]}}})(["Nil"])(c)},toList:function(c){return m(function(c){return function(a){return function(b){return["Cons",["Tuple2",c,a],b]}}})(["Nil"])(c)},fromList:function(c){return List.foldl(uncurry(q))(B)(c)}}}()})();
(function(){for(var d in Elm)this[d]=Elm[d];Elm.Set=function(){var a=[],e;for(e in Elm.Prelude)0<=a.indexOf(e)||(this[e]=Elm.Prelude[e]);a=Dict.empty;e=Dict.remove;var d=Dict.member,i=Dict.union,b=Dict.intersect,k=Dict.diff,j=Dict.keys,f=List.foldl(function(c){return function(a){return Dict.insert(c)(["Tuple0"])(a)}})(a);return{empty:a,singleton:function(c){return Dict.singleton(c)(["Tuple0"])},insert:function(c){return Dict.insert(c)(["Tuple0"])},remove:e,member:d,union:i,intersect:b,diff:k,toList:j,
fromList:f,foldl:function(c){return Dict.foldl(function(a){return function(){return function(b){return c(a)(b)}}})},foldr:function(c){return Dict.foldr(function(a){return function(){return function(b){return c(a)(b)}}})},map:function(c){return function(a){a=j(a);return f(List.map(c)(a))}}}}()})();Elm=Elm||{};
Elm.Char=function(){function d(a,b){return function(e){e=e.charCodeAt(0);return a<=e&&e<=b}}var a=d(48,57),e=d(97,102),h=d(65,70);return{fromCode:function(a){return String.fromCharCode(a)},toCode:function(a){return a.charCodeAt(0)},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},toLocaleUpper:function(a){return a.toLocaleUpperCase()},toLocaleLower:function(a){return a.toLocaleLowerCase()},isLower:d(97,122),isUpper:d(65,90),isDigit:a,isOctDigit:d(48,55),isHexDigit:function(d){return a(d)||
e(d)||h(d)}}}();var String={toText:Value.toText,properEscape:Value.properEscape},Elm=Elm||{};
Elm.Color=function(){return{rgba:function(d){return function(a){return function(e){return function(h){return["Color",d,a,e,h]}}}},rgb:function(d){return function(a){return function(e){return["Color",d,a,e,1]}}},red:["Color",255,0,0,1],green:["Color",0,255,0,1],blue:["Color",0,0,255,1],yellow:["Color",255,255,0,1],cyan:["Color",0,255,255,1],magenta:["Color",255,0,255,1],black:["Color",0,0,0,1],white:["Color",255,255,255,1],gray:["Color",128,128,128,1],grey:["Color",128,128,128,1],complement:function(d){var a,
e=d[1]/255;a=d[2]/255;var h=d[3]/255,d=Math.max(e,a,h),i=Math.min(e,a,h),i=d-i,b=0;0===i?b=0:d===e?b=(a-h)/i%6:d===a?b=(h-e)/i+2:d===h&&(b=(e-a)/i+4);a=60*b;var e=d*(0===d?0:i/d),b=(a+180)%360/60,k=e*(1-Math.abs(b%2-1)),i=h=a=0;0<=b&&1>b?(a=e,h=k,i=0):1<=b&&2>b?(a=k,h=e,i=0):2<=b&&3>b?(a=0,h=e,i=k):3<=b&&4>b?(a=0,h=k,i=e):4<=b&&5>b?(a=k,h=0,i=e):5<=b&&6>b&&(a=e,h=0,i=k);d-=e;return["Color",Math.round(255*(a+d)),Math.round(255*(h+d)),Math.round(255*(i+d)),1]},extract:function(d){return 1===d[4]?"rgb("+
d[1]+","+d[2]+","+d[3]+")":"rgba("+d[1]+","+d[2]+","+d[3]+","+d[4]+")"}}}();
var Collage=function(){function d(a,c){var b=c.length-1;if(!(0>=b))for(a.moveTo(c[b][1],c[b][2]);b--;)a.lineTo(c[b][1],c[b][2])}function a(a,c,b,e){0===a.length&&(a=[8,4]);var d=e.length-1;if(!(0>=d)){var j=e[d][1],h=e[d][2],l=0,k=0,i=0,m=0,p=0,t=0,w=a.length,y=!0,x=a[0];for(c.moveTo(j,h);d--;){l=e[d][1];k=e[d][2];i=l-j;m=k-h;for(p=Math.sqrt(i*i+m*m);x<=p;)j+=i*x/p,h+=m*x/p,c[y?"lineTo":"moveTo"](j,h),i=l-j,m=k-h,p=Math.sqrt(i*i+m*m),y=!y,t=(t+1)%w,x=a[t];0<p&&(c[y?"lineTo":"moveTo"](l,k),x-=p);j=
l;h=k}}c.strokeStyle=Elm.Color.extract(b);c.stroke()}function e(b,c,g,e,h){c.clearRect(0,0,g,e);for(g=h.length;g--;){var k=h[g],n=b,e=c,l=k[1],i=k[2],s=k[3][1],m=k[3][2],k=k[4];e.save();(0!==s||0!==m)&&e.translate(s,m);l!==~~l&&e.rotate(2*Math.PI*l);1!==i&&e.scale(i,i);e.beginPath();switch(k[0]){case "FLine":a:switch(n=e,l=k,k=l[3][1],l[1][0]){case "Solid":l=l[2];d(n,k);n.strokeStyle=Elm.Color.extract(l);n.stroke();break;case "Dotted":a([3,3],n,l[2],k);break a;case "Dashed":a([8,4],n,l[2],k);break a;
case "Custom":a(l[1][1],n,l[2],k)}break;case "FShape":a:switch(s=n,i=e,n=k[1],l=k[2],k=k[3][1],n[0]){case "Filled":n=i;d(n,k);n.fillStyle=Elm.Color.extract(l);n.fill();break a;case "Outlined":n=i;d(n,k);n.strokeStyle=Elm.Color.extract(l);n.stroke();break a;case "Textured":l=s;n=n[1];s=new Image;s.src=j.castStringToJSString(n);s.onload=l;d(i,k);i.fillStyle=i.createPattern(s,"repeat");i.fill();break a;case "CustomOutline":a(n[1],i,l,k)}break;case "FImage":l=e,i=k[1],s=k[2],k=k[3],m=new Image,m.onload=
n,m.src=j.castStringToJSString(k),l.drawImage(m,-i/2,-s/2,i,s)}e.restore()}}function h(a,c,b){var d=Render.newElement("canvas");d.style.width=~~a+"px";d.style.height=~~c+"px";d.style.display="block";d.width=~~a;d.height=~~c;if(d.getContext){var h=d.getContext("2d"),a=d.width,c=d.height;e(function(){e(this,h,a,c,b)},h,a,c,b);return d}d.innerHTML="Your browser does not support the canvas element.";return d}function i(a,c,b,e,d,h,j){var k=Render.render(j),b="translate("+(d-j[3]/2)+"px,"+(h-j[4]/2)+"px) "+
(1===e?"":"scale("+e+","+e+")")+" "+(b===~~b?"":"rotate("+360*b+"deg)");k.style.transform=b;k.style.msTransform=b;k.style.MozTransform=b;k.style.webkitTransform=b;k.style.OTransform=b;b=Render.newElement("div");Render.addTo(b,k);b.style.width=~~a+"px";b.style.height=~~c+"px";b.style.overflow="hidden";return b}function b(a,c,b){if(!Value.eq(b,c)){var d=a.style.width.slice(0,-2)-0,j=a.style.height.slice(0,-2)-0;if("object"===typeof b[0]){if("object"===typeof c[0]&&a.getContext){var k=a.getContext("2d");
return e(function(){e(this,k,d,j,b)},k,d,j,b)}c=h(d,j,b);c.style.position="absolute";return a.parentNode.replaceChild(c,a)}c=i(d,j,b[1],b[2],b[3][1],b[3][2],b[4][1]);c.style.position="absolute";return a.parentNode.replaceChild(c,a)}}function k(a,c,b,e,d){var j=0,h,k=(a[1]-e[1])/b,a=(a[2]-e[2])/b;0!==c&&(c*=-2*Math.PI,b=k*Math.cos(c)-a*Math.sin(c),a=k*Math.sin(c)+a*Math.cos(c),k=b);if(0===d.length)return!1;h=d[0];for(b=d.length-1;b--;){c=d[b];e=h[1];h=h[2];var i=c[1],s=c[2];if(h<s)var m=h,p=s;else m=
s,p=h;if(e<i)var t=e,w=i;else t=i,w=e;m<a&&a<=p&&k<=w&&(k<=t||k<=(a-h)*(i-e)/(s-h)+e)&&++j;h=c}return 1===j%2}var j=Elm.JavaScript;return{collage:function(a,c,b){if(0===b.length)return h(a,c,[]);for(var e=Array(b.length),d=b.length;d--;){var j=b[d];e[d]="string"===typeof j[0]?i(a,c,j[1],j[2],j[3][1],j[3][2],j[4][1]):h(a,c,j)}return 1===b.length?e[0]:Render.flowWith(Render.goIn,function(c){return c},e)},updateCollage:function(a,c,g){if(1===g.length)return b(a,c[0],g[0]);for(var a=a.childNodes,e=a.length,
d=e;d--;)b(a[e-d-1],c[d],g[d])},insideForm:function(a){return function(c){var b=a[1],e=a[2];if(6>c.length){var d=c[3][1],j=c[3][2],h=0,i=c[2];switch(c[4][0]){case "FShape":for(var v=c[4][3][1],s=v.length;--s;)var m=v[s],h=Math.max(h,m[1]*m[1]+m[2]*m[2]);h*=i*i;break;case "FImage":v=i*c[4][1]/2;i=i*c[4][2]/2;h=v*v+i*i;break;case "FElement":v=i*c[4][1][3]/2,i=i*c[4][1][4]/2,h=v*v+i*i}c.push(function(c,a){var b=c-d,g=a-j;return b*b+g*g<h+1})}if(!c[5](b,e))return!1;var p,t;switch(c[4][0]){case "FShape":return k(a,
c[1],c[2],c[3],c[4][3][1]);case "FLine":return!1;case "FImage":p=c[4][1]/2;t=c[4][2]/2;break;case "FElement":p=c[4][1][3]/2,t=c[4][1][4]/2}return k(a,c[1],c[2],c[3],[[null,p,t],[null,-p,t],[null,-p,-t],[null,p,-t],[null,p,t]])}}}}(),Elm=Elm||{};
Elm.Graphics=function(){function d(c){return function(a){return["Position",c,a]}}function a(c){return function(a){return["EText",c,a]}}function e(c){return function(a){return["EFlow",c,l.castListToJSArray(a)]}}function h(c){return["Line",l.castListToJSArray(c)]}function i(c){return function(a){var b=l.castListToJSArray(c);0<b.length&&b.push(b[0]);return["Shape",b,a]}}function b(c){return function(a){return function(b){return function(g){return["Form",c,a,b,g]}}}}function k(c){return function(a){return function(b){return["FLine",
c,a,b]}}}function j(c){return function(a){return function(b){return["FShape",c,a,b]}}}function f(c,a,b,g,f,e){return["Element",Guid.guid(),c,a,b,g,f,e]}function c(c,a,b){return["Element",Guid.guid(),c,a,b,1,Nothing,Nothing]}function g(c){return~~c[3]}function u(c){return~~c[4]}function q(a){return function(b){return function(g){return c(["EImage",l.castStringToJSString(g)],a,b)}}}function r(a){return function(b){return c(y,a,b)}}function n(c){return function(a){return function(b){var g=map(function(b){return["Tuple2",
c/2*cos(2*(pi/50)*b),a/2*sin(2*(pi/50)*b)]}),f=49,e=["Nil"];if(0<=f){do e=["Cons",f,e];while(0<f--)}return i(g(e))(b)}}}var l=Elm.JavaScript,v=["DRight"],s=["DDown"],m=["DOut"],p=["Near"],t=["Mid"],w=["Far"],y=["EEmpty"],x=["Solid"],C=["Dotted"],z=["Dashed"],B=["Filled"],A=["Outlined"],D=d(p)(p),E=d(w)(p),F=d(p)(w),G=d(w)(w),H=d(p)(t),I=d(w)(t),p=d(t)(p),w=d(t)(w),t=d(t)(t);return{left:["DLeft"],right:v,down:s,up:["DUp"],inward:["DIn"],outward:m,topLeft:D,topRight:E,bottomLeft:F,bottomRight:G,midLeft:H,
midRight:I,midTop:p,midBottom:w,middle:t,middleAt:function(c){return function(a){return["PositionAt",c,a]}},topLeftAt:function(c){return function(a){return["PositionTL",c,a]}},topRightAt:function(c){return function(a){return["PositionTR",c,a]}},bottomLeftAt:function(c){return function(a){return["PositionBL",c,a]}},bottomRightAt:function(c){return function(a){return["PositionBR",c,a]}},absolute:function(c){return["Absolute",c]},relative:function(c){return["Relative",c]},width:function(c){return function(a){var b=
a[2];switch(b[0]){case "EImage":case "EVideo":return f(a[2],c,a[4]*c/a[3],a[5],a[6],a[7]);case "EText":return b=Value.getTextSize(c,a[4],b[2]),f(a[2],c,b[1],a[5],a[6],a[7])}return f(a[2],c,a[4],a[5],a[6],a[7])}},height:function(c){return function(a){switch(a[2][0]){case "EImage":case "EVideo":return f(a[2],a[3]*c/a[4],c,a[5],a[6],a[7])}return f(a[2],a[3],c,a[5],a[6],a[7])}},size:function(a){return function(c){return function(b){return f(b[2],a,c,b[5],b[6],b[7])}}},opacity:function(a){return function(c){return f(c[2],
c[3],c[4],a,c[6],c[7])}},color:function(a){return function(c){return f(c[2],c[3],c[4],c[5],Just(a),c[7])}},link:function(c){return function(a){return f(a[2],a[3],a[4],a[5],a[6],Just(l.castStringToJSString(c)))}},widthOf:g,heightOf:u,sizeOf:function(a){return["Tuple2",~~a[3],~~a[4]]},text:function(b){var g=Value.getTextSize(0,0,b);return c(a("left")(b),g[0],g[1])},asText:function(b){var b=monospace(Value.toText(Value.show(b))),g=Value.getTextSize(0,0,b);return c(a("left")(b),g[0],g[1])},plainText:function(b){var b=
Value.toText(b),g=Value.getTextSize(0,0,b);return c(a("left")(b),g[0],g[1])},centeredText:function(b){var g=Value.getTextSize(0,0,b);return c(a("center")(b),g[0],g[1])},justifiedText:function(b){var g=Value.getTextSize(0,0,b);return c(a("justify")(b),g[0],g[1])},rightedText:function(b){var g=Value.getTextSize(0,0,b);return c(a("right")(b),g[0],g[1])},image:q,images:function(a){var c=Elm.Signal.constant(r(0)(0)),a=Elm.Signal.lift(function(a){var a=l.castStringToJSString(a),b=new Image;b.onload=function(){Dispatcher.notify(c.id,
q(this.width)(this.height)(a))};b.src=a})(a);return Elm.Signal.lift2(function(a){return function(){return a}})(c)(a)},video:function(a){return function(b){return function(g){return c(["EVideo",l.castStringToJSString(g)],a,b)}}},fittedImage:function(a){return function(b){return function(g){return c(["EFittedImage",l.castStringToJSString(g)],a,b)}}},flow:function(a){return function(b){var f;f=map(g)(b);a:{switch(a[0]){case "DLeft":f=sum(f);break a;case "DRight":f=sum(f);break a}f=maximum(f)}var d;d=
map(u)(b);a:{switch(a[0]){case "DDown":d=sum(d);break a;case "DUp":d=sum(d);break a}d=maximum(d)}return c(e(a)(b),f,d)}},above:function(a){return function(b){return c(e(s)(["Cons",a,["Cons",b,["Nil"]]]),max(~~a[3])(~~b[3]),~~a[4]+~~b[4])}},below:function(a){return function(b){return c(e(s)(["Cons",b,["Cons",a,["Nil"]]]),max(~~a[3])(~~b[3]),~~a[4]+~~b[4])}},beside:function(a){return function(b){return c(e(v)(["Cons",a,["Cons",b,["Nil"]]]),~~a[3]+~~b[3],max(~~a[4])(~~b[4]))}},layers:function(a){return c(e(m)(a),
maximum(map(g)(a)),maximum(map(u)(a)))},collage:function(a){return function(b){return function(g){return c(["ECollage",a,b,Value.groupForms(g)],a,b)}}},spacer:r,container:function(a){return function(b){return function(g){return function(f){return c(["EContainer",g,f],a,b)}}}},line:h,segment:function(a){return function(c){return h(["Cons",a,["Cons",c,["Nil"]]])}},polygon:i,rect:function(a){return function(c){return function(b){return i(["Cons",["Tuple2",0-a/2,0-c/2],["Cons",["Tuple2",0-a/2,c/2],["Cons",
["Tuple2",a/2,c/2],["Cons",["Tuple2",a/2,0-c/2],["Nil"]]]]])(b)}}},oval:n,circle:function(a){return n(2*a)(2*a)},ngon:function(a){return function(c){return function(b){var g=toFloat(a),f=map(function(a){return["Tuple2",c*cos(2*(pi/g)*a),c*sin(2*(pi/g)*a)]}),e=a-1,d=["Nil"];if(0<=e){do d=["Cons",e,d];while(0<e--)}return i(f(d))(b)}}},solid:function(a){return function(c){return b(0)(1)(["Tuple2",0,0])(k(x)(a)(c))}},dotted:function(a){return function(c){return b(0)(1)(["Tuple2",0,0])(k(C)(a)(c))}},dashed:function(a){return function(c){return b(0)(1)(["Tuple2",
0,0])(k(z)(a)(c))}},customLine:function(a){return function(c){return function(g){return b(0)(1)(["Tuple2",0,0])(k(["Custom",l.castListToJSArray(a)])(c)(g))}}},filled:function(a){return function(c){return b(0)(1)(c[2])(j(B)(a)(c))}},outlined:function(a){return function(c){return b(0)(1)(c[2])(j(A)(a)(c))}},customOutline:function(a){return function(c){return function(g){return b(0)(1)(g[2])(j(["CustomOutline",l.castListToJSArray(a)])(c)(g))}}},textured:function(a){return function(c){return b(0)(1)(c[2])(j(["Textured",
a])(null)(c))}},sprite:function(a){return function(c){return function(g){return function(f){return b(0)(1)(f)(["FImage",c,g,l.castStringToJSString(a)])}}}},toForm:function(a){return function(c){return b(0)(1)(a)(["FElement",c])}},rotate:function(a){return function(c){a:{switch(c[0]){case "Form":var g=c[2],f=c[3],e=c[4],c=b(a+c[1])(g)(f)(e);break a}throw"Non-exhaustive pattern match in case";}return c}},scale:function(a){return function(c){return b(c[1])(a*c[2])(c[3])(c[4])}},move:function(a){return function(c){return function(g){var f;
a:{switch(g[0]){case "Form":f=g[1];var e=g[2],d=g[3],g=g[4];switch(d[0]){case "Tuple2":var h=d[1],d=d[2];f=b(f)(e)(["Tuple2",a+h,c+d])(g);break a}}throw"Non-exhaustive pattern match in case";}return f}}},isWithin:Collage.insideForm}}();Elm=Elm||{};
Elm.Text=function(){function d(a){return Value.toText(a)}var a=function(a){return function(b){return"<"+a+' style="padding:0;margin:0">'+b+"</"+a+">"}},e=function(a,b){return function(f){return"<span style='"+a+":"+b+"'>"+f+"</span>"}},h=function(a){a=Elm.JavaScript.castStringToJSString(a);return e("font-family",a)},i=a("h1"),b=e("font-style","italic"),a=a("b"),k=e("text-decoration","underline"),j=e("text-decoration","overline"),f=e("text-decoration","line-through");return{fromString:d,toText:d,header:i,
height:function(a){return e("font-size",a+"em")},italic:b,bold:a,underline:k,overline:j,strikeThrough:f,monospace:h("monospace"),typeface:h,color:function(a){return e("color",Elm.Color.extract(a))},link:function(a){return function(b){return"<a href='"+d(a)+"'>"+b+"</a>"}}}}();
var Render=function(){function d(a){a=document.createElement(a);a.style.padding="0";a.style.margin="0";return a}function a(a){return a}function e(a){a.style.styleFloat="left";a.style.cssFloat="left";return a}function h(a){a.style.position="absolute";return a}function i(a,b,f){for(var e=d("div"),h=f.length;h--;){var j=a(b(f[h]));e.appendChild(j)}return e}function b(a){switch(a[0]){case "Absolute":return a[1]+"px";case "Relative":return 100*a[1]+"%"}}function k(a,g){g.style.position="absolute";g.style.margin=
"auto";switch(a[0]){case "Position":"Far"!==a[1][0]&&(g.style.left=0);"Near"!==a[1][0]&&(g.style.right=0);"Far"!==a[2][0]&&(g.style.top=0);"Near"!==a[2][0]&&(g.style.bottom=0);break;case "PositionAt":g.style.top=b(a[2]);g.style.left=b(a[1]);var f="translate("+-elem[3]/2+"px,"+-elem[4]/2+"px)";g.style.transform=f;g.style.msTransform=f;g.style.MozTransform=f;g.style.webkitTransform=f;g.style.OTransform=f;break;default:f=a[0].slice(-2),g.style["T"===f[0]?"top":"bottom"]=b(a[2]),g.style["L"===f[1]?"left":
"right"]=b(a[1])}}function j(c){var b={};switch(c[2][0]){case "EText":var b=c[2][1],f=c[2][2],q=d("div");q.innerHTML=f;q.style.textAlign=b;b=q;break;case "EImage":b=c[2][1];f=d("img");f.src=b;f.name=b;f.style.display="block";b=f;break;case "EVideo":q=c[2][1];b=d("video");b.controls="controls";f=d("source");f.src=q;q=q.split(".");f.type="video/"+q[q.length-1];b.appendChild(f);b.style.display="block";break;case "EFittedImage":var r=c[3],n=c[4],b=c[2][1],l=d("canvas");l.style.display="block";l.style.width=
r+"px";l.style.height=n+"px";l.width=r;l.height=n;l.innerHTML="Your browser does not support the canvas element.";var v=d("img");v.onload=function(){if(l.getContext){var a=l.getContext("2d"),b=0,c=0,f=this.width,e=this.height;r/n>this.width/this.height?(e=this.width*n/r,c=(this.height-e)/2):(f=this.height*r/n,b=(this.width-f)/2);a.drawImage(v,b,c,f,e,0,0,l.width,l.height)}};v.src=b;b=l;break;case "EFlow":a:{b=c[2][2];switch(c[2][1][0]){case "DDown":b=b.slice(0).reverse();case "DUp":b=i(a,j,b);break a;
case "DRight":b=b.slice(0).reverse();case "DLeft":b=i(e,j,b);break a;case "DOut":b=b.slice(0).reverse();case "DIn":b=i(h,j,b);break a}b=void 0}break;case "ECollage":b=Collage.collage(c[2][1],c[2][2],c[2][3]);break;case "EEmpty":b=d("div");break;case "EContainer":f=c[2][1];b=j(c[2][2]);k(f,b);f=d("div");f.style.position="relative";f.style.overflow="hidden";f.appendChild(b);b=f;break;case "EHtml":b=c[2][1];"button"!==b.type&&(f=Value.getExcess(b),c[3]-=f[0],c[4]-=f[1]);break;case "EExternalHtml":b=
d("div"),b.appendChild(c[2][1])}b.id=c[1];b.style.width=~~c[3]+"px";b.style.height=~~c[4]+"px";1!==c[5]&&(b.style.opacity=c[5]);"Just"===c[6][0]&&(b.style.backgroundColor=Elm.Color.extract(c[6][1]));return"Just"===c[7][0]?(f=d("a"),f.href=c[7][1],f.appendChild(b),f):b}function f(b,g,d){"A"===b.tagName&&(b=b.firstChild);if(g[1]!==d[1]){if(g[2][0]!==d[2][0])return b.parentNode.replaceChild(j(d),b);var i=d[2],r=g[2];switch(i[0]){case "EText":i[1]!==r[1]&&(b.style.textAlign=i[1]);i[2]!==r[2]&&(b.innerHTML=
i[2]);break;case "EImage":i[1]!==r[1]&&(b.src=i[1]);break;case "EVideo":case "EFittedImage":if(!Value.eq(i,r)||d[3]!==g[3]||d[4]!==g[4])return b.parentNode.replaceChild(j(d),b);break;case "ECollage":if(i[1]!==r[1]||i[2]!==r[2]||i[3].length!==r[3].length)return b.parentNode.replaceChild(j(d),b);Collage.updateCollage(b,r[3],i[3]);break;case "EFlow":if(i[1]!==r[1])return b.parentNode.replaceChild(j(d),b);var n=i[2],l=b.childNodes;if(n.length!==l.length)return b.parentNode.replaceChild(j(d),b);var r=
r[2],v={};switch(i[1][0]){case "DDown":case "DUp":v=a;break;case "DRight":case "DLeft":v=e;break;case "DOut":case "DIn":v=h}for(i=l.length;i--;)f(l[i],r[i],n[i]),v(l[i]);break;case "EContainer":f(b.childNodes[0],r[2],i[2]);k(i[1],b.childNodes[0]);break;case "EHtml":d[1]!==g[1]&&(n=j(d),b.parentNode.replaceChild(n,b),b=n);"button"!==n.type&&(i=Value.getExcess(b),d[3]-=i[0],d[4]-=i[1]);break;case "EExternalHtml":d[1]!==g[1]&&b.parentNode.replaceChild(j(d),b)}d[3]!==g[3]&&(b.style.width=~~d[3]+"px");
d[4]!==g[4]&&(b.style.height=~~d[4]+"px");d[5]!==g[5]&&(b.style.opacity=d[5]);2===d[6].length&&(i=Elm.Color.extract(d[6][1]),i!==b.style.backgroundColor&&(b.style.backgroundColor=i));if(2===d[7].length&&(1===g[7].length||d[7][1]!==g[7][1]))b.parentNode.href=d[7][1];d[1]=g[1]}}return{render:j,update:f,addTo:function(a,b){a.appendChild(b)},newElement:d,flowWith:i,goIn:h}}(),Elm=Elm||{};
Elm.Signal=function(){var d=function(a,b,d){for(var e=a.kids,h=e.length;h--;)e[h].recv(b,d,a.id)},a=function(a){this.id=Guid.guid();this.value=a;this.kids=[];this.defaultNumberOfKids=0;this.recv=function(a,b,f){if(b=b===this.id)this.value=f;d(this,a,b);return b};Dispatcher.inputs.push(this)},e=function(a,b){this.id=Guid.guid();this.value=null;this.kids=[];this.count=0;this.changed=!1;b.reverse();this.recalc=function(){for(var d=a,e=b.length;e--;)d=d(b[e].value);this.value=d};this.recalc();this.recv=
function(a,f){this.count+=1;f&&(this.changed=!0);this.count==b.length&&(this.changed&&this.recalc(),d(this,a,this.changed),this.changed=!1,this.count=0)};for(var e=b.length;e--;)b[e].kids.push(this)},h=function(a,b,e,h){this.id=Guid.guid();this.value=e?b(h.value):b;this.kids=[];this.recv=function(b,c){c&&(this.value=a(h.value)(this.value));d(this,b,c)};h.kids.push(this)},i=function(a,b,e){this.id=Guid.guid();this.value=a(e.value)?b:e.value;this.kids=[];this.recv=function(b,c){var h=c&&!a(e.value);
h&&(this.value=e.value);d(this,b,h)};e.kids.push(this)},b=function(a){this.id=Guid.guid();this.value=a.value;this.kids=[];this.recv=function(b,e){var h=e&&!eq(this.value,a.value);h&&(this.value=a.value);d(this,b,h)};a.kids.push(this)},k=function(a){return function(b){return function(d){d=new e(function(a){return function(b){return[a,b]}},[a,d]);d=new i(function(a){return a[0]},[!0,b],d);return new e(function(a){return a[1]},[d])}}},j=function(a,b){this.id=Guid.guid();this.value=b.value;this.kids=
[];this.count=0;this.changed=!1;this.recv=function(e,h,j){j===a.id&&(this.changed=h);this.count+=1;2==this.count&&(this.changed&&(this.value=b.value),d(this,e,this.changed),this.count=0,this.changed=!1)};a.kids.push(this);b.kids.push(this)};return{constant:function(b){return new a(b)},lift:function(a){return function(b){return new e(a,[b])}},lift2:function(a){return function(b){return function(d){return new e(a,[b,d])}}},lift3:function(a){return function(b){return function(d){return function(h){return new e(a,
[b,d,h])}}}},lift4:function(a){return function(b){return function(d){return function(h){return function(j){return new e(a,[b,d,h,j])}}}}},foldp:function(a){return function(b){return function(d){return new h(a,b,!1,d)}}},foldp_:function(a){return function(b){return function(d){return new h(a,b,!0,d)}}},foldp1:function(a){return function(b){return new h(a,function(a){return a},!0,b)}},count:function(a){return new h(function(){return function(a){return a+1}},0,!1,a)},keepIf:function(a){return function(b){return function(d){return new i(function(b){return!a(b)},
b,d)}}},dropIf:function(a){return function(b){return function(d){return new i(a,b,d)}}},keepWhen:function(a){return k(new e(function(a){return!a},[a]))},dropWhen:k,dropRepeats:function(a){return new b(a)},sampleOn:function(a){return function(b){return new j(a,b)}}}}();
var Dispatcher=function(){function d(a){if(!a.hasOwnProperty("defaultNumberOfKids"))return!0;var e=a.kids.length;if(0==e)return!1;if(e>a.defaultNumberOfKids)return!0;for(var h=!1;e--;)h=h||d(a.kids[e]);return h}var a=null,e=0,h=[],i=null;return{initialize:function(){a=Elm.main();a.hasOwnProperty("recv")||(a=Elm.Signal.constant(a));i=a.value;for(var b=[],e=h.length;e--;)d(h[e])&&b.push(h[e]);h=b;document.getElementById("content").appendChild(Render.render(i));b=document.getElementById("widthChecker").offsetWidth;
b!==window.innerWidth&&Dispatcher.notify(Window.dimensions.id,Value.Tuple(b,window.innerHeight));a=Elm.Signal.lift(function(a){var b=document.getElementById("content");Render.update(b.firstChild,i,a);return i=a})(a)},notify:function(a,d){e+=1;for(var j=!1,f=h.length;f--;)j=h[f].recv(e,a,d)||j;return j},inputs:h}}();
Elm.HTTP=function(){function d(a){return function(b){return function(d){return function(c){return{"0":"Request",length:1,verb:i.castStringToJSString(a),url:i.castStringToJSString(b),data:null===d?null:i.castStringToJSString(d),headers:c}}}}}function a(a){return d("GET")(a)(null)(["Nil"])}function e(a){return function(d){Dispatcher.notify(a.id,["Waiting"]);var e=null;window.XMLHttpRequest?e=new XMLHttpRequest:window.ActiveXObject&&(e=new ActiveXObject("Microsoft.XMLHTTP"));e.onreadystatechange=function(){4===
e.readyState&&Dispatcher.notify(a.id,200===e.status?["Success",b(e.responseText)]:["Failure",e.status,b(e.statusText)])};e.open(d.verb,d.url,!0);Elm.List.map(function(a){e.setRequestHeader(i.castStringToJSString(a[1]),i.castStringToJSString(a[2]))})(d.headers);e.send(d.data);return null}}function h(a){var b=Elm.Signal.constant(["Waiting"]),a=Elm.Signal.lift(e(b))(a);return Elm.Signal.lift2(function(a){return function(){return a}})(b)(a)}var i=Elm.JavaScript,b=Elm.JavaScript.castJSStringToString;return{get:a,
post:function(a){return function(b){return d("POST")(a)(b)(["Nil"])}},request:d,send:h,sendGet:function(b){return h(Elm.Signal.lift(a)(b))}}}();
Elm.Input=function(){var d=Elm.JavaScript,a=Elm.JavaScript.castJSStringToString,e=function(b,e){b.placeholder=d.castStringToJSString(e);var h=Elm.Signal.constant(["Nil"]);Value.addListener(b,"keyup",function(){Dispatcher.notify(h.id,a(b.value));b.focus()});b.style.padding="1px";return Value.Tuple(Value.wrap(b),h)},h=function(a){a=document.createElement(a);a.style.padding="0";a.style.margin="0";return a},i=function(a){for(var d=h("select"),e=[];"Cons"===a[0];){var f=h("option"),c=Value.toText(a[1][1]);
f.value=c;f.innerHTML=c;d.appendChild(f);e.push(a[1][2]);a=a[2]}var g=Elm.Signal.constant(e[0]);Value.addListener(d,"change",function(){Dispatcher.notify(g.id,e[d.selectedIndex])});return Value.Tuple(Value.wrap(d),g)};return{textArea:function(a){return function(d){var j=h("textarea");j.rows=d;j.cols=a;return e(j,"")}},textField:function(a){var d=h("input");d.type="text";return e(d,a)},password:function(a){var d=h("input");d.type="password";return e(d,a)},checkbox:function(a){var d=h("input");d.type=
"checkbox";d.checked=a;var e=Elm.Signal.constant(a);Value.addListener(d,"change",function(){Dispatcher.notify(e.id,d.checked)});return Value.Tuple(Value.wrap(d),e)},dropDown:i,stringDropDown:function(a){return i(Elm.List.map(function(a){return Value.Tuple(a,a)})(a))},button:function(a){var e=h("input");e.type="button";e.value=d.castStringToJSString(a);var i=Elm.Signal.constant(!1);Value.addListener(e,"click",function(){Dispatcher.notify(i.id,!0);Dispatcher.notify(i.id,!1)});return Value.Tuple(Value.wrap(e),
i)}}}();
Elm.Keyboard={Raw:function(){function d(a,e){return"Nil"===e[0]?e:e[1]===a?e[2]:["Cons",e[1],d(a,e[2])]}var a=Elm.Signal.constant(["Nil"]),e=Elm.Signal.constant(["Nothing"]);Value.addListener(document,"keydown",function(d){var e;a:{for(e=a.value;"Nil"!==e[0];){if(e[1]===d.keyCode){e=!0;break a}e=e[2]}e=!1}e||Dispatcher.notify(a.id,["Cons",d.keyCode,a.value])||this.removeEventListener("keydown",arguments.callee,!1)});Value.addListener(document,"keyup",function(e){var i=d(e.keyCode,a.value);Dispatcher.notify(a.id,
i)||this.removeEventListener("keyup",arguments.callee,!1)});Value.addListener(window,"blur",function(e){Dispatcher.notify(a.id,["Nil"])||this.removeEventListener("blur",arguments.callee,!1)});Value.addListener(document,"keypress",function(a){var d=Dispatcher.notify(e.id,["Just",a.charCode||a.keyCode]);Dispatcher.notify(e.id,["Nothing"]);d||this.removeEventListener("keypress",arguments.callee,!1)});return{keysDown:a,charPressed:e}}()};
Elm.Mouse=function(){function d(a){var b=0,c=0;a||(a=window.event);if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return Value.Tuple(b,c)}var a=Elm.Signal.constant(Value.Tuple(0,0));a.defaultNumberOfKids=2;var e=Elm.Signal.lift(function(a){return a[1]})(a);e.defaultNumberOfKids=0;var h=Elm.Signal.lift(function(a){return a[2]})(a);h.defaultNumberOfKids=
0;var i=Elm.Signal.constant(!1),b=Elm.Signal.constant(!1),k=Elm.Signal.constant(Value.Tuple());Value.addListener(document,"click",function(a){var e=Dispatcher.notify(b.id,!0),c=Dispatcher.notify(k.id,Value.Tuple());Dispatcher.notify(b.id,!1);!e&&!c&&this.removeEventListener("click",arguments.callee,!1)});Value.addListener(document,"mousedown",function(a){Dispatcher.notify(i.id,!0)||this.removeEventListener("mousedown",arguments.callee,!1)});Value.addListener(document,"mouseup",function(a){Dispatcher.notify(i.id,
!1)||this.removeEventListener("mouseup",arguments.callee,!1)});Value.addListener(document,"mousemove",function(b){Dispatcher.notify(a.id,d(b))||this.removeEventListener("mousemove",arguments.callee,!1)});return{position:a,x:e,y:h,isClicked:b,isDown:i,clicks:k,isClickedOn:function(a){var a=Render.render(a),b=Elm.Signal.constant(!1);Value.addListener(a,"click",function(){Dispatcher.notify(b.id,!0);Dispatcher.notify(b.id,!1)});return Value.Tuple(Value.wrap(a),b)}}}();
Elm.Random=function(){return{inRange:function(d){return function(a){return Elm.Signal.constant(Math.floor(Math.random()*(a-d+1))+d)}},randomize:function(d){return function(a){return function(e){return Elm.Signal.lift(function(){return Math.floor(Math.random()*(a-d+1))+d})(e)}}}}}();
Elm.Time=function(){return{every:function(d){var d=1E3*d,a=Elm.Signal.constant(0),e=0;setInterval(function(){e+=d;Dispatcher.notify(a.id,e/1E3)},d);return a},after:function(d){var d=1E3*d,a=Elm.Signal.constant(!1);setTimeout(function(){Dispatcher.notify(a.id,!0)},d);return a},before:function(d){var d=1E3*d,a=Elm.Signal.constant(!0);setTimeout(function(){Dispatcher.notify(a.id,!1)},d);return a}}}();
Elm.Window=function(){var d=Elm.Signal.constant(Value.Tuple(window.innerWidth,window.innerHeight));d.defaultNumberOfKids=2;var a=Elm.Signal.lift(function(a){return a[1]})(d);a.defaultNumberOfKids=0;var e=Elm.Signal.lift(function(a){return a[2]})(d);e.defaultNumberOfKids=0;Value.addListener(window,"resize",function(a){var e=document.getElementById("widthChecker").offsetWidth;Dispatcher.notify(d.id,Value.Tuple(e,window.innerHeight))||this.removeEventListener("resize",arguments.callee,!1)});return{dimensions:d,
width:a,height:e}}();Value.addListener(document,"elm_log",function(d){console.log(d.value)});Value.addListener(document,"elm_title",function(d){document.title=d.value});Value.addListener(document,"elm_redirect",function(d){0<d.value.length&&(window.location=d.value)});Elm=Elm||{};
Elm.Prelude=function(){var d=function(a){return function(e){var h=a%e,h=0==a?0:0<e?0<=a?h:h+e:-d(-a)(-e);return h==e?0:h}};return{eq:Value.eq,id:function(a){return a},not:function(a){return!a},fst:function(a){return a[1]},snd:function(a){return a[2]},rem:function(a){return function(e){return a%e}},div:function(a){return function(e){return~~(a/e)}},compare:function(a){return function(e){a="object"===typeof a?toText(a):a;e="object"===typeof e?toText(e):e;return[a===e?"EQ":a<e?"LT":"GT"]}},toFloat:function(a){return a},
round:function(a){return Math.round(a)},floor:function(a){return Math.floor(a)},ceiling:function(a){return Math.ceil(a)},truncate:function(a){return~~a},readInt:function(a){var a=JavaScript.castStringToJSString(a),e=a.length;if(0===e)return Nothing;var d=0;if("-"==a[0]){if(1===e)return Nothing;d=1}for(;d<e;++d)if(!Char.isDigit(a[d]))return Nothing;return Just(parseInt(a))},readFloat:function(a){var a=JavaScript.castStringToJSString(a),e=a.length;if(0===e)return Nothing;var d=0;if("-"==a[0]){if(1===
e)return Nothing;d=1}for(var i=0;d<e;++d)if(!Char.isDigit(a[d])){if("."===a[d]&&(i+=1,1>=i))continue;return Nothing}return Just(parseFloat(a))},sqrt:Math.sqrt,abs:Math.abs,pi:Math.PI,e:Math.E,sin:Math.sin,cos:Math.cos,tan:Math.tan,asin:Math.asin,acos:Math.acos,atan:Math.atan,atan2:function(a){return function(d){return Math.atan2(a,d)}},mod:d,min:function(a){return function(d){return Math.min(a,d)}},max:function(a){return function(d){return Math.max(a,d)}},flip:function(a){return function(d){return function(h){return a(h)(d)}}},
clamp:function(a){return function(d){return function(h){return Math.min(d,Math.max(a,h))}}},curry:function(a){return function(d){return function(h){return a(["Tuple2",d,h])}}},uncurry:function(a){return function(d){if("Tuple2"!==d[0])throw"Function was uncurry'd but was not given a pair.";return a(d[1])(d[2])}},logBase:function(a){return function(d){return Math.log(d)/Math.log(a)}},Just:Elm.Maybe.Just,Nothing:Elm.Maybe.Nothing,maybe:Elm.Maybe.maybe,map:Elm.List.map,filter:Elm.List.filter,head:Elm.List.head,
tail:Elm.List.tail,last:Elm.List.last,length:Elm.List.length,reverse:Elm.List.reverse,foldr:Elm.List.foldr,foldr1:Elm.List.foldr1,foldl:Elm.List.foldl,foldl1:Elm.List.foldl1,and:Elm.List.and,or:Elm.List.or,all:Elm.List.all,any:Elm.List.any,sum:Elm.List.sum,product:Elm.List.product,concat:Elm.List.concat,concatMap:Elm.List.concatMap,maximum:Elm.List.maximum,minimum:Elm.List.minimum,scanl:Elm.List.scanl,scanl1:Elm.List.scanl1,take:Elm.List.take,drop:Elm.List.drop,zip:Elm.List.zip,unzip:Elm.List.unzip,
lift:Elm.Signal.lift,lift2:Elm.Signal.lift2,lift3:Elm.Signal.lift3,lift4:Elm.Signal.lift4,foldp:Elm.Signal.foldp,foldp1:Elm.Signal.foldp1,foldp_:Elm.Signal.foldp_,constant:Elm.Signal.constant,count:Elm.Signal.count,keepIf:Elm.Signal.keepIf,dropIf:Elm.Signal.dropIf,keepWhen:Elm.Signal.keepWhen,dropWhen:Elm.Signal.dropWhen,dropRepeats:Elm.Signal.dropRepeats,sampleOn:Elm.Signal.sampleOn}}();
(function(){var d=function(a){for(var d in a)Elm.Prelude[d]=a[d]};d(Elm.Color);d(Elm.Text);d(Elm.Graphics);show=Value.show})();
(function(){for(var d in Elm)this[d]=Elm[d];Elm.Automaton=function(){function a(a){return["Automaton",a]}function d(a){return["DragFrom",a]}function h(b){return function(c){var d;a:{switch(b[0]){case "Automaton":d=b[1];break a}throw"Non-exhaustive pattern match in case";}var e;a:{switch(c[0]){case "Automaton":e=c[1];break a}throw"Non-exhaustive pattern match in case";}return a(function(a){var a=d(a),b;a:{switch(a[0]){case "Tuple2":b=a[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(a[0]){case "Tuple2":a=
a[2];break a}throw"Non-exhaustive pattern match in case";}var c=e(b);a:{switch(c[0]){case "Tuple2":b=c[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(c[0]){case "Tuple2":c=c[2];break a}throw"Non-exhaustive pattern match in case";}return["Tuple2",b,h(a)(c)]})}}function i(b){return a(function(a){var c=unzip(map(function(b){a:{switch(b[0]){case "Automaton":b=b[1](a);break a}throw"Non-exhaustive pattern match in case";}return b})(b)),d;a:{switch(c[0]){case "Tuple2":d=c[1];break a}throw"Non-exhaustive pattern match in case";
}a:{switch(c[0]){case "Tuple2":c=c[2];break a}throw"Non-exhaustive pattern match in case";}return["Tuple2",d,i(c)]})}function b(c){return a(function(a){return["Tuple2",c(a),b(c)]})}function k(b){return function(c){return a(function(a){a=c(a)(b);return["Tuple2",a,k(a)(c)]})}}function j(b){return function(c){return a(function(a){var d=c(a)(b);a:{switch(d[0]){case "Tuple2":a=d[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(d[0]){case "Tuple2":d=d[2];break a}throw"Non-exhaustive pattern match in case";
}return["Tuple2",a,j(d)(c)]})}}function f(a){return function(b){a:{switch(a[0]){case "Tuple2":b:{switch(b[0]){case "Tuple2":b=["Tuple2",a[1]-b[1],a[2]-b[2]];break b}break}break a}throw"Non-exhaustive pattern match in case";}return b}}function c(a){return function(b){var c;a:{switch(a[0]){case "Tuple2":b:{switch(b[0]){case "Tuple2":var g=function(a){return["Tuple2",b[2],["Tuple2",a,b[2]]]};c=function(){switch(b[1][0]){case "DragFrom":var c;a[1]?c=["Tuple2",uncurry(move)(f(a[2])(b[1][1]))(b[2]),["Tuple2",
d(b[1][1]),b[2]]]:(c=uncurry(move)(f(a[2])(b[1][1]))(b[2]),c=["Tuple2",c,["Tuple2",q,c]]);return c;case "Ignore":return g(a[1]?r:q);case "Listen":return g(not(a[1])?q:isWithin(a[2])(b[2])?d(a[2]):r)}throw"Non-exhaustive pattern match in case";}();break b}break}break a}throw"Non-exhaustive pattern match in case";}return c}}var g=[],u;for(u in Elm.Prelude)0<=g.indexOf(u)||(this[u]=Elm.Prelude[u]);var q=["Listen"],r=["Ignore"],g=k(0)(function(){return function(a){return 1+a}});return{Automaton:a,run:function(a){return function(b){a:{switch(a[0]){case "Automaton":b=
lift(fst)(foldp_(function(a){return function(b){a:{switch(b[0]){case "Tuple2":switch(b[2][0]){case "Automaton":b=b[2][1](a);break a}}throw"Non-exhaustive pattern match in case";}return b}})(a[1])(b));break a}throw"Non-exhaustive pattern match in case";}return b}},step:function(a){return function(b){a:{switch(a[0]){case "Automaton":b=a[1](b);break a}throw"Non-exhaustive pattern match in case";}return b}},composeAuto:h,combine:i,pure:b,init:k,init_:j,count:g,Listen:q,Ignore:r,DragFrom:d,vecSub:f,stepDrag:c,
draggable:function(a){return j(["Tuple2",q,a])(c)}}}()})();
try{Elm.Website=Elm.Website||{};if(Elm.Website.ColorScheme)throw"Module name collision, 'Website.ColorScheme' is already defined.";Elm.Website.ColorScheme=function(){try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(d){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var a=[],e;for(e in Elm.Prelude)0<=a.indexOf(e)||(this[e]=Elm.Prelude[e]);a=rgb(90)(99)(120);e=rgb(96)(181)(204);var h=rgb(240)(173)(0),i=rgb(234)(21)(122),
b=rgb(127)(209)(59),k=rgb(245)(245)(245),j=rgb(216)(221)(225);return{accent0:a,accent1:e,accent2:h,accent3:i,accent4:b,lightGrey:k,mediumGrey:j}}();Elm.main=function(){return Elm.Website.ColorScheme.main}}catch(e$$62){Elm.main=function(){document.body.innerHTML=Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.ColorScheme module:<br/>'+e$$62+"</span>");throw e$$62;}}
try{Elm.Website=Elm.Website||{};if(Elm.Website.Docs)throw"Module name collision, 'Website.Docs' is already defined.";Elm.Website.Docs=function(){function d(a){return function(b){return bold(Text.height(a)(toText(b)))}}try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(a){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var e=[],h;for(h in Elm.Prelude)0<=e.indexOf(h)||(this[h]=Elm.Prelude[h]);try{if(!(Elm.List instanceof
Object))throw"module not found";}catch(i){throw"Module 'List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var b=Elm.List.intersperse,k=Elm.List.zipWith;try{if(!(Elm.Website.ColorScheme instanceof Object))throw"module not found";}catch(j){throw"Module 'Website.ColorScheme' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}e=[];for(h in Elm.Website.ColorScheme)0<=e.indexOf(h)||(this[h]=Elm.Website.ColorScheme[h]);
try{if(!(Elm.Window instanceof Object))throw"module not found";}catch(f){throw"Module 'Window' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var c=Elm.Window,g=["Cons",accent0,["Cons",accent1,["Cons",accent2,["Cons",accent3,["Cons",accent4,["Nil"]]]]]];return{createDocs:function(a){return function(e){return lift(function(c){var f,h=c-80,i=flow(down);f=text(Text.link(Value.str("/Documentation.elm"))(toText("Back")));var j;j=d(2)(a);j=width(h)(centeredText(j));
var m=spacer(1)(30),p=b(spacer(1)(50));f=i(["Cons",f,["Cons",j,["Cons",m,p(map(function(a){a:{switch(a[0]){case "Tuple2":var b=flow(down),c=text(d(1.25)(a[1])),e=spacer(1)(20),a=b(["Cons",c,["Cons",e,map(function(a){a:{switch(a[0]){case "Tuple3":var b=Text.color(accent1)(toText(" :: ")),c="GT"===compare(length(a[2]))(0)[0]?Value.append(b,toText(a[2])):toText(""),b=flow(down),d=color(mediumGrey)(spacer(h)(1)),c=Value.append(bold(toText(a[1])),c),c=width(h)(color(lightGrey)(text(monospace(c)))),a=b(["Cons",
d,["Cons",c,["Cons",spacer(1)(10),["Cons",flow(right)(["Cons",spacer(50)(10),["Cons",width(h-50)(plainText(a[3])),["Nil"]]]),["Cons",spacer(1)(20),["Nil"]]]]]]);break a}throw"Non-exhaustive pattern match in case";}return a})(a[2])]]);break a}throw"Non-exhaustive pattern match in case";}return a})(e))]]]);var i=flow(down),t=toFloat(c),w=toFloat(10);j=map(function(a){return round(t*(toFloat(a)/w))});m=10;p=["Nil"];if(1<=m){do p=["Cons",m,p];while(1<m--)}j=j(p);j=k(function(a){return function(b){return a-
b}})(j)(["Cons",0,j]);var m=concatMap(function(){return g}),p=div(10)(5),y=["Nil"];if(0<=p){do y=["Cons",p,y];while(0<p--)}m=m(y);j=flow(right)(k(function(a){return function(b){return color(a)(spacer(b)(5))}})(m)(j));m=spacer(c)(15);f=container(c)(heightOf(f))(midTop)(f);p=Value.append(Text.color(rgb(145)(145)(145))(toText("&copy; 2011-2012 ")),Text.link(Value.str("https://github.com/evancz"))(toText("Evan Czaplicki")));c=container(c)(50)(midBottom)(text(p));return i(["Cons",j,["Cons",m,["Cons",f,
["Cons",c,["Nil"]]]]])})(c.width)}}}}();Elm.main=function(){return Elm.Website.Docs.main}}catch(e$$67){Elm.main=function(){document.body.innerHTML=Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Docs module:<br/>'+e$$67+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, Text.link, Window.width, accent0, accent1, accent2, accent3, accent4, lightGrey, mediumGrey</span>");throw e$$67;
}}
try{Elm.Website=Elm.Website||{};if(Elm.Website.Tiles)throw"Module name collision, 'Website.Tiles' is already defined.";Elm.Website.Tiles=function(){function d(a){return function(c){a:{switch(c[0]){case "Cons":c=["Cons",b(a)(c),d(a)(k(a)(c))];break a;case "Nil":c=["Nil"];break a}throw"Non-exhaustive pattern match in case";}return c}}try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(a){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var e=
[],h;for(h in Elm.Prelude)0<=e.indexOf(h)||(this[h]=Elm.Prelude[h]);try{if(!(Elm.List instanceof Object))throw"module not found";}catch(i){throw"Module 'List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var b=Elm.List.take,k=Elm.List.drop,j=Elm.List.intersperse;return{toTile:function(a){var b;a:{switch(a[0]){case "Tuple3":a=["Tuple3",a[1],Value.append(a[3],Value.append(a[2],Value.str(".elm"))),Value.append(Value.str("/screenshot/"),Value.append(a[2],
Value.str(".jpg")))];break a}throw"Non-exhaustive pattern match in case";}b=a;a:{switch(b[0]){case "Tuple3":a=b[1];break a}throw"Non-exhaustive pattern match in case";}var d;a:{switch(b[0]){case "Tuple3":d=b[2];break a}throw"Non-exhaustive pattern match in case";}var e;a:{switch(b[0]){case "Tuple3":e=b[3];break a}throw"Non-exhaustive pattern match in case";}d=link(Value.append(Value.str("/edit/examples/"),d));b=flow(down);e=container(130)(130)(middle)(image(120)(120)(e));a=toText(a);a=width(130)(centeredText(a));
return d(b(["Cons",e,["Cons",a,["Nil"]]]))},tile:function(a){return function(b){b=d(div(a)(130))(b);return flow(down)(j(spacer(1)(14))(map(flow(right))(b)))}}}}();Elm.main=function(){return Elm.Website.Tiles.main}}catch(e$$70){Elm.main=function(){document.body.innerHTML=Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Tiles module:<br/>'+e$$70+"</span>");throw e$$70;}}
try{Elm.Website=Elm.Website||{};if(Elm.Website.Skeleton)throw"Module name collision, 'Website.Skeleton' is already defined.";Elm.Website.Skeleton=function(){try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(d){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var a=[],e;for(e in Elm.Prelude)0<=a.indexOf(e)||(this[e]=Elm.Prelude[e]);try{if(!(Elm.Website.ColorScheme instanceof Object))throw"module not found";}catch(h){throw"Module 'Website.ColorScheme' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";
}a=[];for(e in Elm.Website.ColorScheme)0<=a.indexOf(e)||(this[e]=Elm.Website.ColorScheme[e]);var i=flow(right)(map(function(a){a:{switch(a[0]){case "Tuple3":var d=color(a[3])(spacer(100)(2)),e=container(100)(58)(middle),f;f=toText(a[1]);f=text(Text.color(black)(f));e=e(f);a=link(a[2])(below(d)(e));break a}throw"Non-exhaustive pattern match in case";}return a})(["Cons",["Tuple3",Value.str("About"),Value.str("/About.elm"),accent1],["Cons",["Tuple3",Value.str("Examples"),Value.str("/Examples.elm"),accent2],
["Cons",["Tuple3",Value.str("Docs"),Value.str("/Documentation.elm"),accent3],["Cons",["Tuple3",Value.str("Download"),Value.str("/Download.elm"),accent4],["Nil"]]]]]));return{skeleton:function(a){return function(d){var e="LT"===compare(d)(820)[0]?d-20:800,f=a(e),c=flow(down),g;g=container(d)(60)(middle);var h=beside,e=e-widthOf(i),q;q=toText("Elm");q=text(Text.link(Value.str("/"))(Text.color(black)(Text.height(2)(bold(q)))));e=container(e)(60)(midLeft)(q);g=g(h(e)(i));g=layers(["Cons",flow(down)(["Cons",
color(lightGrey)(spacer(d)(58)),["Cons",color(mediumGrey)(spacer(d)(1)),["Nil"]]]),["Cons",g,["Nil"]]]);h=spacer(d)(10);f=container(d)(heightOf(f))(middle)(f);e=Value.append(Text.color(rgb(145)(145)(145))(toText("&copy; 2011-2012 ")),Text.link(Value.str("https://github.com/evancz"))(toText("Evan Czaplicki")));d=container(d)(50)(midBottom)(text(e));return c(["Cons",g,["Cons",h,["Cons",f,["Cons",d,["Nil"]]]]])}}}}();Elm.main=function(){return Elm.Website.Skeleton.main}}catch(e$$73){Elm.main=function(){document.body.innerHTML=
Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Skeleton module:<br/>'+e$$73+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, Text.link, accent1, accent2, accent3, accent4, below, beside, lightGrey, mediumGrey</span>");throw e$$73;}};