var Guid=function(){var g=0;return{guid:function(){return g+=1}}}(),Foreign=function(){var g=function(a){for(var b=["Nil"],e=a.length;e--;)b=["Cons",a[e],b];return b},e=function(a){for(var b=[];"Cons"===a[0];)b.push(a[1]),a=a[2];return b},b=function(a){return a.slice(1)},a=function(a){return["Tuple"+a.length].concat(a)};return{JavaScript:{castJSBoolToBool:function(a){return a},castBoolToJSBool:function(a){return a},castJSNumberToFloat:function(a){return a},castFloatToJSNumber:function(a){return a},
castJSNumberToInt:function(a){return~~a},castIntToJSNumber:function(a){return a},Experimental:{castJSElementToElement:function(a){return function(b){return function(e){return["Element",Guid.guid(),["EExternalHtml",e],a,b,1,Nothing,Nothing]}}},castElementToJSElement:function(a){return Render.render(a)}},castJSArrayToList:g,castListToJSArray:e,castJSStringToString:g,castStringToJSString:function(a){return"string"===typeof a?a:e(a).join("")},castTupleToJSTuple2:b,castTupleToJSTuple3:b,castTupleToJSTuple4:b,
castTupleToJSTuple5:b,castJSTupleToTuple2:a,castJSTupleToTuple3:a,castJSTupleToTuple4:a,castJSTupleToTuple5:a}}}(),ElmJSON=function(){function g(a){return function(e){function f(a){switch(a[0]){case "JsonNull":return null;case "JsonString":return b.castStringToJSString(a[1]);case "JsonObject":var h={},a=a[1][1],j;for(j in a)h[j]=f(a[j]);return h;case "JsonArray":h=b.castListToJSArray(a[1]);for(j=h.length;j--;)h[j]=f(h[j]);return h;default:return a[1]}}return JSON.stringify(f(["JsonObject",e]),null,
b.castStringToJSString(a))}}function e(a){function e(a){switch(typeof a){case "string":return["JsonString",b.castJSStringToString(a)];case "number":return["JsonNumber",b.castJSNumberToFloat(a)];case "boolean":return["JsonBool",b.castJSBoolToBool(a)];case "object":if(null===a)return["JsonNull"];for(var h in a)a[h]=e(a[h]);return a instanceof Array?["JsonArray",b.castJSArrayToList(a)]:["JsonObject",["JSON",a]]}}var a=JSON.parse(a),f;for(f in a)a[f]=e(a[f]);return["JSON",a]}var b=Foreign.JavaScript;
return{empty:["JSON",{}],singleton:function(a){return function(e){var f={};f[b.castStringToJSString(a)]=e;return["JSON",f]}},insert:function(a){return function(e){return function(f){var f=f[1],g={},h;for(h in f)g[h]=f[h];g[b.castStringToJSString(a)]=e;return["JSON",g]}}},lookup:function(a){return function(e){var f=b.castStringToJSString(a);return e[1].hasOwnProperty(f)?Just(e[1][f]):Nothing}},findWithDefault:function(a){return function(e){return function(f){var g=b.castStringToJSString(e);return f[1].hasOwnProperty(g)?
f[1][g]:a}}},remove:function(a){return function(e){var e=e[1],f={},g;for(g in e)f[g]=e[g];delete f[b.castStringToJSString(a)];return["JSON",f]}},toPrettyJSString:g,toJSString:g(""),fromJSString:e,toPrettyString:function(a){return function(e){return b.castJSStringToString(g(a)(e))}},toString:function(a){return b.castJSStringToString(g("")(a))},fromString:function(a){return e(b.castStringToJSString(a))},toList:function(a){var a=a[1],e=[],f;for(f in a)e.push(Value.Tuple(b.castJSStringToString(f),a[f]));
return b.castJSArrayToList(e)},fromList:function(a){for(var a=b.castListToJSArray(a),e={},f=a.length;f--;)e[b.castStringToJSString(a[f][1])]=a[f][2];return["JSON",e]},JsonString:function(a){return["JsonString",a]},JsonNumber:function(a){return["JsonNumber",a]},JsonBool:function(a){return["JsonBool",a]},JsonNull:["JsonNull"],JsonArray:function(a){return["JsonArray",a]},JsonObject:function(a){return["JsonObject",a]}}}();Foreign.JavaScript.JSON=ElmJSON;
var Value=function(){function g(a){if(0==a.length)return a;for(var a=a.replace(/"/g,"&#34;").replace(/'/g,"&#39;").replace(/</g,"&#60;").replace(/>/g,"&#62;").replace(/\n/g,"<br/>"),a=a.split("<br/>"),b=a.length;b--;){var e=a,g=b,h;h=a[b];if(0!=h.length){h=h.split("");" "==h[0]&&(h[0]="&nbsp;");for(var j=h.length;--j;)" "==h[j][0]&&" "==h[j-1]&&(h[j-1]+=h[j],h[j]="");for(j=h.length;j--;)if(1<h[j].length&&" "==h[j][0]){for(var c=h[j].split(""),d=c.length-2;0<=d;d-=2)c[d]="&nbsp;";h[j]=c.join("")}h=
h.join("")}e[g]=h}return a.join("<br/>")}var e=function(a,b){if("object"===typeof a){if(a===b)return!0;if(a.length!==b.length)return!1;for(var f=a.length;f--;)if(!e(a[f],b[f]))return!1;return!0}return a===b},b=function(a){if("boolean"===typeof a)return a?"True":"False";if("number"!==typeof a){if("string"===typeof a&&2>a.length)return"'"+a+"'";if(a[0]){if("Tuple"===a[0].substring(0,5)){for(var e="",f=a.length;--f;)e=","+b(a[f])+e;","===e[0]&&(e=e.substring(1));return"("+e+")"}if("Cons"===a[0])for(var f=
"string"===typeof a[1]?'"':"]",g="string"===typeof a[1]?"":",",h="string"===typeof a[1]?function(a){return a}:b,e=("string"===typeof a[1]?'"':"[")+h(a[1]),a=a[2];;)if("Cons"===a[0])e+=g+h(a[1]),a=a[2];else return e+f;else{if("Nil"===a[0])return"[]";if("JSON"===a[0])return"(JSON.fromList "+b(ElmJSON.toList(a))+")";e="";for(f=a.length;--f;)e=" "+b(a[f])+e;e=a[0]+e;return 1<a.length?"("+e+")":e}}}return a+""};return{eq:e,str:function(a){for(var b=["Nil"],e=a.length;e--;)b=["Cons",a[e],b];return b},show:function(a){return Text.monospace(g(b(a)))},
Tuple:function(){var a=arguments.length,b=Array(a+1);for(b[0]="Tuple"+arguments.length;a--;)b[a+1]=arguments[a];return b},append:function(a,b){if("string"===typeof a&&"string"===typeof b)return a.concat(b);if("Nil"===a[0])return b;for(var e=["Cons",a[1],["Nil"]],g=e,a=a[2];"Cons"===a[0];)g[2]=["Cons",a[1],["Nil"]],a=a[2],g=g[2];g[2]=b;return e},listToArray:function(a){for(var b=[];"Cons"===a[0];)b.push(a[1]),a=a[2];return b},toText:function(a){if("string"===typeof a)return g(a);for(var b=[];"Cons"===
a[0];)b.push(a[1]),a=a[2];return g(b.join(""))},properEscape:g,getTextSize:function(a,b,e){var g=document.createElement("div");g.innerHTML=e;g.style.textAlign="left";0<a&&(g.style.width=a+"px");g.style.visibility="hidden";g.style.styleFloat="left";g.style.cssFloat="left";document.body.appendChild(g);e=window.getComputedStyle(g);a=e.getPropertyValue("width").slice(0,-2)-0;e=e.getPropertyValue("height").slice(0,-2)-0;document.body.removeChild(g);delete g;return[Math.ceil(a),Math.ceil(Math.max(b,e))]},
getSize:function(a){a=a.cloneNode(!0);a.style.visibility="hidden";a.style.styleFloat="left";a.style.cssFloat="left";document.body.appendChild(a);var b=a.offsetWidth,e=a.offsetHeight;document.body.removeChild(a);delete a;return[b,e]},getExcess:function(a){a=a.cloneNode(!0);a.style.visibility="hidden";a.style.styleFloat="left";a.style.cssFloat="left";document.body.appendChild(a);var b=a.offsetWidth,e=a.offsetHeight,g=window.getComputedStyle(a),h=g.getPropertyValue("width").slice(0,-2)-0,g=g.getPropertyValue("height").slice(0,
-2)-0;document.body.removeChild(a);delete a;return[b-h,e-g]},groupForms:function(a){for(var a=Foreign.JavaScript.castListToJSArray(a),b=[],e=[],g=a.length;g--;){var h=a[g];switch(h[4][0]){case "FElement":0<e.length&&(b.push(e),e=[]);b.push(h);break;default:e.push(h)}}0<e.length&&b.push(e);return b}}}(),List=function(){function g(a){return function(d){if("Nil"===d[0])return d;"Cons"!==d[0]&&c("map");for(var k=["Cons",a(d[1]),["Nil"]],b=k,d=d[2];"Cons"===d[0];)b[2]=["Cons",a(d[1]),["Nil"]],d=d[2],b=
b[2];return k}}function e(a){return function(d){return function(k){var b=d;if("Nil"===k[0])return b;for("Cons"!==k[0]&&c("foldl");"Cons"===k[0];)b=a(k[1])(b),k=k[2];return b}}}function b(a){return function(d){return function(k){var b=d;if("Nil"===k[0])return b;"Cons"!==k[0]&&c("foldr");for(var e=[];"Cons"===k[0];)e.push(k[1]),k=k[2];for(k=e.length;k--;)b=a(e[k])(b);return b}}}function a(a){return function(c){var k;"Cons"!==c[0]?k=void 0:(k=c[1],c=c[2],k=e(a)(k)(c));return k}}function l(a){return function(d){return function(k){if("Nil"===
k[0])return["Cons",d,["Nil"]];"Cons"!==k[0]&&c("scanl");for(var b=[d];"Cons"===k[0];)d=a(k[1])(d),b.push(d),k=k[2];for(var k=["Nil"],e=b.length;e--;)k=["Cons",b[e],k];return k}}}function f(a){return function(c){a:{for(var d=[function(a){return"Nil"!==a[0]?void 0:["Tuple2",["Nil"],["Nil"]]},function(c){if("Cons"===c[0]){var d=c[1],c=c[2];var b=f(a)(c);"Tuple2"!==b[0]?d=void 0:(c=b[1],b=b[2],d=a(d)?["Tuple2",["Cons",d,c],b]:["Tuple2",c,["Cons",d,b]]);return d}}],b=d.length;b--;){var e=d[b](c);if(void 0!==
e){c=e;break a}}c=void 0}return c}}function n(a){a:{for(var c=[function(a){return"Nil"!==a[0]?void 0:["Tuple2",["Nil"],["Nil"]]},function(a){if("Cons"!==a[0])a=void 0;else if(a=["Tuple2",a[1],n(a[2])],"Tuple2"!==a[0]||"Tuple2"!==a[1][0])a=void 0;else var c=a[1][1],d=a[1][2],a="Tuple2"!==a[2][0]?void 0:["Tuple2",["Cons",c,a[2][1]],["Cons",d,a[2][2]]];return a}],d=c.length;d--;){var b=c[d](a);if(void 0!==b){a=b;break a}}a=void 0}return a}function h(a){return function(c){a:{for(var d=[function(a){return"Nil"!==
a[0]?void 0:["Nil"]},function(a){if("Cons"===a[0]){var c=a[1];return"Nil"!==a[2][0]?void 0:["Cons",c,["Nil"]]}},function(c){if("Cons"===c[0]){var d=c[1];if("Cons"===c[2][0]){var b=c[2][1],c=c[2][2];return["Cons",d,["Cons",a,h(a)(["Cons",b,c])]]}}}],b=d.length;b--;){var e=d[b](c);if(void 0!==e){c=e;break a}}c=void 0}return c}}function j(a){return function(c){a:{for(var d=[function(a){return"Nil"!==a[0]?void 0:["Nil"]},function(a){if("Cons"===a[0]){var c=a[1];return"Nil"!==a[2][0]?void 0:c}},function(c){if("Cons"===
c[0]){var d=c[1];if("Cons"===c[2][0]){var b=c[2][1],c=c[2][2];return Value.append(d,Value.append(a,j(a)(["Cons",b,c])))}}}],b=d.length;b--;){var e=d[b](c);if(void 0!==e){c=e;break a}}c=void 0}return c}}var c=function(a){throw"Function '"+a+"' expecting a list!";},d=e(function(a){return function(c){return["Cons",a,c]}})(["Nil"]),t=b(function(a){return function(c){return Value.append(a,c)}})(["Nil"]),p=e(function(a){return function(c){return a&&c}})(!0),r=e(function(a){return function(c){return a||
c}})(!1),i=e(function(a){return function(c){return a+c}})(0),m=e(function(a){return function(c){return a*c}})(1),v=a(function(a){return function(c){return Math.max(a,c)}}),s=a(function(a){return function(c){return Math.min(a,c)}});return{head:function(a){if("Cons"!==a[0])throw"Error: 'head' only accepts lists of length greater than one.";return a[1]},tail:function(a){if("Cons"!==a[0])throw"Error: 'tail' only accepts lists of length greater than one.";return a[2]},last:function(a){if("Cons"!==a[0])throw"Error: 'last' only accepts lists of length greater than one.";
for(var c=a[1];"Cons"===a[0];)c=a[1],a=a[2];return c},map:g,foldl:e,foldr:b,foldl1:a,foldr1:function(a){return function(d){if("Nil"===d[0])throw"'foldr1' requires an non-empty list.";"Cons"!==d[0]&&c("foldr1");for(var b=[];"Cons"===d[0];)b.push(d[1]),d=d[2];for(var d=b.pop(),e=b.length;e--;)d=a(b[e])(d);return d}},scanl:l,scanl1:function(a){return function(c){if("Cons"!==c[0])throw"Error: 'scanl1' requires a list of at least length 1.";return l(a)(c[1])(c[2])}},filter:function(a){return function(d){if("Nil"===
d[0])return d;"Cons"!==d[0]&&c("filter");for(var b=[];"Cons"===d[0];)a(d[1])&&b.push(d[1]),d=d[2];for(var d=["Nil"],e=b.length;e--;)d=["Cons",b[e],d];return d}},length:function(a){for(var c=0;"Cons"===a[0];)c+=1,a=a[2];return c},reverse:d,concat:t,concatMap:function(a){return function(c){return t(g(a)(c))}},and:p,or:r,forall:function(a){return e(function(c){return function(d){return d&&a(c)}})(!0)},exists:function(a){return e(function(c){return function(d){return d||a(c)}})(!1)},sum:i,product:m,maximum:v,
minimum:s,partition:f,zipWith:function(a){return function(d){return function(b){if("Nil"===d[0]||"Nil"===b[0])return["Nil"];("Cons"!==d[0]||"Cons"!==b[0])&&c("zipWith");for(var e=[];"Cons"===d[0]&&"Cons"===b[0];)e.push(a(d[1])(b[1])),d=d[2],b=b[2];for(var b=["Nil"],j=e.length;j--;)b=["Cons",e[j],b];return b}}},zip:function(a){return function(d){if("Nil"===a[0]||"Nil"===d[0])return["Nil"];("Cons"!==a[0]||"Cons"!==d[0])&&c("zip");for(var b=[];"Cons"===a[0]&&"Cons"===d[0];)b.push(["Tuple2",a[1],d[1]]),
a=a[2],d=d[2];for(var d=["Nil"],e=b.length;e--;)d=["Cons",b[e],d];return d}},unzip:n,intersperse:h,intercalate:j,sort:function(a){if("Nil"===a[0])return a;"Cons"!==a[0]&&c("sort");for(var d=[];"Cons"===a[0];)d.push(a[1]),a=a[2];d.sort(function(a,c){return a-c});for(var a=["Nil"],b=d.length;b--;)a=["Cons",d[b],a];return a},take:function(a){return function(d){if(0>=a)return["Nil"];if("Nil"===d[0])return d;"Cons"!==d[0]&&c("take");var b=["Cons",d[1],["Nil"]],e=b,d=d[2];for(--a;"Cons"===d[0]&&0<a;)e[2]=
["Cons",d[1],["Nil"]],e=e[2],d=d[2],--a;return b}},drop:function(a){return function(d){if("Nil"===d[0])return d;for("Cons"!==d[0]&&c("drop");"Cons"===d[0]&&0<a;)d=d[2],--a;return d}}}}(),Data=function(){var g;g=function(b){return function(a){return"Just"===b[0]?["Cons",b[1],a]:a}};var e=function(b){return function(a){return function(e){var g=b(a);return"Just"===g[0]?["Cons",g[1],e]:e}}};g={Just:function(b){return["Just",b]},Nothing:["Nothing"],catMaybes:List.foldr(g)(["Nil"]),isJust:function(b){return"Just"===
b[0]},isNothing:function(b){return"Nothing"===b[0]},fromMaybe:function(b){return function(a){return"Just"===a[0]?a[1]:b}},consMaybe:g,mapMaybe:function(b){return List.foldr(e(b))(["Nil"])},maybe:function(b){return function(a){return function(e){return"Just"===e[0]?a(e[1]):b}}}};return{String:{toText:Value.toText,properEscape:Value.properEscape},Char:{fromCode:function(b){return String.fromCharCode(b)},toCode:function(b){return b.charCodeAt(0)},toUpper:function(b){return b.toUpperCase()},toLower:function(b){return b.toLowerCase()},
toLocaleUpper:function(b){return b.toLocaleUpperCase()},toLocaleLower:function(b){return b.toLocaleLowerCase()}},Maybe:g,List:List}}(),ElmCode=ElmCode||{};ElmCode.Graphics=ElmCode.Graphics||{};
ElmCode.Graphics.Color=function(){return{rgba:function(g){return function(e){return function(b){return function(a){return["Color",g,e,b,a]}}}},rgb:function(g){return function(e){return function(b){return["Color",g,e,b,1]}}},red:["Color",255,0,0,1],green:["Color",0,255,0,1],blue:["Color",0,0,255,1],yellow:["Color",255,255,0,1],cyan:["Color",0,255,255,1],magenta:["Color",255,0,255,1],black:["Color",0,0,0,1],white:["Color",255,255,255,1],gray:["Color",128,128,128,1],grey:["Color",128,128,128,1],extract:function(g){return 1===
g[4]?"rgb("+g[1]+","+g[2]+","+g[3]+")":"rgba("+g[1]+","+g[2]+","+g[3]+","+g[4]+")"}}}();
var Collage=function(){function g(a,b){var c=b.length-1;if(!(0>=c))for(a.moveTo(b[c][1],b[c][2]);c--;)a.lineTo(b[c][1],b[c][2])}function e(a,b,c,d){0===a.length&&(a=[8,4]);var e=d.length-1;if(!(0>=e)){var g=d[e][1],r=d[e][2],f=0,m=0,n=0,s=0,q=0,l=0,k=a.length,x=!0,w=a[0];for(b.moveTo(g,r);e--;){f=d[e][1];m=d[e][2];n=f-g;s=m-r;for(q=Math.sqrt(n*n+s*s);w<=q;)g+=n*w/q,r+=s*w/q,b[x?"lineTo":"moveTo"](g,r),n=f-g,s=m-r,q=Math.sqrt(n*n+s*s),x=!x,l=(l+1)%k,w=a[l];0<q&&(b[x?"lineTo":"moveTo"](f,m),w-=q);g=
f;r=m}}b.strokeStyle=ElmCode.Graphics.Color.extract(c);b.stroke()}function b(a,b,c,d,t){b.clearRect(0,0,c,d);for(c=t.length;c--;){var p=t[c],f=a,d=b,i=p[1],m=p[2],n=p[3][1],l=p[3][2],p=p[4];d.save();(0!==n||0!==l)&&d.translate(n,l);i!==~~i&&d.rotate(2*Math.PI*i);1!==m&&d.scale(m,m);d.beginPath();switch(p[0]){case "FLine":a:switch(f=d,i=p,p=i[3][1],i[1][0]){case "Solid":i=i[2];g(f,p);f.strokeStyle=ElmCode.Graphics.Color.extract(i);f.stroke();break;case "Dotted":e([3,3],f,i[2],p);break a;case "Dashed":e([8,
4],f,i[2],p);break a;case "Custom":e(i[1][1],f,i[2],p)}break;case "FShape":a:switch(n=f,m=d,f=p[1],i=p[2],p=p[3][1],f[0]){case "Filled":f=m;g(f,p);f.fillStyle=ElmCode.Graphics.Color.extract(i);f.fill();break a;case "Outlined":f=m;g(f,p);f.strokeStyle=ElmCode.Graphics.Color.extract(i);f.stroke();break a;case "Textured":i=n;f=f[1];n=new Image;n.src=Foreign.JavaScript.castStringToJSString(f);n.onload=i;g(m,p);m.fillStyle=m.createPattern(n,"repeat");m.fill();break a;case "CustomOutline":e(f[1],m,i,p)}break;
case "FImage":i=d,m=p[1],n=p[2],p=p[3],l=new Image,l.onload=f,l.src=Foreign.JavaScript.castStringToJSString(p),i.drawImage(l,-m/2,-n/2,m,n)}d.restore()}}function a(a,e,c){var d=Render.newElement("canvas");d.style.width=~~a+"px";d.style.height=~~e+"px";d.style.display="block";d.width=~~a;d.height=~~e;if(d.getContext){var t=d.getContext("2d"),a=d.width,e=d.height;b(function(){b(this,t,a,e,c)},t,a,e,c);return d}d.innerHTML="Your browser does not support the canvas element.";return d}function l(a,b,c,
d,e,g,f){var i=Render.render(f),c="translate("+(e-f[3]/2)+"px,"+(g-f[4]/2)+"px) "+(1===d?"":"scale("+d+","+d+")")+" "+(c===~~c?"":"rotate("+360*c+"deg)");i.style.transform=c;i.style.msTransform=c;i.style.MozTransform=c;i.style.webkitTransform=c;i.style.OTransform=c;c=Render.newElement("div");Render.addTo(c,i);c.style.width=~~a+"px";c.style.height=~~b+"px";c.style.overflow="hidden";return c}function f(e,j,c){if(!Value.eq(c,j)){var d=e.style.width.slice(0,-2)-0,g=e.style.height.slice(0,-2)-0;if("object"===
typeof c[0]){if("object"===typeof j[0]&&e.getContext){var f=e.getContext("2d");return b(function(){b(this,f,d,g,c)},f,d,g,c)}j=a(d,g,c);j.style.position="absolute";return e.parentNode.replaceChild(j,e)}j=l(d,g,c[1],c[2],c[3][1],c[3][2],c[4][1]);j.style.position="absolute";return e.parentNode.replaceChild(j,e)}}function n(a,b,c,d,e){var g=0,f,i=(a[1]-d[1])/c,a=(a[2]-d[2])/c;0!==b&&(b*=2*Math.PI,b=0===i?(0<a?Math.PI/2:-Math.PI/2)-b:Math.atan(a/i)+(0<i?0:Math.PI)-b,a=Math.sqrt(i*i+a*a),i=a*Math.cos(b),
a*=Math.sin(b));if(0===e.length)return!1;f=e[0];for(c=e.length-1;c--;){b=e[c];d=f[1];f=f[2];var n=b[1],l=b[2];if(f<l)var s=f,q=l;else s=l,q=f;if(d<n)var u=d,k=n;else u=n,k=d;s<a&&a<=q&&i<=k&&(i<=u||i<=(a-f)*(n-d)/(l-f)+d)&&++g;f=b}return 1===g%2}return{collage:function(b,e,c){if(0===c.length)return a(b,e,[]);for(var d=Array(c.length),g=c.length;g--;){var f=c[g];d[g]="string"===typeof f[0]?l(b,e,f[1],f[2],f[3][1],f[3][2],f[4][1]):a(b,e,f)}return 1===c.length?d[0]:Render.flowWith(Render.goIn,function(a){return a},
d)},updateCollage:function(a,b,c){if(1===c.length)return f(a,b[0],c[0]);for(var a=a.childNodes,d=a.length,e=d;e--;)f(a[d-e-1],b[e],c[e])},insideForm:function(a){return function(b){var c=a[1],d=a[2];if(6>b.length){var e=b[3][1],g=b[3][2],f=0,i=b[2];switch(b[4][0]){case "FShape":for(var m=b[4][3][1],l=m.length;--l;)var s=m[l],f=Math.max(f,s[1]*s[1]+s[2]*s[2]);f*=i*i;break;case "FImage":m=i*b[4][1]/2;i=i*b[4][2]/2;f=m*m+i*i;break;case "FElement":m=i*b[4][1][3]/2,i=i*b[4][1][4]/2,f=m*m+i*i}b.push(function(a,
c){var b=a-e,d=c-g;return b*b+d*d<f+1})}if(!b[5](c,d))return!1;var q,u;switch(b[4][0]){case "FShape":return n(a,b[1],b[2],b[3],b[4][3][1]);case "FLine":return!1;case "FImage":q=b[4][1]/2;u=b[4][2]/2;break;case "FElement":q=b[4][1][3]/2,u=b[4][1][4]/2}return n(a,b[1],b[2],b[3],[[null,q,u],[null,-q,u],[null,-q,-u],[null,q,-u],[null,q,u]])}}}}(),ElmCode=ElmCode||{};ElmCode.Graphics=ElmCode.Graphics||{};
ElmCode.Graphics.Element=function(){function g(a){return function(c){return["Position",a,c]}}function e(a){return function(c){return["EText",a,c]}}function b(a){return function(c){return["EFlow",a,Foreign.JavaScript.castListToJSArray(c)]}}function a(a){return["Line",Foreign.JavaScript.castListToJSArray(a)]}function l(a){return function(c){var b=Foreign.JavaScript.castListToJSArray(a);0<b.length&&b.push(b[0]);return["Shape",b,c]}}function f(a){return function(c){return function(b){return function(d){return["Form",
a,c,b,d]}}}}function n(a){return function(c){return function(b){return["FLine",a,c,b]}}}function h(a){return function(c){return function(b){return["FShape",a,c,b]}}}function j(a,c,b,d,e,k){return["Element",Guid.guid(),a,c,b,d,e,k]}function c(a,c,b){return["Element",Guid.guid(),a,c,b,1,Nothing,Nothing]}function d(a){return~~a[3]}function t(a){return~~a[4]}function p(a){return function(b){return function(d){return c(["EImage",Foreign.JavaScript.castStringToJSString(d)],a,b)}}}function r(a){return function(b){return c(x,
a,b)}}function i(a){return function(c){return function(b){var d=map(function(b){return["Tuple2",a/2*cos(2*(pi/50)*b),c/2*sin(2*(pi/50)*b)]}),e=49,k=["Nil"];if(0<=e){do k=["Cons",e,k];while(0<e--)}return l(d(k))(b)}}}var m=["DRight"],v=["DDown"],s=["DOut"],q=["Near"],u=["Mid"],k=["Far"],x=["EEmpty"],w=["Solid"],y=["Dotted"],z=["Dashed"],A=["Filled"],B=["Outlined"],C=g(q)(q),D=g(k)(q),E=g(q)(k),F=g(k)(k),G=g(q)(u),H=g(k)(u),q=g(u)(q),k=g(u)(k),u=g(u)(u);return{left:["DLeft"],right:m,down:v,up:["DUp"],
inward:["DIn"],outward:s,topLeft:C,topRight:D,bottomLeft:E,bottomRight:F,midLeft:G,midRight:H,midTop:q,midBottom:k,middle:u,middleAt:function(a){return function(c){return["PositionAt",a,c]}},topLeftAt:function(a){return function(c){return["PositionTL",a,c]}},topRightAt:function(a){return function(c){return["PositionTR",a,c]}},bottomLeftAt:function(a){return function(c){return["PositionBL",a,c]}},bottomRightAt:function(a){return function(c){return["PositionBR",a,c]}},absolute:function(a){return["Absolute",
a]},relative:function(a){return["Relative",a]},width:function(a){return function(c){var b=c[2];switch(b[0]){case "EImage":case "EVideo":return j(c[2],a,c[4]*a/c[3],c[5],c[6],c[7]);case "EText":return b=Value.getTextSize(a,c[4],b[2]),j(c[2],a,b[1],c[5],c[6],c[7])}return j(c[2],a,c[4],c[5],c[6],c[7])}},height:function(a){return function(c){switch(c[2][0]){case "EImage":case "EVideo":return j(c[2],c[3]*a/c[4],a,c[5],c[6],c[7])}return j(c[2],c[3],a,c[5],c[6],c[7])}},size:function(a){return function(c){return function(b){return j(b[2],
a,c,b[5],b[6],b[7])}}},opacity:function(a){return function(c){return j(c[2],c[3],c[4],a,c[6],c[7])}},color:function(a){return function(c){return j(c[2],c[3],c[4],c[5],Just(a),c[7])}},link:function(a){return function(c){return j(c[2],c[3],c[4],c[5],c[6],Just(Foreign.JavaScript.castStringToJSString(a)))}},widthOf:d,heightOf:t,sizeOf:function(a){return["Tuple2",~~a[3],~~a[4]]},text:function(a){var b=Value.getTextSize(0,0,a);return c(e("left")(a),b[0],b[1])},asText:function(a){var a=Value.show(a),b=Value.getTextSize(0,
0,a);return c(e("left")(a),b[0],b[1])},plainText:function(a){var a=Value.toText(a),b=Value.getTextSize(0,0,a);return c(e("left")(a),b[0],b[1])},centeredText:function(a){var b=Value.getTextSize(0,0,a);return c(e("center")(a),b[0],b[1])},justifiedText:function(a){var b=Value.getTextSize(0,0,a);return c(e("justify")(a),b[0],b[1])},rightedText:function(a){var b=Value.getTextSize(0,0,a);return c(e("right")(a),b[0],b[1])},image:p,images:function(a){var c=Elm.Input(r(0)(0)),a=Elm.Lift(function(a){var a=
Foreign.JavaScript.castStringToJSString(a),b=new Image;b.onload=function(){console.log("loaded");Dispatcher.notify(c.id,p(this.width)(this.height)(a))};b.src=a},[a]);return Elm.Lift(function(a){return function(){return a}},[c,a])},video:function(a){return function(b){return function(d){return c(["EVideo",Foreign.JavaScript.castStringToJSString(d)],a,b)}}},fittedImage:function(a){return function(b){return function(d){return c(["EFittedImage",Foreign.JavaScript.castStringToJSString(d)],a,b)}}},flow:function(a){return function(e){var k;
k=map(d)(e);a:{switch(a[0]){case "DLeft":k=sum(k);break a;case "DRight":k=sum(k);break a}k=maximum(k)}var g;g=map(t)(e);a:{switch(a[0]){case "DDown":g=sum(g);break a;case "DUp":g=sum(g);break a}g=maximum(g)}return c(b(a)(e),k,g)}},above:function(a){return function(d){return c(b(v)(["Cons",a,["Cons",d,["Nil"]]]),max(~~a[3])(~~d[3]),~~a[4]+~~d[4])}},below:function(a){return function(d){return c(b(v)(["Cons",d,["Cons",a,["Nil"]]]),max(~~a[3])(~~d[3]),~~a[4]+~~d[4])}},beside:function(a){return function(d){return c(b(m)(["Cons",
a,["Cons",d,["Nil"]]]),~~a[3]+~~d[3],max(~~a[4])(~~d[4]))}},layers:function(a){return c(b(s)(a),maximum(map(d)(a)),maximum(map(t)(a)))},collage:function(a){return function(b){return function(d){return c(["ECollage",a,b,Value.groupForms(d)],a,b)}}},spacer:r,container:function(a){return function(b){return function(d){return function(e){return c(["EContainer",d,e],a,b)}}}},line:a,segment:function(c){return function(b){return a(["Cons",c,["Cons",b,["Nil"]]])}},polygon:l,rect:function(a){return function(c){return function(b){return l(["Cons",
["Tuple2",0-a/2,0-c/2],["Cons",["Tuple2",0-a/2,c/2],["Cons",["Tuple2",a/2,c/2],["Cons",["Tuple2",a/2,0-c/2],["Nil"]]]]])(b)}}},oval:i,circle:function(a){return i(2*a)(2*a)},ngon:function(a){return function(c){return function(b){var d=toFloat(a),e=map(function(a){return["Tuple2",c*cos(2*(pi/d)*a),c*sin(2*(pi/d)*a)]}),k=a-1,g=["Nil"];if(0<=k){do g=["Cons",k,g];while(0<k--)}return l(e(g))(b)}}},solid:function(a){return function(c){return f(0)(1)(["Tuple2",0,0])(n(w)(a)(c))}},dotted:function(a){return function(c){return f(0)(1)(["Tuple2",
0,0])(n(y)(a)(c))}},dashed:function(a){return function(c){return f(0)(1)(["Tuple2",0,0])(n(z)(a)(c))}},customLine:function(a){return function(c){return function(b){return f(0)(1)(["Tuple2",0,0])(n(["Custom",Foreign.JavaScript.castListToJSArray(a)])(c)(b))}}},filled:function(a){return function(c){return f(0)(1)(c[2])(h(A)(a)(c))}},outlined:function(a){return function(c){return f(0)(1)(c[2])(h(B)(a)(c))}},customOutline:function(a){return function(c){return function(b){return f(0)(1)(b[2])(h(["CustomOutline",
Foreign.JavaScript.castListToJSArray(a)])(c)(b))}}},textured:function(a){return function(c){return f(0)(1)(c[2])(h(["Textured",a])(null)(c))}},sprite:function(a){return function(c){return function(b){return function(d){return f(0)(1)(d)(["FImage",c,b,Foreign.JavaScript.castStringToJSString(a)])}}}},toForm:function(a){return function(c){return f(0)(1)(a)(["FElement",c])}},rotate:function(a){return function(c){a:{switch(c[0]){case "Form":var b=c[2],d=c[3],e=c[4],c=f(a+c[1])(b)(d)(e);break a}throw"Non-exhaustive pattern match in case";
}return c}},scale:function(a){return function(c){return f(c[1])(a*c[2])(c[3])(c[4])}},move:function(a){return function(c){return function(b){var d;a:{switch(b[0]){case "Form":d=b[1];var e=b[2],k=b[3],b=b[4];switch(k[0]){case "Tuple2":var g=k[1],k=k[2];d=f(d)(e)(["Tuple2",a+g,c+k])(b);break a}}throw"Non-exhaustive pattern match in case";}return d}}},isWithin:Collage.insideForm}}();
var Text=function(){function g(a){return Value.toText(a)}var e=function(a){return function(b){return"<"+a+' style="padding:0;margin:0">'+b+"</"+a+">"}},b=function(a,b){return function(e){return"<span style='"+a+":"+b+"'>"+e+"</span>"}},a=function(a){a=Foreign.JavaScript.castStringToJSString(a);return b("font-family",a)},l=e("h1"),f=b("font-style","italic"),e=e("b"),n=b("text-decoration","underline"),h=b("text-decoration","overline"),j=b("text-decoration","line-through");return{fromString:g,toText:g,
header:l,height:function(a){return b("font-size",a+"em")},italic:f,bold:e,underline:n,overline:h,strikeThrough:j,monospace:a("monospace"),typeface:a,color:function(a){return b("color",ElmCode.Graphics.Color.extract(a))},link:function(a){return function(b){return"<a href='"+g(a)+"'>"+b+"</a>"}}}}(),Render=function(){function g(a){a=document.createElement(a);a.style.padding="0";a.style.margin="0";return a}function e(a){return a}function b(a){a.style.styleFloat="left";a.style.cssFloat="left";return a}
function a(a){a.style.position="absolute";return a}function l(a,b,e){for(var f=g("div"),j=e.length;j--;){var h=a(b(e[j]));f.appendChild(h)}return f}function f(a){switch(a[0]){case "Absolute":return a[1]+"px";case "Relative":return 100*a[1]+"%"}}function n(a,b){b.style.position="absolute";b.style.margin="auto";switch(a[0]){case "Position":"Far"!==a[1][0]&&(b.style.left=0);"Near"!==a[1][0]&&(b.style.right=0);"Far"!==a[2][0]&&(b.style.top=0);"Near"!==a[2][0]&&(b.style.bottom=0);break;case "PositionAt":b.style.top=
f(a[2]);b.style.left=f(a[1]);var e="translate("+-elem[3]/2+"px,"+-elem[4]/2+"px)";b.style.transform=e;b.style.msTransform=e;b.style.MozTransform=e;b.style.webkitTransform=e;b.style.OTransform=e;break;default:e=a[0].slice(-2),b.style["T"===e[0]?"top":"bottom"]=f(a[2]),b.style["L"===e[1]?"left":"right"]=f(a[1])}}function h(c){var d={};switch(c[2][0]){case "EText":var d=c[2][1],f=c[2][2],j=g("div");j.innerHTML=f;j.style.textAlign=d;d=j;break;case "EImage":d=c[2][1];f=g("img");f.src=d;f.name=d;f.style.display=
"block";d=f;break;case "EVideo":j=c[2][1];d=g("video");d.controls="controls";f=g("source");f.src=j;j=j.split(".");f.type="video/"+j[j.length-1];d.appendChild(f);d.style.display="block";break;case "EFittedImage":var r=c[3],i=c[4],d=c[2][1],m=g("canvas");m.style.display="block";m.style.width=r+"px";m.style.height=i+"px";m.width=r;m.height=i;m.innerHTML="Your browser does not support the canvas element.";var v=g("img");v.onload=function(){if(m.getContext){var a=m.getContext("2d"),b=0,c=0,d=this.width,
e=this.height;r/i>this.width/this.height?(e=this.width*i/r,c=(this.height-e)/2):(d=this.height*r/i,b=(this.width-d)/2);a.drawImage(v,b,c,d,e,0,0,m.width,m.height)}};v.src=d;d=m;break;case "EFlow":a:{d=c[2][2];switch(c[2][1][0]){case "DDown":d=d.slice(0).reverse();case "DUp":d=l(e,h,d);break a;case "DRight":d=d.slice(0).reverse();case "DLeft":d=l(b,h,d);break a;case "DOut":d=d.slice(0).reverse();case "DIn":d=l(a,h,d);break a}d=void 0}break;case "ECollage":d=Collage.collage(c[2][1],c[2][2],c[2][3]);
break;case "EEmpty":d=g("div");break;case "EContainer":f=c[2][1];d=h(c[2][2]);n(f,d);f=g("div");f.style.position="relative";f.style.overflow="hidden";f.appendChild(d);d=f;break;case "EHtml":d=c[2][1];"button"!==d.type&&(f=Value.getExcess(d),c[3]-=f[0],c[4]-=f[1]);break;case "EExternalHtml":d=g("div"),d.appendChild(c[2][1])}d.id=c[1];d.style.width=~~c[3]+"px";d.style.height=~~c[4]+"px";1!==c[5]&&(d.style.opacity=c[5]);"Just"===c[6][0]&&(d.style.backgroundColor=ElmCode.Graphics.Color.extract(c[6][1]));
return"Just"===c[7][0]?(f=g("a"),f.href=c[7][1],f.appendChild(d),f):d}function j(c,d,f){"A"===c.tagName&&(c=c.firstChild);if(d[1]!==f[1]){if(d[2][0]!==f[2][0])return c.parentNode.replaceChild(h(f),c);var g=f[2],l=d[2];switch(g[0]){case "EText":g[1]!==l[1]&&(c.style.textAlign=g[1]);g[2]!==l[2]&&(c.innerHTML=g[2]);break;case "EImage":g[1]!==l[1]&&(c.src=g[1]);break;case "EVideo":case "EFittedImage":if(!Value.eq(g,l)||f[3]!==d[3]||f[4]!==d[4])return c.parentNode.replaceChild(h(f),c);break;case "ECollage":if(g[1]!==
l[1]||g[2]!==l[2]||g[3].length!==l[3].length)return c.parentNode.replaceChild(h(f),c);Collage.updateCollage(c,l[3],g[3]);break;case "EFlow":if(g[1]!==l[1])return c.parentNode.replaceChild(h(f),c);var i=g[2],m=c.childNodes;if(i.length!==m.length)return c.parentNode.replaceChild(h(f),c);var l=l[2],v={};switch(g[1][0]){case "DDown":case "DUp":v=e;break;case "DRight":case "DLeft":v=b;break;case "DOut":case "DIn":v=a}for(g=m.length;g--;)j(m[g],l[g],i[g]),v(m[g]);break;case "EContainer":j(c.childNodes[0],
l[2],g[2]);n(g[1],c.childNodes[0]);break;case "EHtml":f[1]!==d[1]&&(i=h(f),c.parentNode.replaceChild(i,c),c=i);"button"!==i.type&&(g=Value.getExcess(c),f[3]-=g[0],f[4]-=g[1]);break;case "EExternalHtml":f[1]!==d[1]&&c.parentNode.replaceChild(h(f),c)}f[3]!==d[3]&&(c.style.width=~~f[3]+"px");f[4]!==d[4]&&(c.style.height=~~f[4]+"px");f[5]!==d[5]&&(c.style.opacity=f[5]);2===f[6].length&&(g=ElmCode.Graphics.Color.extract(f[6][1]),g!==c.style.backgroundColor&&(c.style.backgroundColor=g));if(2===f[7].length&&
(1===d[7].length||f[7][1]!==d[7][1]))c.parentNode.href=f[7][1];f[1]=d[1]}}return{render:h,update:j,addTo:function(a,b){a.appendChild(b)},newElement:g,flowWith:l,goIn:a}}(),Elm=function(){var g=function(a,b,d){for(var e=a.kids,f=e.length;f--;)e[f].recv(b,d,a.id)},e=function(a){this.id=Guid.guid();this.value=a;this.kids=[];this.defaultNumberOfKids=0;this.recv=function(a,b,e){if(b=b===this.id)this.value=e;g(this,a,b);return b};Dispatcher.inputs.push(this)},b=function(a,b){this.id=Guid.guid();this.value=
null;this.kids=[];this.count=0;this.changed=!1;b.reverse();this.recalc=function(){for(var d=a,e=b.length;e--;)d=d(b[e].value);this.value=d};this.recalc();this.recv=function(a,d){this.count+=1;d&&(this.changed=!0);this.count==b.length&&(this.changed&&this.recalc(),g(this,a,this.changed),this.changed=!1,this.count=0)};for(var d=b.length;d--;)b[d].kids.push(this)},a=function(a,b,d,e){this.id=Guid.guid();this.value=d?b(e.value):b;this.kids=[];this.recv=function(b,c){c&&(this.value=a(e.value)(this.value));
g(this,b,c)};e.kids.push(this)},l=function(a,b,d){this.id=Guid.guid();this.value=a(d.value)?b:d.value;this.kids=[];this.recv=function(b,c){var e=c&&!a(d.value);e&&(this.value=d.value);g(this,b,e)};d.kids.push(this)},f=function(a){this.id=Guid.guid();this.value=a.value;this.kids=[];this.recv=function(b,d){var e=d&&!eq(this.value,a.value);e&&(this.value=a.value);g(this,b,e)};a.kids.push(this)},n=function(a){return function(c){return function(d){d=new b(function(a){return function(b){return[a,b]}},[a,
d]);d=new l(function(a){return a[0]},[!0,c],d);return new b(function(a){return a[1]},[d])}}},h=function(a,b){this.id=Guid.guid();this.value=b.value;this.kids=[];this.count=0;this.changed=!1;this.recv=function(d,e,f){f===a.id&&(this.changed=e);this.count+=1;2==this.count&&(this.changed&&(this.value=b.value),g(this,d,this.changed),this.count=0,this.changed=!1)};a.kids.push(this);b.kids.push(this)};return{Input:function(a){return new e(a)},Lift:function(a,c){return new b(a,c)},Fold:function(b,c,d){return new a(b,
c,!1,d)},Fold1:function(b,c,d){return new a(b,c,!0,d)},keepIf:function(a){return function(b){return function(d){return new l(function(b){return!a(b)},b,d)}}},dropIf:function(a){return function(b){return function(d){return new l(a,b,d)}}},keepWhen:function(a){return n(new b(function(a){return!a},[a]))},dropWhen:n,dropRepeats:function(a){return new f(a)},sampleOn:function(a){return function(b){return new h(a,b)}}}}(),Dispatcher=function(){function g(a){if(!a.hasOwnProperty("defaultNumberOfKids"))return!0;
var b=a.kids.length;if(0==b)return!1;if(b>a.defaultNumberOfKids)return!0;for(var e=!1;b--;)e=e||g(a.kids[b]);return e}var e=null,b=0,a=[],l=null;return{initialize:function(){e=ElmCode.main();e.hasOwnProperty("recv")||(e=Elm.Input(e));l=e.value;for(var b=[],n=a.length;n--;)g(a[n])&&b.push(a[n]);a=b;document.getElementById("content").appendChild(Render.render(l));b=document.getElementById("widthChecker").offsetWidth;b!==window.innerWidth&&Dispatcher.notify(Window.dimensions.id,Value.Tuple(b,window.innerHeight));
e=Elm.Lift(function(a){var b=document.getElementById("content");Render.update(b.firstChild,l,a);return l=a},[e])},notify:function(e,g){b+=1;for(var h=!1,j=a.length;j--;)h=a[j].recv(b,e,g)||h;return h},inputs:a}}(),Signal=function(){function g(a){var b=Value.getSize(a);return["Element",Guid.guid(),["EHtml",a],b[0],b[1],1,Nothing,Nothing]}function e(a){for(var b=["Nil"],c=a.length;c--;)b=["Cons",a[c],b];return b}var b;b=document.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:function(a,
b,c){a.attachEvent("on"+b,c)};var a,l=function(a){var b=0,c=0;a||(a=window.event);if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return Value.Tuple(b,c)},f=Elm.Input(Value.Tuple(0,0));f.defaultNumberOfKids=2;a=Elm.Lift(function(a){return a[1]},[f]);a.defaultNumberOfKids=0;var n=Elm.Lift(function(a){return a[2]},[f]);n.defaultNumberOfKids=
0;var h=Elm.Input(!1),j=Elm.Input(!1),c=Elm.Input(Value.Tuple());b(document,"click",function(a){var b=Dispatcher.notify(j.id,!0),d=Dispatcher.notify(c.id,Value.Tuple());Dispatcher.notify(j.id,!1);!b&&!d&&this.removeEventListener("click",arguments.callee,!1)});b(document,"mousedown",function(a){Dispatcher.notify(h.id,!0)||this.removeEventListener("mousedown",arguments.callee,!1)});b(document,"mouseup",function(a){Dispatcher.notify(h.id,!1)||this.removeEventListener("mouseup",arguments.callee,!1)});
b(document,"mousemove",function(a){Dispatcher.notify(f.id,l(a))||this.removeEventListener("mousemove",arguments.callee,!1)});a={position:f,x:a,y:n,isClicked:j,isDown:h,clicks:c,isClickedOn:function(a){var a=Render.render(a),c=Elm.Input(!1);b(a,"click",function(){Dispatcher.notify(c.id,!0);Dispatcher.notify(c.id,!1)});return Value.Tuple(g(a),c)}};var d=Elm.Input(Value.Tuple(window.innerWidth,window.innerHeight));d.defaultNumberOfKids=2;n=Elm.Lift(function(a){return a[1]},[d]);n.defaultNumberOfKids=
0;var t=Elm.Lift(function(a){return a[2]},[d]);t.defaultNumberOfKids=0;b(window,"resize",function(a){var b=document.getElementById("widthChecker").offsetWidth;Dispatcher.notify(d.id,Value.Tuple(b,window.innerHeight))||this.removeEventListener("resize",arguments.callee,!1)});var n={dimensions:d,width:n,height:t},p=function(a,b){return"Nil"===b[0]?b:b[1]===a?b[2]:["Cons",b[1],p(a,b[2])]},r=Elm.Input(["Nil"]),i=Elm.Input(["Nothing"]);b(document,"keydown",function(a){var b;a:{for(b=r.value;"Nil"!==b[0];){if(b[1]===
a.keyCode){b=!0;break a}b=b[2]}b=!1}b||Dispatcher.notify(r.id,["Cons",a.keyCode,r.value])||this.removeEventListener("keydown",arguments.callee,!1)});b(document,"keyup",function(a){var b=p(a.keyCode,r.value);Dispatcher.notify(r.id,b)||this.removeEventListener("keyup",arguments.callee,!1)});b(window,"blur",function(a){Dispatcher.notify(r.id,["Nil"])||this.removeEventListener("blur",arguments.callee,!1)});b(document,"keypress",function(a){var b=Dispatcher.notify(i.id,["Just",a.charCode||a.keyCode]);
Dispatcher.notify(i.id,["Nothing"]);b||this.removeEventListener("keypress",arguments.callee,!1)});var t={Raw:{keysDown:r,charPressed:i}},m;m=function(a){return function(b){var c=Elm.Input(["Waiting"]),d={};window.XMLHttpRequest?d=new XMLHttpRequest:window.ActiveXObject&&(d=new ActiveXObject("Microsoft.XMLHTTP"));d.onreadystatechange=function(){4===d.readyState&&Dispatcher.notify(c.id,200===d.status?["Success",e(d.responseText)]:["Failure",d.status,e(d.statusText)])};d.open(a,Value.toText(b),!0);d.send(null);
return c}};var v=function(a){return function(b){var c=Elm.Input(["Nothing"]),b=Elm.Lift(function(b){if("Just"!==b[0]){try{Dispatcher.notify(c.id,["Nothing"])}catch(d){}return[]}try{Dispatcher.notify(c.id,["Just",["Waiting"]])}catch(g){c.value=["Just",["Waiting"]]}var f={};window.XMLHttpRequest?f=new XMLHttpRequest:window.ActiveXObject&&(f=new ActiveXObject("Microsoft.XMLHTTP"));f.onreadystatechange=function(){4===f.readyState&&Dispatcher.notify(c.id,["Just",200===f.status?["Success",e(f.responseText)]:
["Failure",f.status,e(f.statusText)]])};f.open(a,Value.toText(b[1]),!0);f.send(null);return[]},[b]);return Elm.Lift(function(a){return function(){return a}},[c,b])}};m={get:m("GET"),post:m("POST"),gets:v("GET"),posts:v("POST")};var s=function(a,c){a.placeholder=Foreign.JavaScript.castStringToJSString(c);var d=Elm.Input(["Nil"]);b(a,"keyup",function(){Dispatcher.notify(d.id,e(a.value));a.focus()});a.style.padding="1px";return Value.Tuple(g(a),d)},q=function(a){a=document.createElement(a);a.style.padding=
"0";a.style.margin="0";return a},u=function(a){for(var c=q("select"),d=[];"Cons"===a[0];){var e=q("option"),f=Text.toText(a[1][1]);e.value=f;e.innerHTML=f;c.appendChild(e);d.push(a[1][2]);a=a[2]}var j=Elm.Input(d[0]);b(c,"change",function(){Dispatcher.notify(j.id,d[c.selectedIndex])});return Value.Tuple(g(c),j)};return{addListener:b,Mouse:a,Keyboard:t,Time:{every:function(a){var a=1E3*a,b=Elm.Input(0),c=0;setInterval(function(){c+=a;Dispatcher.notify(b.id,c/1E3)},a);return b},after:function(a){var a=
1E3*a,b=Elm.Input(!1);setTimeout(function(){Dispatcher.notify(b.id,!0)},a);return b},before:function(a){var a=1E3*a,b=Elm.Input(!0);setTimeout(function(){Dispatcher.notify(b.id,!1)},a);return b}},Window:n,HTTP:m,Random:{inRange:function(a){return function(b){return Elm.Input(Math.floor(Math.random()*(b-a+1))+a)}},randomize:function(a){return function(b){return function(c){return Elm.Lift(function(){return Math.floor(Math.random()*(b-a+1))+a},[c])}}}},Input:{textArea:function(a){return function(b){var c=
q("textarea");c.rows=b;c.cols=a;return s(c,"")}},textField:function(a){var b=q("input");b.type="text";return s(b,a)},password:function(a){var b=q("input");b.type="password";return s(b,a)},checkbox:function(a){var c=q("input");c.type="checkbox";c.checked=a;var d=Elm.Input(a);b(c,"change",function(){Dispatcher.notify(d.id,c.checked)});return Value.Tuple(g(c),d)},dropDown:u,stringDropDown:function(a){return u(List.map(function(a){return Value.Tuple(a,a)})(a))},button:function(a){var c=q("input");c.type=
"button";c.value=Foreign.JavaScript.castStringToJSString(a);var d=Elm.Input(!1);b(c,"click",function(){Dispatcher.notify(d.id,!0);Dispatcher.notify(d.id,!1)});return Value.Tuple(g(c),d)}},constant:function(a){return Elm.Input(a)},lift:function(a){return function(b){return Elm.Lift(a,[b])}},lift2:function(a){return function(b){return function(c){return Elm.Lift(a,[b,c])}}},lift3:function(a){return function(b){return function(c){return function(d){return Elm.Lift(a,[b,c,d])}}}},lift4:function(a){return function(b){return function(c){return function(d){return function(e){return Elm.Lift(a,
[b,c,d,e])}}}}},foldp:function(a){return function(b){return function(c){return Elm.Fold(a,b,c)}}},foldp_:function(a){return function(b){return function(c){return Elm.Fold1(a,b,c)}}},foldp1:function(a){return function(b){return Elm.Fold1(a,function(a){return a},b)}},count:function(a){return Elm.Fold(function(){return function(a){return a+1}},0,a)},keepIf:Elm.keepIf,dropIf:Elm.dropIf,keepWhen:Elm.keepWhen,dropWhen:Elm.dropWhen,dropRepeats:Elm.dropRepeats,sampleOn:Elm.sampleOn}}(),Prelude=function(){var g=
function(e){return function(b){var a=e%b,a=0==e?0:0<b?0<=e?a:a+b:-g(-e)(-b);return a==b?0:a}};return{id:function(e){return e},not:function(e){return!e},fst:function(e){return e[1]},snd:function(e){return e[2]},rem:function(e){return function(b){return e%b}},div:function(e){return function(b){return~~(e/b)}},compare:function(e){return function(b){e="object"===typeof e?toText(e):e;b="object"===typeof b?toText(b):b;return[e===b?"EQ":e<b?"LT":"GT"]}},toFloat:function(e){return e},round:function(e){return Math.round(e)},
floor:function(e){return Math.floor(e)},ceiling:function(e){return Math.ceil(e)},truncate:function(e){return~~e},sqrt:Math.sqrt,abs:Math.abs,pi:Math.PI,e:Math.E,sin:Math.sin,cos:Math.cos,tan:Math.tan,asin:Math.asin,acos:Math.acos,atan:Math.atan,mod:g,min:function(e){return function(b){return Math.min(e,b)}},max:function(e){return function(b){return Math.max(e,b)}},flip:function(e){return function(b){return function(a){return e(a)(b)}}},clamp:function(e){return function(b){return function(a){return Math.min(b,
Math.max(e,a))}}},curry:function(e){return function(b){return function(a){return e(["Tuple2",b,a])}}},uncurry:function(e){return function(b){if("Tuple2"!==b[0])throw"Function was uncurry'd but was not given a pair.";return e(b[1])(b[2])}},logBase:function(e){return function(b){return Math.log(b)/Math.log(e)}},Just:Data.Maybe.Just,Nothing:Data.Maybe.Nothing,maybe:Data.Maybe.maybe,map:Data.List.map,filter:Data.List.filter,head:Data.List.head,tail:Data.List.tail,last:Data.List.last,length:Data.List.length,
reverse:Data.List.reverse,foldr:Data.List.foldr,foldr1:Data.List.foldr1,foldl:Data.List.foldl,foldl1:Data.List.foldl1,and:Data.List.and,or:Data.List.or,forall:Data.List.forall,exists:Data.List.exists,sum:Data.List.sum,product:Data.List.product,concat:Data.List.concat,concatMap:Data.List.concatMap,maximum:Data.List.maximum,minimum:Data.List.minimum,scanl:Data.List.scanl,scanl1:Data.List.scanl1,take:Data.List.take,drop:Data.List.drop,lift:Signal.lift,lift2:Signal.lift2,lift3:Signal.lift3,lift4:Signal.lift4,
foldp:Signal.foldp,foldp1:Signal.foldp1,foldp_:Signal.foldp_,constant:Signal.constant,count:Signal.count,keepIf:Signal.keepIf,dropIf:Signal.dropIf,keepWhen:Signal.keepWhen,dropWhen:Signal.dropWhen,dropRepeats:Signal.dropRepeats,sampleOn:Signal.sampleOn}}(),eq=Value.eq;Signal.addListener(document,"elm_log",function(g){console.log(g.value)});Signal.addListener(document,"elm_title",function(g){document.title=g.value});
Signal.addListener(document,"elm_redirect",function(g){0<g.value.length&&(window.location=g.value)});var includeGlobal=this;
(function(){var g=function(b){for(var a in b)if("Internal"!==a)try{includeGlobal[a]=b[a]}catch(e){"length"===a&&(includeGlobal.execScript("var length;"),length=b[a])}},e=function(b){return function(a){includeGlobal[b]=includeGlobal[b]||{};for(var e in a)"Internal"!==e&&(includeGlobal[b][e]=a[e])}};g(Element);g(Text);color=Element.color;height=Element.height;show=Value.show;g(ElmCode.Graphics.Color);g(ElmCode.Graphics.Element);e("Time")(Signal.Time);e("Mouse")(Signal.Mouse);e("Keyboard")(Signal.Keyboard);
e("Window")(Signal.Window);e("HTTP")(Signal.HTTP);e("Input")(Signal.Input);e("Random")(Signal.Random)})();ElmCode=ElmCode||{};ElmCode.Data=Data;ElmCode.Signal=Signal;ElmCode.Data.List=List;ElmCode.Foreign=Foreign;ElmCode.Prelude=Prelude;ElmCode.Graphics.Text=Text;
try{ElmCode.Website=ElmCode.Website||{};if(ElmCode.Website.Docs)throw"Module name collision, 'Website.Docs' is already defined.";ElmCode.Website.Docs=function(){function g(a){return function(b){return bold(Text.height(a)(toText(b)))}}try{ElmCode.Prelude instanceof Object}catch(e){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var b=[],a;for(a in ElmCode.Prelude)0<=b.indexOf(a)||(this[a]=ElmCode.Prelude[a]);try{ElmCode.Data.List instanceof
Object}catch(l){throw"Module 'Data.List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var f=ElmCode.Data.List.intersperse,n=rgb(245)(245)(245),h=rgb(216)(221)(225);return{createDocs:function(a){return function(b){return lift(function(d){var e,l=d-80,r=flow(down),i=text(Text.link(Value.str("/Documentation.elm"))(toText("Back")));e=g(2)(a);e=width(l)(centeredText(e));var m=spacer(1)(30),v=f(spacer(1)(50));e=r(["Cons",i,["Cons",e,["Cons",m,v(map(function(a){a:{switch(a[0]){case "Tuple2":var b=
a[1],a=a[2],c=flow(down),b=text(g(1.25)(b)),d=spacer(1)(20),a=c(["Cons",b,["Cons",d,map(function(a){a:{switch(a[0]){case "Tuple3":var b=a[1],c=a[2],a=a[3],d="GT"===compare(length(c))(0)[0]?Value.append(Value.str(" :: "),c):Value.str(""),c=flow(down),e=color(h)(spacer(l)(1)),b=Value.append(bold(toText(b)),toText(d)),b=width(l)(color(n)(text(monospace(b)))),a=c(["Cons",e,["Cons",b,["Cons",spacer(1)(10),["Cons",flow(right)(["Cons",spacer(50)(10),["Cons",width(l-50)(plainText(a)),["Nil"]]]),["Cons",spacer(1)(20),
["Nil"]]]]]]);break a}throw"Non-exhaustive pattern match in case";}return a})(a)]]);break a}throw"Non-exhaustive pattern match in case";}return a})(b))]]]);r=flow(down);i=spacer(d)(15);e=container(d)(heightOf(e))(midTop)(e);m=toText("&copy; 2011-2012 Evan Czaplicki");d=container(d)(50)(midBottom)(text(Text.color(h)(m)));return r(["Cons",i,["Cons",e,["Cons",d,["Nil"]]]])})(Window.width)}}}}();ElmCode.main=function(){return ElmCode.Website.Docs.main}}catch(e$$66){ElmCode.main=function(){document.body.innerHTML=
Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Docs module:<br/>'+e$$66+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, Text.link, Window.width, container, heightOf, midBottom, midTop, spacer</span>");throw e$$66;}}
try{ElmCode.Website=ElmCode.Website||{};if(ElmCode.Website.Tiles)throw"Module name collision, 'Website.Tiles' is already defined.";ElmCode.Website.Tiles=function(){function g(a){return function(b){a:{switch(b[0]){case "Cons":b=["Cons",f(a)(b),g(a)(n(a)(b))];break a;case "Nil":b=["Nil"];break a}throw"Non-exhaustive pattern match in case";}return b}}try{ElmCode.Prelude instanceof Object}catch(e){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";
}var b=[],a;for(a in ElmCode.Prelude)0<=b.indexOf(a)||(this[a]=ElmCode.Prelude[a]);try{ElmCode.Data.List instanceof Object}catch(l){throw"Module 'Data.List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var f=ElmCode.Data.List.take,n=ElmCode.Data.List.drop,h=ElmCode.Data.List.intersperse;return{toTile:function(a){var b;a:{switch(a[0]){case "Tuple3":var d=a[2],a=["Tuple3",a[1],Value.append(a[3],Value.append(d,Value.str(".elm"))),Value.append(Value.str("/screenshot/"),
Value.append(d,Value.str(".jpg")))];break a}throw"Non-exhaustive pattern match in case";}b=a;a:{switch(b[0]){case "Tuple3":a=b[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(b[0]){case "Tuple3":d=b[2];break a}throw"Non-exhaustive pattern match in case";}var e;a:{switch(b[0]){case "Tuple3":e=b[3];break a}throw"Non-exhaustive pattern match in case";}d=link(Value.append(Value.str("/edit/examples/"),d));b=flow(down);e=container(130)(130)(middle)(image(120)(120)(e));a=toText(a);a=width(130)(centeredText(a));
return d(b(["Cons",e,["Cons",a,["Nil"]]]))},tile:function(a){return function(b){b=g(div(a)(130))(b);return flow(down)(h(spacer(1)(14))(map(flow(right))(b)))}}}}();ElmCode.main=function(){return ElmCode.Website.Tiles.main}}catch(e$$69){ElmCode.main=function(){document.body.innerHTML=Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Tiles module:<br/>'+e$$69+"<br/><br/>The problem may stem from an improper usage of:<br/>container, link, middle, spacer</span>");
throw e$$69;}}
try{ElmCode.Website=ElmCode.Website||{};if(ElmCode.Website.Skeleton)throw"Module name collision, 'Website.Skeleton' is already defined.";ElmCode.Website.Skeleton=function(){try{ElmCode.Prelude instanceof Object}catch(g){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var e=[],b;for(b in ElmCode.Prelude)0<=e.indexOf(b)||(this[b]=ElmCode.Prelude[b]);var a,e=["Cons",["Tuple2",Value.str("Home"),Value.str("/")],["Cons",["Tuple2",Value.str("Examples"),
Value.str("/Examples.elm")],["Cons",["Tuple2",Value.str("Docs"),Value.str("/Documentation.elm")],["Cons",["Tuple2",Value.str("Download"),Value.str("/Download.elm")],["Nil"]]]]];a=flow(right)(map(function(a){var b;a:{switch(a[0]){case "Tuple2":b=a[2];a=plainText(a[1]);b=link(b)(container(100)(60)(middle)(a));break a}throw"Non-exhaustive pattern match in case";}return b})(e));var l=rgb(245)(245)(245),f=rgb(216)(221)(225);return{skeleton:function(b){return function(e){var g="LT"===compare(e)(820)[0]?
e-20:800,c=b(g),d=flow(down),t=beside,p;p=g-widthOf(a);var r=toText("Elm");p=container(p)(60)(midLeft)(text(Text.height(2)(bold(r))));t=t(p)(a);g=color(f)(container(e)(61)(midTop)(color(l)(container(e)(60)(middle)(container(g)(60)(middle)(t)))));t=spacer(e)(10);c=container(e)(heightOf(c))(middle)(c);p=toText("&copy; 2011-2012 Evan Czaplicki");e=container(e)(50)(midBottom)(text(Text.color(f)(p)));return d(["Cons",g,["Cons",t,["Cons",c,["Cons",e,["Nil"]]]]])}}}}();ElmCode.main=function(){return ElmCode.Website.Skeleton.main}}catch(e$$71){ElmCode.main=
function(){document.body.innerHTML=Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Skeleton module:<br/>'+e$$71+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, beside, container, heightOf, link, midBottom, midLeft, midTop, middle, spacer, widthOf</span>");throw e$$71;}};