Elm={};var Guid=function(){var f=0;return{guid:function(){return f+=1}}}();
Elm.JavaScript=function(){function f(a){for(var b=["Nil"],m=a.length;m--;)b=["Cons",a[m],b];return b}function j(a){for(var b=[];"Cons"===a[0];)b.push(a[1]),a=a[2];return b}function a(a){return a.slice(1)}function e(a){return["Tuple"+a.length].concat(a)}return{castJSBoolToBool:function(a){return a},castBoolToJSBool:function(a){return a},castJSNumberToFloat:function(a){return a},castFloatToJSNumber:function(a){return a},castJSNumberToInt:function(a){return~~a},castIntToJSNumber:function(a){return a},
Experimental:{castJSElementToElement:function(a){return function(b){return function(m){return["Element",Guid.guid(),["EExternalHtml",m],a,b,1,["Nothing"],["Nothing"]]}}},castElementToJSElement:function(a){return Render.render(a)}},castJSArrayToList:f,castListToJSArray:j,castJSStringToString:f,castStringToJSString:function(a){return"string"===typeof a?a:j(a).join("")},castTupleToJSTuple2:a,castTupleToJSTuple3:a,castTupleToJSTuple4:a,castTupleToJSTuple5:a,castJSTupleToTuple2:e,castJSTupleToTuple3:e,
castJSTupleToTuple4:e,castJSTupleToTuple5:e}}();var JSjson=window.JSON;
Elm.JSON=function(){function f(b,a){return function(g){return function(k){var c=e.castStringToJSString(g);return k[1].hasOwnProperty(c)&&(k=k[1][c],k[0]===b)?k[1]:a}}}function j(b){return function(a){function g(b){switch(b[0]){case "JsonNull":return null;case "JsonString":return e.castStringToJSString(b[1]);case "JsonObject":var c={};b=b[1][1];for(var d in b)c[d]=g(b[d]);return c;case "JsonArray":c=e.castListToJSArray(b[1]);for(d=c.length;d--;)c[d]=g(c[d]);return c;default:return b[1]}}return JSjson.stringify(g(["JsonObject",
a]),null,e.castStringToJSString(b))}}function a(b){function a(b){switch(typeof b){case "string":return["JsonString",e.castJSStringToString(b)];case "number":return["JsonNumber",e.castJSNumberToFloat(b)];case "boolean":return["JsonBool",e.castJSBoolToBool(b)];case "object":if(null===b)return["JsonNull"];for(var c in b)b[c]=a(b[c]);return b instanceof Array?["JsonArray",e.castJSArrayToList(b)]:["JsonObject",["JSON",b]]}}b=JSjson.parse(b);for(var g in b)b[g]=a(b[g]);return["JSON",b]}var e=Elm.JavaScript,
h=["JSON",{}];return{empty:h,singleton:function(b){return function(a){var g={};g[e.castStringToJSString(b)]=a;return["JSON",g]}},insert:function(b){return function(a){return function(g){g=g[1];var k={},c;for(c in g)k[c]=g[c];k[e.castStringToJSString(b)]=a;return["JSON",k]}}},lookup:function(b){return function(a){var g=e.castStringToJSString(b);return a[1].hasOwnProperty(g)?["Just",a[1][g]]:["Nothing"]}},findString:f("JsonString",["Nil"]),findObject:f("JsonObject",h),findArray:f("JsonArray",["Nil"]),
findWithDefault:function(b){return function(a){return function(g){var k=e.castStringToJSString(a);return g[1].hasOwnProperty(k)?g[1][k]:b}}},remove:function(b){return function(a){a=a[1];var g={},k;for(k in a)g[k]=a[k];delete g[e.castStringToJSString(b)];return["JSON",g]}},toPrettyJSString:j,toJSString:j(""),fromJSString:a,toPrettyString:function(b){return function(a){return e.castJSStringToString(j(b)(a))}},toString:function(b){return e.castJSStringToString(j("")(b))},fromString:function(b){return a(e.castStringToJSString(b))},
toList:function(b){b=b[1];var a=[],g;for(g in b)a.push(Value.Tuple(e.castJSStringToString(g),b[g]));return e.castJSArrayToList(a)},fromList:function(b){b=e.castListToJSArray(b);for(var a={},g=b.length;g--;)a[e.castStringToJSString(b[g][1])]=b[g][2];return["JSON",a]},JsonString:function(b){return["JsonString",b]},JsonNumber:function(b){return["JsonNumber",b]},JsonBool:function(b){return["JsonBool",b]},JsonNull:["JsonNull"],JsonArray:function(b){return["JsonArray",b]},JsonObject:function(b){return["JsonObject",
b]}}}();
var Value=function(){function f(b){if(0==b.length)return b;b=b.replace(/"/g,"&#34;").replace(/'/g,"&#39;").replace(/</g,"&#60;").replace(/>/g,"&#62;").replace(/\n/g,"<br/>");b=b.split("<br/>");for(var a=b.length;a--;){var g=b,k=a,c;c=b[a];if(0!=c.length){c=c.split("");" "==c[0]&&(c[0]="&nbsp;");for(var d=c.length;--d;)" "==c[d][0]&&" "==c[d-1]&&(c[d-1]+=c[d],c[d]="");for(d=c.length;d--;)if(1<c[d].length&&" "==c[d][0]){for(var l=c[d].split(""),e=l.length-2;0<=e;e-=2)l[e]="&nbsp;";c[d]=l.join("")}c=c.join("");
c=" "===c[c.length-1]?c.slice(0,-1)+"&nbsp;":c}g[k]=c}return b.join("<br/>")}var j=function(b,a){if("object"===typeof b){if(b.hasOwnProperty("_")){for(var g in b)if(b[g]!=a[g])return!1;for(g in a)if(b[g]!=a[g])return!1;return!0}if(b===a)return!0;if(b.length!==a.length)return!1;for(g=b.length;g--;)if(!j(b[g],a[g]))return!1;return!0}return b===a},a=function(b){if("function"===typeof b)return"<function>";if("boolean"===typeof b)return b?"True":"False";if("number"!==typeof b){if("string"===typeof b&&
2>b.length)return"'"+b+"'";if("object"===typeof b&&b.hasOwnProperty("_")){var e=[],g;for(g in b)if("_"!=g)for(var k=b[g].length;k--;)e.push(g+" = "+a(b[g][k]));return 0===e.length?"{}":"{ "+e.join(", ")+" }"}if(b[0]){if("Tuple"===b[0].substring(0,5)){e=Array(b.length-1);for(k=b.length;--k;)e[k-1]=a(b[k]);return"("+e.join(",")+")"}if("Cons"===b[0]){g="string"===typeof b[1]?'"':"]";var k="string"===typeof b[1]?"":",",c="string"===typeof b[1]?function(c){return c}:a,e=("string"===typeof b[1]?'"':"[")+
c(b[1]);for(b=b[2];;)if("Cons"===b[0])e+=k+c(b[1]),b=b[2];else return e+g}else{if("Nil"===b[0])return"[]";if("JSON"===b[0])return"(JSON.fromList "+a(Elm.JSON.toList(b))+")";if("RBNode"===b[0]||"RBEmpty"===b[0])return b=Elm.Dict.foldr(function(c){return function(b){return function(a){return["Cons",["Tuple2",c,b],a]}}})(["Nil"])(b),e="Dict","Cons"===b[0]&&"Tuple0"===b[1][2][0]&&(e="Set",b=Elm.List.map(function(c){return c[1]})(b)),"("+e+".fromList "+a(b)+")";e=[];for(k=b.length;--k;)e.push(a(b[k]));
e=b[0]+" "+e.join(" ");return 1<b.length?"("+e+")":e}}}return b+""},e=function(b){for(var a=["Nil"],e=b.length;e--;)a=["Cons",b[e],a];return a},h;h=document.addEventListener?function(b,a,e){b.addEventListener(a,e,!1)}:function(b,a,e){b.attachEvent("on"+a,e)};return{eq:j,str:e,show:function(b){return e(a(b))},Tuple:function(){var b=arguments.length,a=Array(b+1);for(a[0]="Tuple"+arguments.length;b--;)a[b+1]=arguments[b];return a},append:function(b,a){if("string"===typeof b&&"string"===typeof a)return b.concat(a);
if("Nil"===b[0])return a;var e=["Cons",b[1],["Nil"]],k=e;for(b=b[2];"Cons"===b[0];)k[2]=["Cons",b[1],["Nil"]],b=b[2],k=k[2];k[2]=a;return e},listToArray:function(a){for(var e=[];"Cons"===a[0];)e.push(a[1]),a=a[2];return e},toText:function(a){if("string"===typeof a)return f(a);for(var e=[];"Cons"===a[0];)e.push(a[1]),a=a[2];return f(e.join(""))},properEscape:f,getTextSize:function(a,e,g){var k=document.createElement("div");k.innerHTML=g;k.style.textAlign="left";0<a&&(k.style.width=a+"px");k.style.visibility=
"hidden";k.style.styleFloat="left";k.style.cssFloat="left";document.body.appendChild(k);g=window.getComputedStyle(k,null);a=g.getPropertyValue("width").slice(0,-2)-0;g=g.getPropertyValue("height").slice(0,-2)-0;document.body.removeChild(k);return[Math.ceil(a),Math.ceil(Math.max(e,g))]},getSize:function(a){a=a.cloneNode(!0);a.style.visibility="hidden";a.style.styleFloat="left";a.style.cssFloat="left";document.body.appendChild(a);var e=a.offsetWidth,g=a.offsetHeight;document.body.removeChild(a);return[e,
g]},getExcess:function(a){a=a.cloneNode(!0);a.style.visibility="hidden";a.style.styleFloat="left";a.style.cssFloat="left";document.body.appendChild(a);var e=a.offsetWidth,g=a.offsetHeight,k=window.getComputedStyle(a,null),c=k.getPropertyValue("width").slice(0,-2)-0,k=k.getPropertyValue("height").slice(0,-2)-0;document.body.removeChild(a);return[e-c,g-k]},groupForms:function(a){a=Elm.JavaScript.castListToJSArray(a);for(var e=[],g=[],k=a.length;k--;){var c=a[k];switch(c[4][0]){case "FElement":0<g.length&&
(e.push(g),g=[]);e.push(c);break;default:g.push(c)}}0<g.length&&e.push(g);return e},wrap:function(a){var e=Value.getSize(a);return["Element",Guid.guid(),["EHtml",a],e[0],e[1],1,["Nothing"],["Nothing"]]},addListener:h}}();
Elm.List=function(){function f(a){return function(d){if("Nil"===d[0])return d;"Cons"!==d[0]&&c("map");var b=["Cons",a(d[1]),["Nil"]],l=b;for(d=d[2];"Cons"===d[0];)l[2]=["Cons",a(d[1]),["Nil"]],d=d[2],l=l[2];return b}}function j(a){return function(d){return function(b){var l=d;if("Nil"===b[0])return l;for("Cons"!==b[0]&&c("foldl");"Cons"===b[0];)l=a(b[1])(l),b=b[2];return l}}}function a(a){return function(d){return function(b){var l=d;if("Nil"===b[0])return l;"Cons"!==b[0]&&c("foldr");for(var e=[];"Cons"===
b[0];)e.push(b[1]),b=b[2];for(b=e.length;b--;)l=a(e[b])(l);return l}}}function e(a){return function(c){var d;"Cons"!==c[0]?d=void 0:(d=c[1],c=c[2],d=j(a)(d)(c));return d}}function h(a){return function(d){return function(b){if("Nil"===b[0])return["Cons",d,["Nil"]];"Cons"!==b[0]&&c("scanl");for(var l=[d];"Cons"===b[0];)d=a(b[1])(d),l.push(d),b=b[2];b=["Nil"];for(var e=l.length;e--;)b=["Cons",l[e],b];return b}}}function b(a){return function(c){a:{for(var d=[function(a){return"Nil"!==a[0]?void 0:["Tuple2",
["Nil"],["Nil"]]},function(c){if("Cons"===c[0]){var d=c[1];c=c[2];var l=b(a)(c);"Tuple2"!==l[0]?d=void 0:(c=l[1],l=l[2],d=a(d)?["Tuple2",["Cons",d,c],l]:["Tuple2",c,["Cons",d,l]]);return d}}],l=d.length;l--;){var e=d[l](c);if(void 0!==e){c=e;break a}}c=void 0}return c}}function m(a){a:{for(var c=[function(a){return"Nil"!==a[0]?void 0:["Tuple2",["Nil"],["Nil"]]},function(a){if("Cons"!==a[0])a=void 0;else if(a=["Tuple2",a[1],m(a[2])],"Tuple2"!==a[0]||"Tuple2"!==a[1][0])a=void 0;else{var c=a[1][1],d=
a[1][2];a="Tuple2"!==a[2][0]?void 0:["Tuple2",["Cons",c,a[2][1]],["Cons",d,a[2][2]]]}return a}],d=c.length;d--;){var b=c[d](a);if(void 0!==b){a=b;break a}}a=void 0}return a}function g(a){return function(c){a:{for(var d=[function(a){return"Nil"!==a[0]?void 0:["Nil"]},function(a){if("Cons"===a[0]){var c=a[1];return"Nil"!==a[2][0]?void 0:["Cons",c,["Nil"]]}},function(c){if("Cons"===c[0]){var d=c[1];if("Cons"===c[2][0]){var b=c[2][1];c=c[2][2];return["Cons",d,["Cons",a,g(a)(["Cons",b,c])]]}}}],b=d.length;b--;){var l=
d[b](c);if(void 0!==l){c=l;break a}}c=void 0}return c}}function k(a){return function(c){a:{for(var d=[function(a){return"Nil"!==a[0]?void 0:["Nil"]},function(a){if("Cons"===a[0]){var c=a[1];return"Nil"!==a[2][0]?void 0:c}},function(c){if("Cons"===c[0]){var d=c[1];if("Cons"===c[2][0]){var b=c[2][1];c=c[2][2];return Value.append(d,Value.append(a,k(a)(["Cons",b,c])))}}}],b=d.length;b--;){var l=d[b](c);if(void 0!==l){c=l;break a}}c=void 0}return c}}var c=function(a){throw"Function '"+a+"' expecting a list!";
},d=j(function(a){return function(c){return["Cons",a,c]}})(["Nil"]),l=a(function(a){return function(c){return Value.append(a,c)}})(["Nil"]),y=j(function(a){return function(c){return a&&c}})(!0),n=j(function(a){return function(c){return a||c}})(!1),p=j(function(a){return function(c){return a+c}})(0),r=j(function(a){return function(c){return a*c}})(1),x=e(function(a){return function(c){return Math.max(a,c)}}),s=e(function(a){return function(c){return Math.min(a,c)}});return{head:function(a){if("Cons"!==
a[0])throw"Error: 'head' only accepts lists of length greater than one.";return a[1]},tail:function(a){if("Cons"!==a[0])throw"Error: 'tail' only accepts lists of length greater than one.";return a[2]},last:function(a){if("Cons"!==a[0])throw"Error: 'last' only accepts lists of length greater than one.";for(var c=a[1];"Cons"===a[0];)c=a[1],a=a[2];return c},map:f,foldl:j,foldr:a,foldl1:e,foldr1:function(a){return function(d){if("Nil"===d[0])throw"'foldr1' requires an non-empty list.";"Cons"!==d[0]&&
c("foldr1");for(var b=[];"Cons"===d[0];)b.push(d[1]),d=d[2];d=b.pop();for(var l=b.length;l--;)d=a(b[l])(d);return d}},scanl:h,scanl1:function(a){return function(c){if("Cons"!==c[0])throw"Error: 'scanl1' requires a list of at least length 1.";return h(a)(c[1])(c[2])}},filter:function(a){return function(d){if("Nil"===d[0])return d;"Cons"!==d[0]&&c("filter");for(var b=[];"Cons"===d[0];)a(d[1])&&b.push(d[1]),d=d[2];d=["Nil"];for(var l=b.length;l--;)d=["Cons",b[l],d];return d}},length:function(a){for(var c=
0;"Cons"===a[0];)c+=1,a=a[2];return c},reverse:d,concat:l,concatMap:function(a){return function(c){return l(f(a)(c))}},and:y,or:n,all:function(a){return j(function(c){return function(d){return d&&a(c)}})(!0)},any:function(a){return j(function(c){return function(d){return d||a(c)}})(!1)},sum:p,product:r,maximum:x,minimum:s,partition:b,zipWith:function(a){return function(d){return function(b){if("Nil"===d[0]||"Nil"===b[0])return["Nil"];("Cons"!==d[0]||"Cons"!==b[0])&&c("zipWith");for(var l=[];"Cons"===
d[0]&&"Cons"===b[0];)l.push(a(d[1])(b[1])),d=d[2],b=b[2];b=["Nil"];for(var e=l.length;e--;)b=["Cons",l[e],b];return b}}},zip:function(a){return function(d){if("Nil"===a[0]||"Nil"===d[0])return["Nil"];("Cons"!==a[0]||"Cons"!==d[0])&&c("zip");for(var b=[];"Cons"===a[0]&&"Cons"===d[0];)b.push(["Tuple2",a[1],d[1]]),a=a[2],d=d[2];d=["Nil"];for(var l=b.length;l--;)d=["Cons",b[l],d];return d}},unzip:m,intersperse:g,intercalate:k,sort:function(a){if("Nil"===a[0])return a;"Cons"!==a[0]&&c("sort");for(var d=
[];"Cons"===a[0];)d.push(a[1]),a=a[2];d.sort(function(a,c){return a-c});a=["Nil"];for(var b=d.length;b--;)a=["Cons",d[b],a];return a},take:function(a){return function(d){if(0>=a)return["Nil"];if("Nil"===d[0])return d;"Cons"!==d[0]&&c("take");var b=["Cons",d[1],["Nil"]],l=b;d=d[2];for(--a;"Cons"===d[0]&&0<a;)l[2]=["Cons",d[1],["Nil"]],l=l[2],d=d[2],--a;return b}},drop:function(a){return function(d){if("Nil"===d[0])return d;for("Cons"!==d[0]&&c("drop");"Cons"===d[0]&&0<a;)d=d[2],--a;return d}}}}();
Elm.Maybe=function(){function f(a){return function(e){return"Just"===a[0]?["Cons",a[1],e]:e}}function j(a){return function(e){return function(f){var b=a(e);return"Just"===b[0]?["Cons",b[1],f]:f}}}return{Just:function(a){return["Just",a]},Nothing:["Nothing"],catMaybes:Elm.List.foldr(f)(["Nil"]),isJust:function(a){return"Just"===a[0]},isNothing:function(a){return"Nothing"===a[0]},fromMaybe:function(a){return function(e){return"Just"===e[0]?e[1]:a}},consMaybe:f,mapMaybe:function(a){return Elm.List.foldr(j(a))(["Nil"])},
maybe:function(a){return function(e){return function(f){return"Just"===f[0]?e(f[1]):a}}}}}();
Elm.Char=function(){function f(a,b){return function(e){e=e.charCodeAt(0);return a<=e&&e<=b}}var j=f(48,57),a=f(97,102),e=f(65,70);return{fromCode:function(a){return String.fromCharCode(a)},toCode:function(a){return a.charCodeAt(0)},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},toLocaleUpper:function(a){return a.toLocaleUpperCase()},toLocaleLower:function(a){return a.toLocaleLowerCase()},isLower:f(97,122),isUpper:f(65,90),isDigit:j,isOctDigit:f(48,55),isHexDigit:function(f){return j(f)||
a(f)||e(f)}}}();
Elm.Color=function(){function f(f){var a=f.value*f.saturation,e=f.hue/60,h=a*(1-Math.abs(e%2-1)),b=0,m=0,g=0;0<=e&&1>e?(b=a,m=h,g=0):1<=e&&2>e?(b=h,m=a,g=0):2<=e&&3>e?(b=0,m=a,g=h):3<=e&&4>e?(b=0,m=h,g=a):4<=e&&5>e?(b=h,m=0,g=a):5<=e&&6>e&&(b=a,m=0,g=h);f=f.value-a;return["Color",Math.round(255*(b+f)),Math.round(255*(m+f)),Math.round(255*(g+f)),1]}return{rgba:function(f){return function(a){return function(e){return function(h){return["Color",f,a,e,h]}}}},rgb:function(f){return function(a){return function(e){return["Color",f,
a,e,1]}}},hsva:function(j){return function(a){return function(e){return function(h){var b=f({hue:j,saturation:a,value:e});b[4]=h;return b}}}},hsv:function(j){return function(a){return function(e){return f({hue:j,saturation:a,value:e})}}},red:["Color",255,0,0,1],green:["Color",0,255,0,1],blue:["Color",0,0,255,1],yellow:["Color",255,255,0,1],cyan:["Color",0,255,255,1],magenta:["Color",255,0,255,1],black:["Color",0,0,0,1],white:["Color",255,255,255,1],gray:["Color",128,128,128,1],grey:["Color",128,128,
128,1],complement:function(j){var a;a=j[1]/255;var e=j[2]/255;j=j[3]/255;var h=Math.max(a,e,j),b=Math.min(a,e,j),b=h-b,m=0;0===b?m=0:h===a?m=(e-j)/b%6:h===e?m=(j-a)/b+2:h===j&&(m=(a-e)/b+4);a={value:h,hue:60*m,saturation:0===h?0:b/h};a.hue=(a.hue+180)%360;return f(a)},extract:function(f){return 1===f[4]?"rgb("+f[1]+","+f[2]+","+f[3]+")":"rgba("+f[1]+","+f[2]+","+f[3]+","+f[4]+")"}}}();
var Collage=function(){function f(a,c){var d=c.length-1;if(!(0>=d))for(a.moveTo(c[d][1],c[d][2]);d--;)a.lineTo(c[d][1],c[d][2])}function j(a,c,d,b){0===a.length&&(a=[8,4]);var e=b.length-1;if(!(0>=e)){var n=b[e][1],g=b[e][2],f=0,h=0,j=0,m=0,q=0,t=0,v=a.length,A=!0,w=a[0];for(c.moveTo(n,g);e--;){f=b[e][1];h=b[e][2];j=f-n;m=h-g;for(q=Math.sqrt(j*j+m*m);w<=q;)n+=j*w/q,g+=m*w/q,c[A?"lineTo":"moveTo"](n,g),j=f-n,m=h-g,q=Math.sqrt(j*j+m*m),A=!A,t=(t+1)%v,w=a[t];0<q&&(c[A?"lineTo":"moveTo"](f,h),w-=q);n=
f;g=h}}c.strokeStyle=Elm.Color.extract(d);c.stroke()}function a(a,c,d,b,e){c.clearRect(0,0,d,b);for(d=e.length;d--;){var n=e[d],p=a;b=c;var h=n[1],m=n[2],s=n[3][1],u=n[3][2],n=n[4];b.save();(0!==s||0!==u)&&b.translate(s,u);h!==~~h&&b.rotate(2*Math.PI*h);1!==m&&b.scale(m,m);b.beginPath();switch(n[0]){case "FLine":a:switch(p=b,h=n,n=h[3][1],h[1][0]){case "Solid":h=h[2];f(p,n);p.strokeStyle=Elm.Color.extract(h);p.stroke();break;case "Dotted":j([3,3],p,h[2],n);break a;case "Dashed":j([8,4],p,h[2],n);
break a;case "Custom":j(h[1][1],p,h[2],n)}break;case "FShape":a:switch(s=p,m=b,p=n[1],h=n[2],n=n[3][1],p[0]){case "Filled":p=m;f(p,n);p.fillStyle=Elm.Color.extract(h);p.fill();break a;case "Outlined":p=m;f(p,n);p.strokeStyle=Elm.Color.extract(h);p.stroke();break a;case "Textured":h=s;p=p[1];s=new Image;s.src=g.castStringToJSString(p);s.onload=h;f(m,n);m.fillStyle=m.createPattern(s,"repeat");m.fill();break a;case "CustomOutline":j(p[1],m,h,n)}break;case "FImage":h=b,m=n[1],s=n[2],n=n[3],u=new Image,
u.onload=p,u.src=g.castStringToJSString(n),h.drawImage(u,-m/2,-s/2,m,s)}b.restore()}}function e(b,c,d){var l=Render.newElement("canvas");b=~~b;c=~~c;l.style.width=b+"px";l.style.height=c+"px";l.style.display="block";l.width=b;l.height=c;if(l.getContext){var e=l.getContext("2d");a(function(){a(this,e,b,c,d)},e,b,c,d);return l}l.innerHTML="Your browser does not support the canvas element.";return l}function h(a,c,d,b,e,n,g){var f=Render.render(g);d="translate("+(e-g[3]/2)+"px,"+(n-g[4]/2)+"px) "+(1===
b?"":"scale("+b+","+b+")")+" "+(d===~~d?"":"rotate("+360*d+"deg)");f.style.transform=d;f.style.msTransform=d;f.style.MozTransform=d;f.style.webkitTransform=d;f.style.OTransform=d;d=Render.newElement("div");Render.addTo(d,f);d.style.width=~~a+"px";d.style.height=~~c+"px";d.style.overflow="hidden";return d}function b(b,c,d){if(!Value.eq(d,c)){var l=b.style.width.slice(0,-2)-0,g=b.style.height.slice(0,-2)-0;if("object"===typeof d[0]){if("object"===typeof c[0]&&b.getContext){var n=b.getContext("2d");
return a(function(){a(this,n,l,g,d)},n,l,g,d)}c=e(l,g,d);c.style.position="absolute";return b.parentNode.replaceChild(c,b)}c=h(l,g,d[1],d[2],d[3][1],d[3][2],d[4][1]);c.style.position="absolute";return b.parentNode.replaceChild(c,b)}}function m(a,c,d,b,e){var n=0,g,f=(a[1]-b[1])/d;a=(a[2]-b[2])/d;0!==c&&(c*=-2*Math.PI,d=f*Math.cos(c)-a*Math.sin(c),a=f*Math.sin(c)+a*Math.cos(c),f=d);if(0===e.length)return!1;g=e[0];for(d=e.length-1;d--;){c=e[d];b=g[1];g=g[2];var h=c[1],j=c[2];if(g<j)var m=g,q=j;else m=
j,q=g;if(b<h)var t=b,v=h;else t=h,v=b;m<a&&a<=q&&f<=v&&(f<=t||f<=(a-g)*(h-b)/(j-g)+b)&&++n;g=c}return 1===n%2}var g=Elm.JavaScript;return{collage:function(a,c,d){if(0===d.length)return e(a,c,[]);for(var b=Array(d.length),g=d.length;g--;){var n=d[g];b[g]="string"===typeof n[0]?h(a,c,n[1],n[2],n[3][1],n[3][2],n[4][1]):e(a,c,n)}return 1===d.length?b[0]:Render.flowWith(Render.goIn,function(a){return a},b)},updateCollage:function(a,c,d){if(1===d.length)return b(a,c[0],d[0]);a=a.childNodes;for(var e=a.length,
g=e;g--;)b(a[e-g-1],c[g],d[g])},insideForm:function(a){return function(c){var d=a[1],b=a[2];if(6>c.length){var e=c[3][1],g=c[3][2],f=0,h=c[2];switch(c[4][0]){case "FShape":for(var j=c[4][3][1],s=j.length;--s;)var u=j[s],f=Math.max(f,u[1]*u[1]+u[2]*u[2]);f*=h*h;break;case "FImage":j=h*c[4][1]/2;h=h*c[4][2]/2;f=j*j+h*h;break;case "FElement":j=h*c[4][1][3]/2,h=h*c[4][1][4]/2,f=j*j+h*h}c.push(function(a,c){var d=a-e,b=c-g;return d*d+b*b<f+1})}if(!c[5](d,b))return!1;var q,t;switch(c[4][0]){case "FShape":return m(a,
c[1],c[2],c[3],c[4][3][1]);case "FLine":return!1;case "FImage":q=c[4][1]/2;t=c[4][2]/2;break;case "FElement":q=c[4][1][3]/2,t=c[4][1][4]/2}return m(a,c[1],c[2],c[3],[[null,q,t],[null,-q,t],[null,-q,-t],[null,q,-t],[null,q,t]])}}}}();
Elm.Graphics=function(){function f(a){return function(c){return["Position",a,c]}}function j(a){return function(c){return["EText",a,c]}}function a(a){return function(c){return["EFlow",a,r.castListToJSArray(c)]}}function e(a){return["Line",r.castListToJSArray(a)]}function h(a){return function(c){var d=r.castListToJSArray(a);0<d.length&&d.push(d[0]);return["Shape",d,c]}}function b(a){return function(c){return function(d){return function(b){return["Form",a,c,d,b]}}}}function m(a){return function(c){return function(d){return["FLine",
a,c,d]}}}function g(a){return function(c){return function(d){return["FShape",a,c,d]}}}function k(a,c,d,b,e,l){return["Element",Guid.guid(),a,c,d,b,e,l]}function c(a,c,d){return["Element",Guid.guid(),a,c,d,1,["Nothing"],["Nothing"]]}function d(a){return~~a[3]}function l(a){return~~a[4]}function y(a){return function(d){return function(b){return c(["EImage",r.castStringToJSString(b)],a,d)}}}function n(a){return function(d){return c(A,a,d)}}function p(a){return function(c){return function(d){var b=map(function(d){return["Tuple2",
a/2*Math.cos(2*(Math.PI/50)*d),c/2*Math.sin(2*(Math.PI/50)*d)]}),e=49,l=["Nil"];if(0<=e){do l=["Cons",e,l];while(0<e--)}return h(b(l))(d)}}}for(this.i in Elm.List)eval("var "+this.i+" = Elm.List[this.i];");var r=Elm.JavaScript,x=["DRight"],s=["DDown"],u=["DOut"],q=["Near"],t=["Mid"],v=["Far"],A=["EEmpty"],w=["Solid"],D=["Dotted"],F=["Dashed"],B=["Filled"],E=["Outlined"],z=f(q)(q),C=f(v)(q),G=f(q)(v),H=f(v)(v),I=f(q)(t),J=f(v)(t),q=f(t)(q),v=f(t)(v),t=f(t)(t);return{left:["DLeft"],right:x,down:s,up:["DUp"],
inward:["DIn"],outward:u,topLeft:z,topRight:C,bottomLeft:G,bottomRight:H,midLeft:I,midRight:J,midTop:q,midBottom:v,middle:t,middleAt:function(a){return function(c){return["PositionAt",a,c]}},topLeftAt:function(a){return function(c){return["PositionTL",a,c]}},topRightAt:function(a){return function(c){return["PositionTR",a,c]}},bottomLeftAt:function(a){return function(c){return["PositionBL",a,c]}},bottomRightAt:function(a){return function(c){return["PositionBR",a,c]}},absolute:function(a){return["Absolute",
a]},relative:function(a){return["Relative",a]},width:function(a){return function(c){var d=c[2];switch(d[0]){case "EImage":case "EVideo":return k(c[2],a,c[4]*a/c[3],c[5],c[6],c[7]);case "EText":return d=Value.getTextSize(a,c[4],d[2]),k(c[2],a,d[1],c[5],c[6],c[7])}return k(c[2],a,c[4],c[5],c[6],c[7])}},height:function(a){return function(c){switch(c[2][0]){case "EImage":case "EVideo":return k(c[2],c[3]*a/c[4],a,c[5],c[6],c[7])}return k(c[2],c[3],a,c[5],c[6],c[7])}},size:function(a){return function(c){return function(d){return k(d[2],
a,c,d[5],d[6],d[7])}}},opacity:function(a){return function(c){return k(c[2],c[3],c[4],a,c[6],c[7])}},color:function(a){return function(c){return k(c[2],c[3],c[4],c[5],["Just",a],c[7])}},link:function(a){return function(c){return k(c[2],c[3],c[4],c[5],c[6],["Just",r.castStringToJSString(a)])}},widthOf:d,heightOf:l,sizeOf:function(a){return["Tuple2",~~a[3],~~a[4]]},text:function(a){var d=Value.getTextSize(0,0,a);return c(j("left")(a),d[0],d[1])},asText:function(a){a=Elm.Text.monospace(Value.toText(Value.show(a)));
var d=Value.getTextSize(0,0,a);return c(j("left")(a),d[0],d[1])},plainText:function(a){a=Value.toText(a);var d=Value.getTextSize(0,0,a);return c(j("left")(a),d[0],d[1])},centeredText:function(a){var d=Value.getTextSize(0,0,a);return c(j("center")(a),d[0],d[1])},justifiedText:function(a){var d=Value.getTextSize(0,0,a);return c(j("justify")(a),d[0],d[1])},rightedText:function(a){var d=Value.getTextSize(0,0,a);return c(j("right")(a),d[0],d[1])},image:y,images:function(a){var c=Elm.Signal.constant(n(0)(0));
a=Elm.Signal.lift(function(a){a=r.castStringToJSString(a);var d=new Image;d.onload=function(){Dispatcher.notify(c.id,y(this.width)(this.height)(a))};d.src=a})(a);return Elm.Signal.lift2(function(a){return function(){return a}})(c)(a)},video:function(a){return function(d){return function(b){return c(["EVideo",r.castStringToJSString(b)],a,d)}}},fittedImage:function(a){return function(d){return function(b){return c(["EFittedImage",r.castStringToJSString(b)],a,d)}}},flow:function(b){return function(e){var g;
g=map(d)(e);a:{switch(b[0]){case "DLeft":g=sum(g);break a;case "DRight":g=sum(g);break a}g=maximum(g)}var f;f=map(l)(e);a:{switch(b[0]){case "DDown":f=sum(f);break a;case "DUp":f=sum(f);break a}f=maximum(f)}return c(a(b)(e),g,f)}},above:function(d){return function(b){return c(a(s)(["Cons",d,["Cons",b,["Nil"]]]),Math.max(~~d[3],~~b[3]),~~d[4]+~~b[4])}},below:function(d){return function(b){return c(a(s)(["Cons",b,["Cons",d,["Nil"]]]),Math.max(~~d[3],~~b[3]),~~d[4]+~~b[4])}},beside:function(d){return function(b){return c(a(x)(["Cons",
d,["Cons",b,["Nil"]]]),~~d[3]+~~b[3],Math.max(~~d[4],~~b[4]))}},layers:function(b){return c(a(u)(b),maximum(map(d)(b)),maximum(map(l)(b)))},collage:function(a){return function(d){return function(b){return c(["ECollage",a,d,Value.groupForms(b)],a,d)}}},spacer:n,container:function(a){return function(d){return function(b){return function(e){return c(["EContainer",b,e],a,d)}}}},line:e,segment:function(a){return function(c){return e(["Cons",a,["Cons",c,["Nil"]]])}},polygon:h,rect:function(a){return function(c){return function(d){return h(["Cons",
["Tuple2",0-a/2,0-c/2],["Cons",["Tuple2",0-a/2,c/2],["Cons",["Tuple2",a/2,c/2],["Cons",["Tuple2",a/2,0-c/2],["Nil"]]]]])(d)}}},oval:p,circle:function(a){return p(2*a)(2*a)},ngon:function(a){return function(c){return function(d){var b=map(function(d){return["Tuple2",c*Math.cos(2*(Math.PI/a)*d),c*Math.sin(2*(Math.PI/a)*d)]}),e=a-1,l=["Nil"];if(0<=e){do l=["Cons",e,l];while(0<e--)}return h(b(l))(d)}}},solid:function(a){return function(c){return b(0)(1)(["Tuple2",0,0])(m(w)(a)(c))}},dotted:function(a){return function(c){return b(0)(1)(["Tuple2",
0,0])(m(D)(a)(c))}},dashed:function(a){return function(c){return b(0)(1)(["Tuple2",0,0])(m(F)(a)(c))}},customLine:function(a){return function(c){return function(d){return b(0)(1)(["Tuple2",0,0])(m(["Custom",r.castListToJSArray(a)])(c)(d))}}},filled:function(a){return function(c){return b(0)(1)(c[2])(g(B)(a)(c))}},outlined:function(a){return function(c){return b(0)(1)(c[2])(g(E)(a)(c))}},customOutline:function(a){return function(c){return function(d){return b(0)(1)(d[2])(g(["CustomOutline",r.castListToJSArray(a)])(c)(d))}}},
textured:function(a){return function(c){return b(0)(1)(c[2])(g(["Textured",a])(null)(c))}},sprite:function(a){return function(c){return function(d){return function(e){return b(0)(1)(e)(["FImage",c,d,r.castStringToJSString(a)])}}}},toForm:function(a){return function(c){return b(0)(1)(a)(["FElement",c])}},rotate:function(a){return function(c){a:{switch(c[0]){case "Form":var d=c[2],e=c[3],l=c[4];c=b(a+c[1])(d)(e)(l);break a}throw"Non-exhaustive pattern match in case";}return c}},scale:function(a){return function(c){return b(c[1])(a*
c[2])(c[3])(c[4])}},move:function(a){return function(c){return function(d){var e;a:{switch(d[0]){case "Form":e=d[1];var l=d[2],g=d[3];d=d[4];switch(g[0]){case "Tuple2":var f=g[1],g=g[2];e=b(e)(l)(["Tuple2",a+f,c+g])(d);break a}}throw"Non-exhaustive pattern match in case";}return e}}},isWithin:Collage.insideForm}}();
Elm.Text=function(){function f(a){return Value.toText(a)}var j=function(a){return function(d){return"<"+a+' style="padding:0;margin:0">'+d+"</"+a+">"}},a=function(a,d){return function(b){return"<span style='"+a+":"+d+"'>"+b+"</span>"}},e=function(c){c=Elm.JavaScript.castStringToJSString(c);return a("font-family",c)},h=j("h1"),b=a("font-style","italic"),j=j("b"),m=a("text-decoration","underline"),g=a("text-decoration","overline"),k=a("text-decoration","line-through");return{fromString:f,toText:f,header:h,
height:function(c){return a("font-size",c+"em")},italic:b,bold:j,underline:m,overline:g,strikeThrough:k,monospace:e("monospace"),typeface:e,color:function(c){return a("color",Elm.Color.extract(c))},link:function(a){return function(d){return"<a href='"+f(a)+"'>"+d+"</a>"}}}}();
var Render=function(){function f(a){a=document.createElement(a);a.style.padding="0";a.style.margin="0";return a}function j(a){return a}function a(a){a.style.styleFloat="left";a.style.cssFloat="left";return a}function e(a){a.style.position="absolute";return a}function h(a,d,b){for(var e=f("div"),g=b.length;g--;){var h=a(d(b[g]));e.appendChild(h)}return e}function b(a){switch(a[0]){case "Absolute":return a[1]+"px";case "Relative":return 100*a[1]+"%"}}function m(a,d){d.style.position="absolute";d.style.margin=
"auto";switch(a[0]){case "Position":"Far"!==a[1][0]&&(d.style.left=0);"Near"!==a[1][0]&&(d.style.right=0);"Far"!==a[2][0]&&(d.style.top=0);"Near"!==a[2][0]&&(d.style.bottom=0);break;case "PositionAt":d.style.top=b(a[2]);d.style.left=b(a[1]);var e="translate("+~~(-d.style.width.slice(0,-2)/2)+"px,"+~~(-d.style.height.slice(0,-2)/2)+"px)";d.style.transform=e;d.style.msTransform=e;d.style.MozTransform=e;d.style.webkitTransform=e;d.style.OTransform=e;break;default:e=a[0].slice(-2),d.style["T"===e[0]?
"top":"bottom"]=b(a[2]),d.style["L"===e[1]?"left":"right"]=b(a[1])}}function g(c){var d={};switch(c[2][0]){case "EText":var d=c[2][1],b=c[2][2],k=f("div");k.innerHTML=b;k.style.textAlign=d;d=k;break;case "EImage":d=c[2][1];b=f("img");b.src=d;b.name=d;b.style.display="block";d=b;break;case "EVideo":k=c[2][1];d=f("video");d.controls="controls";b=f("source");b.src=k;k=k.split(".");b.type="video/"+k[k.length-1];d.appendChild(b);d.style.display="block";break;case "EFittedImage":var n=c[3],p=c[4],d=c[2][1],
b=f("div");b.style.width=n+"px";b.style.height=p+"px";b.style.position="relative";b.style.overflow="hidden";var r=f("img");r.onload=function(){r.style.position="absolute";r.style.margin="auto";var a=n,c=p;n/p>this.width/this.height?c=Math.round(this.height*n/this.width):a=Math.round(this.width*p/this.height);r.style.width=a+"px";r.style.height=c+"px";r.style.left=(n-a)/2+"px";r.style.top=(p-c)/2+"px"};r.src=d;r.name=d;b.appendChild(r);d=b;break;case "EFlow":a:{d=c[2][2];switch(c[2][1][0]){case "DDown":d=
d.slice(0).reverse();case "DUp":d=h(j,g,d);break a;case "DRight":d=d.slice(0).reverse();case "DLeft":d=h(a,g,d);break a;case "DOut":d=d.slice(0).reverse();case "DIn":d=h(e,g,d);break a}d=void 0}break;case "ECollage":d=Collage.collage(c[2][1],c[2][2],c[2][3]);break;case "EEmpty":d=f("div");break;case "EContainer":b=c[2][1];d=g(c[2][2]);m(b,d);b=f("div");b.style.position="relative";b.style.overflow="hidden";b.appendChild(d);d=b;break;case "EHtml":d=c[2][1];"button"!==d.type&&(b=Value.getExcess(d),c[3]-=
b[0],c[4]-=b[1]);break;case "EExternalHtml":d=f("div"),d.appendChild(c[2][1])}d.id=c[1];d.style.width=~~c[3]+"px";d.style.height=~~c[4]+"px";1!==c[5]&&(d.style.opacity=c[5]);"Just"===c[6][0]&&(d.style.backgroundColor=Elm.Color.extract(c[6][1]));return"Just"===c[7][0]?(b=f("a"),b.href=c[7][1],b.appendChild(d),b):d}function k(c,d,b){"A"===c.tagName&&(c=c.firstChild);if(d[1]!==b[1]){if(d[2][0]!==b[2][0])return c.parentNode.replaceChild(g(b),c);var f=b[2],n=d[2];switch(f[0]){case "EText":f[1]!==n[1]&&
(c.style.textAlign=f[1]);f[2]!==n[2]&&(c.innerHTML=f[2]);break;case "EImage":f[1]!==n[1]&&(c.src=f[1]);break;case "EVideo":case "EFittedImage":if(!Value.eq(f,n)||b[3]!==d[3]||b[4]!==d[4])return c.parentNode.replaceChild(g(b),c);break;case "ECollage":if(f[1]!==n[1]||f[2]!==n[2]||f[3].length!==n[3].length)return c.parentNode.replaceChild(g(b),c);Collage.updateCollage(c,n[3],f[3]);break;case "EFlow":if(f[1]!==n[1])return c.parentNode.replaceChild(g(b),c);var h=f[2],r=c.childNodes;if(h.length!==r.length)return c.parentNode.replaceChild(g(b),
c);var n=n[2],x=function(a){return a};switch(f[1][0]){case "DDown":case "DUp":x=j;break;case "DRight":case "DLeft":x=a;break;case "DOut":case "DIn":x=e}for(f=r.length;f--;)k(r[f],n[f],h[f]),x(r[f]);break;case "EContainer":k(c.childNodes[0],n[2],f[2]);m(f[1],c.childNodes[0]);break;case "EHtml":b[1]!==d[1]&&(h=g(b),c.parentNode.replaceChild(h,c),c=h);"button"!==h.type&&(f=Value.getExcess(c),b[3]-=f[0],b[4]-=f[1]);break;case "EExternalHtml":b[1]!==d[1]&&c.parentNode.replaceChild(g(b),c)}b[3]!==d[3]&&
(c.style.width=~~b[3]+"px");b[4]!==d[4]&&(c.style.height=~~b[4]+"px");b[5]!==d[5]&&(c.style.opacity=b[5]);2===b[6].length&&(f=Elm.Color.extract(b[6][1]),f!==c.style.backgroundColor&&(c.style.backgroundColor=f));if(2===b[7].length&&(1===d[7].length||b[7][1]!==d[7][1]))c.parentNode.href=b[7][1];b[1]=d[1]}}return{render:g,update:k,addTo:function(a,d){a.appendChild(d)},newElement:f,flowWith:h,goIn:e}}();
Elm.Signal=function(){function f(a){this.id=Guid.guid();this.value=a;this.kids=[];this.defaultNumberOfKids=0;this.recv=function(a,c,d){if(c=c===this.id)this.value=d;k(this,a,c);return c};Dispatcher.inputs.push(this)}function j(a,c){this.id=Guid.guid();this.value=null;this.kids=[];this.count=0;this.changed=!1;c.reverse();this.recalc=function(){for(var b=a,e=c.length;e--;)b=b(c[e].value);this.value=b};this.recalc();this.recv=function(a,d){this.count+=1;d&&(this.changed=!0);this.count==c.length&&(this.changed&&
this.recalc(),k(this,a,this.changed),this.changed=!1,this.count=0)};for(var b=c.length;b--;)c[b].kids.push(this)}function a(a,c,b,e){this.id=Guid.guid();this.value=b?c(e.value):c;this.kids=[];this.recv=function(c,b){b&&(this.value=a(e.value)(this.value));k(this,c,b)};e.kids.push(this)}function e(a,c,b){this.id=Guid.guid();this.value=a(b.value)?c:b.value;this.kids=[];this.recv=function(c,e){var f=e&&!a(b.value);f&&(this.value=b.value);k(this,c,f)};b.kids.push(this)}function h(a){this.id=Guid.guid();
this.value=a.value;this.kids=[];this.recv=function(c,b){var e=b&&!Value.eq(this.value,a.value);e&&(this.value=a.value);k(this,c,e)};a.kids.push(this)}function b(a,c){this.id=Guid.guid();var b=(new window.Date).getTime();this.value=a?Value.Tuple(b,c.value):b;this.kids=[];this.recv=function(b,e){e&&(this.value=a?Value.Tuple(b,c.value):b);k(this,b,e)};c.kids.push(this)}function m(a,c){this.id=Guid.guid();this.value=c.value;this.kids=[];this.count=0;this.changed=!1;this.recv=function(b,e,f){f===a.id&&
(this.changed=e);this.count+=1;2==this.count&&(this.changed&&(this.value=c.value),k(this,b,this.changed),this.count=0,this.changed=!1)};a.kids.push(this);c.kids.push(this)}function g(a,c){this.id=Guid.guid();this.value=a.value;this.kids=[];this.next=null;this.count=0;this.changed=!1;this.recv=function(b,e,f){this.count+=1;e&&(this.changed=!0,f==c.id&&null===this.next&&(this.next=c.value),f==a.id&&(this.next=a.value));2==this.count&&(this.changed&&(this.value=this.next,this.next=null),k(this,b,this.changed),
this.changed=!1,this.count=0)};a.kids.push(this);c.kids.push(this)}var k=function(a,c,b){for(var e=a.kids,f=e.length;f--;)e[f].recv(c,b,a.id)},c=function(a){return function(c){return function(b){b=new j(function(a){return function(c){return[a,c]}},[a,b]);b=new e(function(a){return a[0]},[!0,c],b);return new j(function(a){return a[1]},[b])}}};return{constant:function(a){return new f(a)},lift:function(a){return function(c){return new j(a,[c])}},lift2:function(a){return function(c){return function(b){return new j(a,
[c,b])}}},lift3:function(a){return function(c){return function(b){return function(e){return new j(a,[c,b,e])}}}},lift4:function(a){return function(c){return function(b){return function(e){return function(f){return new j(a,[c,b,e,f])}}}}},lift5:function(a){return function(c){return function(b){return function(e){return function(f){return function(g){return new j(a,[c,b,e,f,g])}}}}}},lift6:function(a){return function(c){return function(b){return function(e){return function(f){return function(g){return function(h){return new j(a,
[c,b,e,f,g,h])}}}}}}},lift7:function(a){return function(c){return function(b){return function(e){return function(f){return function(g){return function(h){return function(k){return new j(a,[c,b,e,f,g,h,k])}}}}}}}},lift8:function(a){return function(c){return function(b){return function(e){return function(f){return function(g){return function(h){return function(k){return function(m){return new j(a,[c,b,e,f,g,h,k,m])}}}}}}}}},foldp:function(c){return function(b){return function(e){return new a(c,b,!1,
e)}}},foldp_:function(c){return function(b){return function(e){return new a(c,b,!0,e)}}},foldp1:function(c){return function(b){return new a(c,function(a){return a},!0,b)}},delay:function(a){return function(c){var b=new f(c.value),e=!0;c=new m(b,new j(function(a){return function(){return a}},[b,new j(function(c){e||setTimeout(function(){Dispatcher.notify(b.id,c)},a)},[c])]));e=!1;return c}},merge:function(a){return function(c){return new g(a,c)}},merges:function(a){return Elm.List.foldl1(function(a){return function(c){return new g(a,
c)}})(a)},average:function(a){return function(c){for(var b=Array(a),e=a;e--;)b[e]=0;var e=0,f=!1,g=0;return new j(function(c){g+=c-b[e];b[e]=c;c=g/Math.max(1,f?a:e);++e==a&&(f=!0,e=0);return c},[c])}},count:function(c){return new a(function(){return function(a){return a+1}},0,!1,c)},countIf:function(c){return function(b){return new a(function(a){return function(b){return c(a)?b+1:b}},0,!1,b)}},keepIf:function(a){return function(c){return function(b){return new e(function(c){return!a(c)},c,b)}}},dropIf:function(a){return function(c){return function(b){return new e(a,
c,b)}}},keepWhen:function(a){return c(new j(function(a){return!a},[a]))},dropWhen:c,dropRepeats:function(a){return new h(a)},sampleOn:function(a){return function(c){return new m(a,c)}},timestamp:function(a){return new b(!0,a)},timeOf:function(a){return new b(!1,a)}}}();
var Dispatcher=function(){function f(a){if(!a.hasOwnProperty("defaultNumberOfKids"))return!0;var b=a.kids.length;if(0==b)return!1;if(b>a.defaultNumberOfKids)return!0;for(var e=!1;b--;)e=e||f(a.kids[b]);return e}var j=null,a=[],e=null;return{initialize:function(){j=Elm.main();j.hasOwnProperty("recv")||(j=Elm.Signal.constant(j));e=j.value;for(var h=[],b=a.length;b--;)f(a[b])&&h.push(a[b]);a=h;document.getElementById("content").appendChild(Render.render(e));h=document.getElementById("widthChecker").offsetWidth;
h!==window.innerWidth&&Dispatcher.notify(Elm.Window.dimensions.id,Value.Tuple(h,window.innerHeight));j=Elm.Signal.lift(function(a){var b=document.getElementById("content");Render.update(b.firstChild,e,a);return e=a})(j)},notify:function(e,b){for(var f=(new window.Date).getTime(),g=!1,k=a.length;k--;)g=a[k].recv(f,e,b)||g;return g},inputs:a}}();
Elm.HTTP=function(){function f(a){return function(e){return function(c){return function(d){return{"0":"Request",length:1,verb:b.castStringToJSString(a),url:b.castStringToJSString(e),data:null===c?null:b.castStringToJSString(c),headers:d}}}}}function j(a){return f("GET")(a)(null)(["Nil"])}function a(a,f){return function(c){if(""!==c.url){var d={value:["Waiting"]};a.push(d);var h=null;window.ActiveXObject&&(h=new ActiveXObject("Microsoft.XMLHTTP"));window.XMLHttpRequest&&(h=new XMLHttpRequest);h.onreadystatechange=
function(){4===h.readyState&&(d.value=200===h.status?["Success",m(h.responseText)]:["Failure",h.status,m(h.statusText)],setTimeout(function(){e(a,f)},0))};h.open(c.verb,c.url,!0);Elm.List.map(function(a){h.setRequestHeader(b.castStringToJSString(a[1]),b.castStringToJSString(a[2]))})(c.headers);h.send(c.data)}}}function e(a,b){0<a.length&&(Dispatcher.notify(b.id,a[0].value),"Waiting"!==a[0].value[0]&&(a.shift(),setTimeout(function(){e(a,b)},0)))}function h(b){var e=Elm.Signal.constant(["Waiting"]);
b=Elm.Signal.lift(a([],e))(b);return Elm.Signal.lift2(function(a){return function(){return a}})(e)(b)}var b=Elm.JavaScript,m=Elm.JavaScript.castJSStringToString;return{get:j,post:function(a){return function(b){return f("POST")(a)(b)(["Nil"])}},request:f,send:h,sendGet:function(a){return h(Elm.Signal.lift(j)(a))}}}();
Elm.Input=function(){var f=Elm.JavaScript,j=Elm.JavaScript.castJSStringToString,a=function(a,e){a.placeholder=f.castStringToJSString(e);var g=Elm.Signal.constant(["Nil"]);Value.addListener(a,"keyup",function(){Dispatcher.notify(g.id,j(a.value));a.focus()});a.style.padding="1px";return Value.Tuple(Value.wrap(a),g)},e=function(a){a=document.createElement(a);a.style.padding="0";a.style.margin="0";return a},h=function(a){for(var f=e("select"),g=[];"Cons"===a[0];){var h=e("option"),c=Value.toText(a[1][1]);
h.value=c;h.innerHTML=c;f.appendChild(h);g.push(a[1][2]);a=a[2]}var d=Elm.Signal.constant(g[0]);Value.addListener(f,"change",function(){Dispatcher.notify(d.id,g[f.selectedIndex])});return Value.Tuple(Value.wrap(f),d)};return{textArea:function(b){return function(f){var g=e("textarea");g.rows=f;g.cols=b;return a(g,"")}},textField:function(b){var f=e("input");f.type="text";return a(f,b)},password:function(b){var f=e("input");f.type="password";return a(f,b)},checkbox:function(a){var f=e("input");f.type=
"checkbox";f.checked=a;var g=Elm.Signal.constant(a);Value.addListener(f,"change",function(){Dispatcher.notify(g.id,f.checked)});return Value.Tuple(Value.wrap(f),g)},dropDown:h,stringDropDown:function(a){return h(Elm.List.map(function(a){return Value.Tuple(a,a)})(a))},button:function(a){var h=e("input");h.type="button";h.value=f.castStringToJSString(a);var g=Elm.Signal.constant(!1);Value.addListener(h,"click",function(){Dispatcher.notify(g.id,!0);Dispatcher.notify(g.id,!1)});return Value.Tuple(Value.wrap(h),
g)}}}();
Elm.Keyboard={Raw:function(){function f(a,h){return"Nil"===h[0]?h:h[1]===a?h[2]:["Cons",h[1],f(a,h[2])]}var j=Elm.Signal.constant(["Nil"]),a=Elm.Signal.constant(["Nothing"]);Value.addListener(document,"keydown",function(a){var f;a:{for(f=j.value;"Nil"!==f[0];){if(f[1]===a.keyCode){f=!0;break a}f=f[2]}f=!1}f||Dispatcher.notify(j.id,["Cons",a.keyCode,j.value])||this.removeEventListener("keydown",arguments.callee,!1)});Value.addListener(document,"keyup",function(a){var h=f(a.keyCode,j.value);Dispatcher.notify(j.id,
h)||this.removeEventListener("keyup",arguments.callee,!1)});Value.addListener(window,"blur",function(a){Dispatcher.notify(j.id,["Nil"])||this.removeEventListener("blur",arguments.callee,!1)});Value.addListener(document,"keypress",function(e){var f=Dispatcher.notify(a.id,["Just",e.charCode||e.keyCode]);Dispatcher.notify(a.id,["Nothing"]);f||this.removeEventListener("keypress",arguments.callee,!1)});return{keysDown:j,charPressed:a}}()};
Elm.Mouse=function(){function f(a){var b=0,c=0;a||(a=window.event);if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return Value.Tuple(b,c)}var j=Elm.Signal.constant(Value.Tuple(0,0));j.defaultNumberOfKids=2;var a=Elm.Signal.lift(function(a){return a[1]})(j);a.defaultNumberOfKids=0;var e=Elm.Signal.lift(function(a){return a[2]})(j);e.defaultNumberOfKids=
0;var h=Elm.Signal.constant(!1),b=Elm.Signal.constant(!1),m=Elm.Signal.constant(Value.Tuple());Value.addListener(document,"click",function(a){var e=Dispatcher.notify(b.id,!0),c=Dispatcher.notify(m.id,Value.Tuple());Dispatcher.notify(b.id,!1);!e&&!c&&this.removeEventListener("click",arguments.callee,!1)});Value.addListener(document,"mousedown",function(a){Dispatcher.notify(h.id,!0)||this.removeEventListener("mousedown",arguments.callee,!1)});Value.addListener(document,"mouseup",function(a){Dispatcher.notify(h.id,
!1)||this.removeEventListener("mouseup",arguments.callee,!1)});Value.addListener(document,"mousemove",function(a){Dispatcher.notify(j.id,f(a))||this.removeEventListener("mousemove",arguments.callee,!1)});return{position:j,x:a,y:e,isClicked:b,isDown:h,clicks:m,isClickedOn:function(a){a=Render.render(a);var b=Elm.Signal.constant(!1);Value.addListener(a,"click",function(){Dispatcher.notify(b.id,!0);Dispatcher.notify(b.id,!1)});return Value.Tuple(Value.wrap(a),b)}}}();
Elm.Random=function(){return{inRange:function(f){return function(j){return Elm.Signal.constant(Math.floor(Math.random()*(j-f+1))+f)}},randomize:function(f){return function(j){return function(a){return Elm.Signal.lift(function(){return Math.floor(Math.random()*(j-f+1))+f})(a)}}}}}();
Elm.Time=function(){function f(){return(new window.Date).getTime()}function j(a){return function(e){var h=1E3/a,b=f(),j=b,g=0,k=!0,c=Elm.Signal.constant(g),d=0;return Elm.Signal.lift2(function(a){return function(e){if(a){var n=!k&&a;d=setTimeout(function(){j=f();g=n?0:j-b;b=j;Dispatcher.notify(c.id,g)},h)}else k&&clearTimeout(d);k=a;return e}})(e)(c)}}Elm.Signal.constant(!0);return{fpsWhen:j,fps:function(a){return j(a)(Elm.Signal.constant(!0))},every:function(a){var e=Elm.Signal.constant(f());setInterval(function(){Dispatcher.notify(e.id,
f())},a);return e},delay:Elm.Signal.delay,since:function(a){return function(e){var f=Elm.Signal.count(Elm.Signal.delay(a)(e));return Elm.Signal.lift2(function(a){return function(e){return!Value.eq(a,e)}})(Elm.Signal.count(e))(f)}},after:function(a){a*=1E3;var e=Elm.Signal.constant(!1);setTimeout(function(){Dispatcher.notify(e.id,!0)},a);return e},before:function(a){a*=1E3;var e=Elm.Signal.constant(!0);setTimeout(function(){Dispatcher.notify(e.id,!1)},a);return e},hour:36E5,minute:6E4,second:1E3,ms:1,
inHours:function(a){return a/36E5},inMinutes:function(a){return a/6E4},inSeconds:function(a){return a/1E3},inMss:function(a){return a},toDate:function(a){return new window.Date(a)},read:function(a){a=window.Date.parse(a);return isNaN(a)?["Nothing"]:["Just",a]}}}();
Elm.Window=function(){var f=Elm.Signal.constant(Value.Tuple(window.innerWidth,window.innerHeight));f.defaultNumberOfKids=2;var j=Elm.Signal.lift(function(a){return a[1]})(f);j.defaultNumberOfKids=0;var a=Elm.Signal.lift(function(a){return a[2]})(f);a.defaultNumberOfKids=0;Value.addListener(window,"resize",function(a){var h=document.getElementById("widthChecker").offsetWidth;Dispatcher.notify(f.id,Value.Tuple(h,window.innerHeight))||this.removeEventListener("resize",arguments.callee,!1)});return{dimensions:f,
width:j,height:a}}();
Elm.Date=function(){var f="Sun Mon Tue Wed Thu Fri Sat".split(" "),j="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");return{read:function(a){a=new window.Date(Elm.JavaScript.castStringToJSString(a));return isNaN(a.getTime())?["Nothing"]:["Just",a]},year:function(a){return a.getFullYear()},month:function(a){return[j[a.getMonth()]]},day:function(a){return a.getDate()},hour:function(a){return a.getHours()},minute:function(a){return a.getMinutes()},second:function(a){return a.getSeconds()},dayOfWeek:function(a){return[f[a.getDay()]]},
toTime:function(a){return a.getTime()},Mon:["Mon"],Tue:["Tue"],Wed:["Wed"],Thu:["Thu"],Fri:["Fri"],Sat:["Sat"],Sun:["Sun"],Jan:["Jan"],Feb:["Feb"],Mar:["Mar"],Apr:["Apr"],May:["May"],Jun:["Jun"],Jul:["Jul"],Aug:["Aug"],Sep:["Sep"],Oct:["Oct"],Nov:["Nov"],Dec:["Dec"]}}();Value.addListener(document,"elm_log",function(f){console.log(f.value)});Value.addListener(document,"elm_title",function(f){document.title=f.value});
Value.addListener(document,"elm_redirect",function(f){0<f.value.length&&(window.location=f.value)});
Elm.Prelude=function(){function f(a){return function(e){if(a instanceof Array&&e instanceof Array){var h=a.length;if(h==e.length){for(var b=1;b<h;++b){var j=f(a[b])(e[b]);if("EQ"!==j[0])return j}return["EQ"]}return[1==e.length?"GT":"LT"]}return[a===e?"EQ":a<e?"LT":"GT"]}}var j=function(a){return function(e){var f=a%e,f=0==a?0:0<e?0<=a?f:f+e:-j(-a)(-e);return f==e?0:f}};return{eq:Value.eq,id:function(a){return a},not:function(a){return!a},fst:function(a){return a[1]},snd:function(a){return a[2]},rem:function(a){return function(e){return a%
e}},div:function(a){return function(e){return~~(a/e)}},otherwise:!0,compare:f,toFloat:function(a){return a},round:function(a){return Math.round(a)},floor:function(a){return Math.floor(a)},ceiling:function(a){return Math.ceil(a)},truncate:function(a){return~~a},readInt:function(a){a=Elm.JavaScript.castStringToJSString(a);var e=a.length;if(0===e)return["Nothing"];var f=0;if("-"==a[0]){if(1===e)return["Nothing"];f=1}for(;f<e;++f)if(!Elm.Char.isDigit(a[f]))return["Nothing"];return["Just",parseInt(a)]},
readFloat:function(a){a=Elm.JavaScript.castStringToJSString(a);var e=a.length;if(0===e)return["Nothing"];var f=0;if("-"==a[0]){if(1===e)return["Nothing"];f=1}for(var b=0;f<e;++f)if(!Elm.Char.isDigit(a[f])){if("."===a[f]&&(b+=1,1>=b))continue;return["Nothing"]}return["Just",parseFloat(a)]},sqrt:Math.sqrt,abs:Math.abs,pi:Math.PI,e:Math.E,sin:Math.sin,cos:Math.cos,tan:Math.tan,asin:Math.asin,acos:Math.acos,atan:Math.atan,atan2:function(a){return function(e){return Math.atan2(a,e)}},mod:j,min:function(a){return function(e){return Math.min(a,
e)}},max:function(a){return function(e){return Math.max(a,e)}},flip:function(a){return function(e){return function(f){return a(f)(e)}}},clamp:function(a){return function(e){return function(f){return Math.min(e,Math.max(a,f))}}},curry:function(a){return function(e){return function(f){return a(["Tuple2",e,f])}}},uncurry:function(a){return function(e){if("Tuple2"!==e[0])throw"Function was uncurry'd but was not given a pair.";return a(e[1])(e[2])}},logBase:function(a){return function(e){return Math.log(e)/
Math.log(a)}},Just:Elm.Maybe.Just,Nothing:Elm.Maybe.Nothing,maybe:Elm.Maybe.maybe,map:Elm.List.map,zip:Elm.List.zip,zipWith:Elm.List.zipWith,filter:Elm.List.filter,head:Elm.List.head,tail:Elm.List.tail,last:Elm.List.last,length:Elm.List.length,reverse:Elm.List.reverse,foldr:Elm.List.foldr,foldr1:Elm.List.foldr1,foldl:Elm.List.foldl,foldl1:Elm.List.foldl1,and:Elm.List.and,or:Elm.List.or,all:Elm.List.all,any:Elm.List.any,sum:Elm.List.sum,product:Elm.List.product,concat:Elm.List.concat,concatMap:Elm.List.concatMap,
maximum:Elm.List.maximum,minimum:Elm.List.minimum,scanl:Elm.List.scanl,scanl1:Elm.List.scanl1,take:Elm.List.take,drop:Elm.List.drop,zip:Elm.List.zip,unzip:Elm.List.unzip,lift:Elm.Signal.lift,lift2:Elm.Signal.lift2,lift3:Elm.Signal.lift3,lift4:Elm.Signal.lift4,lift5:Elm.Signal.lift5,lift6:Elm.Signal.lift6,lift7:Elm.Signal.lift7,lift8:Elm.Signal.lift8,foldp:Elm.Signal.foldp,foldp1:Elm.Signal.foldp1,foldp_:Elm.Signal.foldp_,constant:Elm.Signal.constant,merge:Elm.Signal.merge,count:Elm.Signal.count,countIf:Elm.Signal.countIf,
average:Elm.Signal.average,keepIf:Elm.Signal.keepIf,dropIf:Elm.Signal.dropIf,keepWhen:Elm.Signal.keepWhen,dropWhen:Elm.Signal.dropWhen,dropRepeats:Elm.Signal.dropRepeats,sampleOn:Elm.Signal.sampleOn,timestamp:Elm.Signal.timestamp,timeOf:Elm.Signal.timeOf}}();(function(){var f=function(f){for(var a in f)Elm.Prelude[a]=f[a]};f(Elm.Color);f(Elm.Text);f(Elm.Graphics);f(Elm.Time);show=Value.show})();
Elm.Dict=function(){function f(a){return function(c){return function(b){return function(d){return function(e){return["RBNode",a,c,b,d,e]}}}}}function j(a){a:{switch(a[0]){case "RBEmpty":throw"(min RBEmpty) is not defined";case "RBNode":switch(a[4][0]){case "RBEmpty":a=["Tuple2",a[2],a[3]];break a}a=j(a[4]);break a}throw"Non-exhaustive pattern match in case";}return a}function a(c){return function(b){var d;a:{switch(b[0]){case "RBEmpty":d=v;break a;case "RBNode":d=function(){switch(q(c)(b[2])[0]){case "EQ":return A(b[3]);
case "GT":return a(c)(b[5]);case "LT":return a(c)(b[4])}throw"Non-exhaustive pattern match in case";}();break a}throw"Non-exhaustive pattern match in case";}return d}}function e(a){return function(c){return function(b){var d;a:{switch(b[0]){case "RBEmpty":d=a;break a;case "RBNode":d=function(){switch(q(c)(b[2])[0]){case "EQ":return b[3];case "GT":return e(a)(c)(b[5]);case "LT":return e(a)(c)(b[4])}throw"Non-exhaustive pattern match in case";}();break a}throw"Non-exhaustive pattern match in case";
}return d}}}function h(c){return function(b){return F(a(c)(b))}}function b(a){a:{switch(a[0]){case "RBNode":switch(a[5][0]){case "RBNode":a=f(a[1])(a[5][2])(a[5][3])(f(B)(a[2])(a[3])(a[4])(a[5][4]))(a[5][5]);break a}}throw"rotateLeft of a node without enough children";}return a}function m(a){a:{switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":a=f(a[1])(a[4][2])(a[4][3])(a[4][4])(f(B)(a[2])(a[3])(a[4][5])(a[5]));break a}}throw"rotateRight of a node without enough children";}return a}function g(a){a:{switch(a[0]){case "Black":a=
B;break a;case "Red":a=E;break a}throw"Non-exhaustive pattern match in case";}return a}function k(a){a:{switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[5][0]){case "RBNode":a=f(g(a[1]))(a[2])(a[3])(f(g(a[4][1]))(a[4][2])(a[4][3])(a[4][4])(a[4][5]))(f(g(a[5][1]))(a[5][2])(a[5][3])(a[5][4])(a[5][5]));break a}}}throw"color_flip called on a RBEmpty or RBNode with a RBEmpty child";}return a}function c(a){a:switch(a[0]){case "RBNode":switch(a[5][0]){case "RBNode":switch(a[5][1][0]){case "Red":a=
b(a);break a}}}a:switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][1][0]){case "Red":switch(a[4][4][0]){case "RBNode":switch(a[4][4][1][0]){case "Red":a=m(a);break a}}}}}a:switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][1][0]){case "Red":switch(a[5][0]){case "RBNode":switch(a[5][1][0]){case "Red":a=k(a);break a}}}}}return a}function d(a){a:switch(a[0]){case "RBNode":switch(a[1][0]){case "Red":a=f(E)(a[2])(a[3])(a[4])(a[5]);break a}}return a}function l(a){return function(b){return function(e){var g=
function(d){var e;a:{switch(d[0]){case "RBEmpty":e=f(B)(a)(b)(z)(z);break a;case "RBNode":e=function(){switch(q(a)(d[2])[0]){case "EQ":return f(d[1])(d[2])(b)(d[4])(d[5]);case "GT":return f(d[1])(d[2])(d[3])(d[4])(g(d[5]));case "LT":return f(d[1])(d[2])(d[3])(g(d[4]))(d[5])}throw"Non-exhaustive pattern match in case";}();e=c(e);break a}throw"Non-exhaustive pattern match in case";}return e};return d(g(e))}}}function y(a){a:{switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][1][0]){case "Red":a=
!0;break a}}}a=!1}return a}function n(a){a:{switch(a[0]){case "RBNode":switch(a[4][0]){case "RBNode":switch(a[4][4][0]){case "RBNode":switch(a[4][4][1][0]){case "Red":a=!0;break a}}}}a=!1}return a}function p(a){if(w(y(a))&&w(n(a))){a=k(a);a:switch(a[0]){case "RBNode":b:switch(a[5][0]){case "RBNode":switch(a[5][4][0]){case "RBNode":switch(a[5][4][1][0]){case "Red":a=k(b(f(a[1])(a[2])(a[3])(a[4])(m(a[5]))));break b}}}break a}}return a}function r(a){return function(b){var e=function(b){a:{switch(b[0]){case "RBEmpty":b=
z;break a;case "RBNode":if("LT"===q(a)(b[2])[0])b:{b=p(b);switch(b[0]){case "RBEmpty":throw"delLT on RBEmpty";case "RBNode":b=c(f(b[1])(b[2])(b[3])(e(b[4]))(b[5]));break b}break}else{var g=y(b)?m(b):b,h;b:{switch(g[0]){case "RBNode":switch(g[5][0]){case "RBEmpty":h=D(a,g[2]);break b}}h=!1}if(h)b=g[4];else{g=w;b:{switch(b[0]){case "RBNode":switch(b[5][0]){case "RBNode":switch(b[5][1][0]){case "Red":h=!0;break b}}}h=!1}if(g=g(h)){g=w;b:{switch(b[0]){case "RBNode":switch(b[5][0]){case "RBNode":switch(b[5][4][0]){case "RBNode":switch(b[5][4][1][0]){case "Red":h=
!0;break b}}}}h=!1}g=g(h)}g&&(b=k(b),b=n(b)?k(m(b)):b);b:{switch(b[0]){case "RBNode":g=D(a,b[2]);break b}g=!1}if(g)b:{switch(b[0]){case "RBEmpty":throw"delEQ called on a RBEmpty";case "RBNode":h=j(b[5]);c:{switch(h[0]){case "Tuple2":g=h[1];break c}break}c:{switch(h[0]){case "Tuple2":h=h[2];break c}break}var g=f(b[1])(g)(h)(b[4]),l=function(a){a:{switch(a[0]){case "RBNode":switch(a[4][0]){case "RBEmpty":a=z;break a}}b:{a=p(a);switch(a[0]){case "RBEmpty":a=z;break b;case "RBNode":a=c(f(a[1])(a[2])(a[3])(l(a[4]))(a[5]));
break b}throw"Non-exhaustive pattern match in case";}}return a};b=d(l(b[5]));b=c(g(b));break b}break}else b:{switch(b[0]){case "RBEmpty":throw"delGT called on a RBEmpty";case "RBNode":b=c(f(b[1])(b[2])(b[3])(b[4])(e(b[5])));break b}break}}}break a}throw"Non-exhaustive pattern match in case";}return b};return h(a)(b)?d(e(b)):b}}function x(a){return function(b){a:{switch(b[0]){case "RBEmpty":b=z;break a;case "RBNode":b=f(b[1])(b[2])(a(b[3]))(x(a)(b[4]))(x(a)(b[5]));break a}throw"Non-exhaustive pattern match in case";
}return b}}function s(a){return function(b){return function(c){a:{switch(c[0]){case "RBEmpty":c=b;break a;case "RBNode":c=s(a)(a(c[2])(c[3])(s(a)(b)(c[4])))(c[5]);break a}throw"Non-exhaustive pattern match in case";}return c}}}function u(a){return function(b){return function(c){a:{switch(c[0]){case "RBEmpty":c=b;break a;case "RBNode":c=u(a)(a(c[2])(c[3])(u(a)(b)(c[5])))(c[4]);break a}throw"Non-exhaustive pattern match in case";}return c}}}var q=Elm.Prelude.compare,t=Elm.Prelude.uncurry,v=Elm.Prelude.Nothing,
A=Elm.Prelude.Just,w=Elm.Prelude.not,D=Elm.Prelude.eq,F=Elm.Maybe.isJust,B=["Red"],E=["Black"],z=["RBEmpty"],C=z;return{$op:{},empty:C,lookup:a,findWithDefault:e,member:h,insert:l,singleton:function(a){return function(b){return l(a)(b)(z)}},remove:r,map:x,foldl:s,foldr:u,union:function(a){return function(b){return s(l)(b)(a)}},intersect:function(a){return function(b){return s(function(a){return function(c){return function(d){return h(a)(b)?l(a)(c)(d):d}}})(C)(a)}},diff:function(a){return function(b){return s(function(a){return function(){return function(b){return r(a)(b)}}})(a)(b)}},
keys:function(a){return u(function(a){return function(){return function(b){return["Cons",a,b]}}})(["Nil"])(a)},values:function(a){return u(function(){return function(a){return function(b){return["Cons",a,b]}}})(["Nil"])(a)},toList:function(a){return u(function(a){return function(b){return function(c){return["Cons",["Tuple2",a,b],c]}}})(["Nil"])(a)},fromList:function(a){return Elm.List.foldl(t(l))(C)(a)}}}();
Elm.Set=function(){var f=Elm.Dict.empty,j=Elm.Dict.remove,a=Elm.Dict.member,e=Elm.Dict.union,h=Elm.Dict.intersect,b=Elm.Dict.diff,m=Elm.Dict.keys,g=Elm.List.foldl(function(a){return function(b){return Elm.Dict.insert(a)(["Tuple0"])(b)}})(f);return{empty:f,singleton:function(a){return Elm.Dict.singleton(a)(["Tuple0"])},insert:function(a){return Elm.Dict.insert(a)(["Tuple0"])},remove:j,member:a,union:e,intersect:h,diff:b,toList:m,fromList:g,foldl:function(a){return Elm.Dict.foldl(function(b){return function(){return function(d){return a(b)(d)}}})},
foldr:function(a){return Elm.Dict.foldr(function(b){return function(){return function(d){return a(b)(d)}}})},map:function(a){return function(b){b=m(b);return g(Elm.List.map(a)(b))}}}}();
(function(){try{var f={};for(this.i in Elm)eval("var "+this.i+"=Elm[this.i];");if(Elm.Automaton)throw"Module name collision, 'Automaton' is already defined.";Elm.Automaton=function(){function a(a){return["Automaton",a]}function e(b){return a(function(a){var c=unzip(map(function(b){a:{switch(b[0]){case "Automaton":b=b[1](a);break a}throw"Non-exhaustive pattern match in case";}return b})(b)),d;a:{switch(c[0]){case "Tuple2":d=c[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(c[0]){case "Tuple2":c=
c[2];break a}throw"Non-exhaustive pattern match in case";}return["Tuple2",d,e(c)]})}function h(b){return a(function(a){return["Tuple2",b(a),h(b)]})}function b(c){return function(d){return a(function(a){a=d(a)(c);return["Tuple2",a,b(a)(d)]})}}function j(b){return function(c){return a(function(a){var d=c(a)(b);a:{switch(d[0]){case "Tuple2":a=d[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(d[0]){case "Tuple2":d=d[2];break a}throw"Non-exhaustive pattern match in case";}return["Tuple2",
a,j(d)(c)]})}}function g(a){return function(b){a:{switch(a[0]){case "Tuple2":b:{switch(b[0]){case "Tuple2":b=["Tuple2",a[1]-b[1],a[2]-b[2]];break b}break}break a}throw"Non-exhaustive pattern match in case";}return b}}function k(a){return function(b){var c;a:{switch(a[0]){case "Tuple2":b:{switch(b[0]){case "Tuple2":var d=function(a){return["Tuple2",b[2],["Tuple2",a,b[2]]]};c=function(){switch(b[1][0]){case "DragFrom":var c;a[1]?c=["Tuple2",uncurry(move)(g(a[2])(b[1][1]))(b[2]),["Tuple2",["DragFrom",
b[1][1]],b[2]]]:(c=uncurry(move)(g(a[2])(b[1][1]))(b[2]),c=["Tuple2",c,["Tuple2",l,c]]);return c;case "Ignore":return d(a[1]?y:l);case "Listen":return d(not(a[1])?l:isWithin(a[2])(b[2])?["DragFrom",a[2]]:y)}throw"Non-exhaustive pattern match in case";}();break b}break}break a}throw"Non-exhaustive pattern match in case";}return c}}try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(c){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";
}var d={};for(this.i in Elm.Prelude)d[this.i]||eval("var "+this.i+" = Elm.Prelude[this.i];");var l=["Listen"],y=["Ignore"];f[">>>"]=function(b){return function(c){var d;a:{switch(b[0]){case "Automaton":d=b[1];break a}throw"Non-exhaustive pattern match in case";}var e;a:{switch(c[0]){case "Automaton":e=c[1];break a}throw"Non-exhaustive pattern match in case";}return a(function(a){a=d(a);var b;a:{switch(a[0]){case "Tuple2":b=a[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(a[0]){case "Tuple2":a=
a[2];break a}throw"Non-exhaustive pattern match in case";}var c=e(b);a:{switch(c[0]){case "Tuple2":b=c[1];break a}throw"Non-exhaustive pattern match in case";}a:{switch(c[0]){case "Tuple2":c=c[2];break a}throw"Non-exhaustive pattern match in case";}return["Tuple2",b,f[">>>"](a)(c)]})}};f["<<<"]=function(a){return function(b){return f[">>>"](b)(a)}};f["^>>"]=function(a){return function(b){return f[">>>"](h(a))(b)}};f[">>^"]=function(a){return function(b){return f[">>>"](a)(h(b))}};f["^<<"]=function(a){return function(b){return f[">>>"](b)(h(a))}};
f["<<^"]=function(a){return function(b){return f[">>>"](h(b))(a)}};d=b(0)(function(){return function(a){return 1+a}});return{$op:{">>>":f[">>>"],"<<<":f["<<<"],"^>>":f["^>>"],">>^":f[">>^"],"^<<":f["^<<"],"<<^":f["<<^"]},run:function(a){return function(b){a:{switch(a[0]){case "Automaton":b=lift(fst)(foldp_(function(a){return function(b){a:{switch(b[0]){case "Tuple2":switch(b[2][0]){case "Automaton":b=b[2][1](a);break a}}throw"Non-exhaustive pattern match in case";}return b}})(a[1])(b));break a}throw"Non-exhaustive pattern match in case";
}return b}},step:function(a){return function(b){a:{switch(a[0]){case "Automaton":b=a[1](b);break a}throw"Non-exhaustive pattern match in case";}return b}},combine:e,pure:h,init:b,init_:j,count:d,draggable:function(a){return j(["Tuple2",l,a])(k)}}}();Elm.main=function(){return Elm.Automaton.main}}catch(j){Elm.main=function(){document.body.innerHTML=Elm.Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Automaton module:<br/>'+
j+"</span>");throw j;}}})();
(function(){try{for(this.i in Elm)eval("var "+this.i+"=Elm[this.i];");Elm.Website=Elm.Website||{};if(Elm.Website.ColorScheme)throw"Module name collision, 'Website.ColorScheme' is already defined.";Elm.Website.ColorScheme=function(){try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(f){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var a={};for(this.i in Elm.Prelude)a[i]||eval("var "+this.i+" = Elm.Prelude[this.i];");
var a=rgb(90)(99)(120),e=rgb(96)(181)(204),h=rgb(240)(173)(0),b=rgb(234)(21)(122),m=rgb(127)(209)(59),g=rgb(245)(245)(245),k=rgb(216)(221)(225);return{accent0:a,accent1:e,accent2:h,accent3:b,accent4:m,lightGrey:g,mediumGrey:k}}();Elm.main=function(){return Elm.Website.ColorScheme.main}}catch(f){Elm.main=function(){document.body.innerHTML=Elm.Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.ColorScheme module:<br/>'+
f+"</span>");throw f;}}})();
try{Elm.Website=Elm.Website||{};if(Elm.Website.Docs)throw"Module name collision, 'Website.Docs' is already defined.";Elm.Website.Docs=function(){function f(a){return function(b){var d=a(b-80),e=flow(down),f,g=toFloat(b),h=toFloat(10);f=map(function(a){return round(g*(toFloat(a)/h))});var j=10,k=["Nil"];if(1<=j){do k=["Cons",j,k];while(1<j--)}f=f(k);f=c(function(a){return function(b){return a-b}})(f)(["Cons",0,f]);var j=concatMap(function(){return l}),k=div(10)(5),m=["Nil"];if(0<=k){do m=["Cons",k,
m];while(0<k--)}j=j(m);f=flow(right)(c(function(a){return function(b){return color(a)(spacer(b)(5))}})(j)(f));j=spacer(b)(15);d=container(b)(heightOf(d))(midTop)(d);k=Value.append(Text.color(rgb(145)(145)(145))(toText("&copy; 2011-2013 ")),Text.link(Value.str("https://github.com/evancz"))(toText("Evan Czaplicki")));b=container(b)(50)(midBottom)(text(k));return e(["Cons",f,["Cons",j,["Cons",d,["Cons",b,["Nil"]]]]])}}function j(a){return function(b){return bold(Text.height(a)(toText(b)))}}function a(a){return function(b){return flow(down)(["Cons",
spacer(1)(10),["Cons",width(a)(plainText(b)),["Cons",spacer(1)(20),["Nil"]]]])}}function e(a){return function(b){b=width(a)(b);var c=topLeftAt(absolute(0))(absolute(-5));return container(a)(heightOf(b))(c)(b)}}function h(a){return function(b){return function(c){a:{switch(c[0]){case "Tuple2":var d=flow(down),e=text(j(1.25)(c[1])),f=spacer(1)(20);c=d(["Cons",e,["Cons",f,map(function(c){a:{switch(c[0]){case "Tuple3":var d=Text.color(accent1)(toText(" :: ")),e="GT"===compare(length(c[2]))(0)[0]?Value.append(d,
toText(c[2])):toText(""),d=flow(down),f=color(mediumGrey)(spacer(b)(1)),e=Value.append(bold(toText(c[1])),e),e=width(b)(color(lightGrey)(text(monospace(e))));c=d(["Cons",f,["Cons",e,["Cons",flow(right)(["Cons",spacer(50)(10),["Cons",a(b-50)(c[3]),["Nil"]]]),["Nil"]]]]);break a}throw"Non-exhaustive pattern match in case";}return c})(c[2])]]);break a}throw"Non-exhaustive pattern match in case";}return c}}}for(Elm.i in Elm)eval("var "+Elm.i+"=Elm[Elm.i];");try{if(!(Elm.Prelude instanceof Object))throw"module not found";
}catch(b){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var m={};for(Elm.i in Elm.Prelude)m[Elm.i]||eval("var "+Elm.i+" = Elm.Prelude[Elm.i];");try{if(!(Elm.List instanceof Object))throw"module not found";}catch(g){throw"Module 'List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var k=Elm.List.intersperse,c=Elm.List.zipWith;try{if(!(Elm.Website.ColorScheme instanceof Object))throw"module not found";
}catch(d){throw"Module 'Website.ColorScheme' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}m={};for(Elm.i in Elm.Website.ColorScheme)m[Elm.i]||eval("var "+Elm.i+" = Elm.Website.ColorScheme[Elm.i];");var l=["Cons",accent0,["Cons",accent1,["Cons",accent2,["Cons",accent3,["Cons",accent4,["Nil"]]]]]];return{$op:{},createDocs:function(b){return function(c){return lift(f(function(d){var e=flow(down),f=text(Text.link(Value.str("/Documentation.elm"))(toText("Back"))),
g;g=j(2)(b);g=width(d)(centeredText(g));return e(["Cons",f,["Cons",g,["Cons",spacer(1)(30),k(spacer(1)(50))(map(h(a)(d))(c))]]])}))(Window.width)}},createDocs2:function(a){return function(b){return function(c){return lift(f(function(d){var f=flow(down),g=text(Text.link(Value.str("/Documentation.elm"))(toText("Back"))),l;l=j(2)(a);l=width(d)(centeredText(l));return f(["Cons",g,["Cons",l,["Cons",width(d)(b),["Cons",spacer(1)(30),k(spacer(1)(50))(map(h(e)(d))(c))]]]])}))(Window.width)}}}}}();Elm.main=
function(){return Elm.Website.Docs.main}}catch(e$$71){Elm.main=function(){document.body.innerHTML=Elm.Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Docs module:<br/>'+e$$71+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, accent0, accent1, accent2, accent3, accent4, lightGrey, mediumGrey</span>");throw e$$71;}}
try{Elm.Website=Elm.Website||{};if(Elm.Website.Tiles)throw"Module name collision, 'Website.Tiles' is already defined.";Elm.Website.Tiles=function(){function f(a){a:{switch(a[0]){case "Tuple3":a=["Tuple3",a[1],Value.append(a[3],Value.append(a[2],Value.str(".elm"))),Value.append(Value.str("/screenshot/"),Value.append(a[2],Value.str(".jpg")))];break a}throw"Non-exhaustive pattern match in case";}return a}function j(a){return function(b){a:{switch(b[0]){case "Cons":b=["Cons",m(a)(b),j(a)(g(a)(b))];break a;
case "Nil":b=["Nil"];break a}throw"Non-exhaustive pattern match in case";}return b}}function a(a){var b=f(a);a:{switch(b[0]){case "Tuple3":break a}throw"Non-exhaustive pattern match in case";}a:{switch(b[0]){case "Tuple3":a=b[2];break a}throw"Non-exhaustive pattern match in case";}a:{switch(b[0]){case "Tuple3":b=b[3];break a}throw"Non-exhaustive pattern match in case";}return Graphics.link(Value.append(Value.str("/edit/examples/"),a))(container(100)(100)(middle)(image(90)(90)(b)))}for(Elm.i in Elm)eval("var "+
Elm.i+"=Elm[Elm.i];");try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(e){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var h={};for(Elm.i in Elm.Prelude)h[Elm.i]||eval("var "+Elm.i+" = Elm.Prelude[Elm.i];");try{if(!(Elm.List instanceof Object))throw"module not found";}catch(b){throw"Module 'List' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var m=Elm.List.take,
g=Elm.List.drop,k=Elm.List.intersperse;return{$op:{},toTile:function(a){var b=f(a);a:{switch(b[0]){case "Tuple3":a=b[1];break a}throw"Non-exhaustive pattern match in case";}var e;a:{switch(b[0]){case "Tuple3":e=b[2];break a}throw"Non-exhaustive pattern match in case";}var g;a:{switch(b[0]){case "Tuple3":g=b[3];break a}throw"Non-exhaustive pattern match in case";}e=Graphics.link(Value.append(Value.str("/edit/examples/"),e));b=flow(down);g=container(130)(130)(middle)(image(120)(120)(g));a=toText(a);
a=width(130)(centeredText(a));return e(b(["Cons",g,["Cons",a,["Nil"]]]))},tile:function(a){return function(b){b=j(div(a)(130))(b);return flow(down)(k(spacer(1)(14))(map(flow(right))(b)))}},miniTiles:function(b){return function(d){d=map(a)(d);d=j(div(b)(100))(d);return flow(down)(k(spacer(1)(14))(map(flow(right))(d)))}}}}();Elm.main=function(){return Elm.Website.Tiles.main}}catch(e$$74){Elm.main=function(){document.body.innerHTML=Elm.Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Tiles module:<br/>'+
e$$74+"</span>");throw e$$74;}}
try{Elm.Website=Elm.Website||{};if(Elm.Website.Skeleton)throw"Module name collision, 'Website.Skeleton' is already defined.";Elm.Website.Skeleton=function(){function f(a){a:{switch(a[0]){case "Tuple3":var b=color(a[3])(spacer(100)(2)),d=container(100)(58)(middle),e;e=toText(a[1]);e=text(Text.color(black)(e));d=d(e);a=Graphics.link(a[2])(below(b)(d));break a}throw"Non-exhaustive pattern match in case";}return a}function j(a){var b;b=toText("Elm");b=text(Text.link(Value.str("/"))(Text.color(black)(Text.height(2)(bold(b)))));return container(a)(60)(midLeft)(b)}
function a(a){return function(b){b=container(a)(60)(middle)(beside(j(b-widthOf(m)))(m));return layers(["Cons",flow(down)(["Cons",color(lightGrey)(spacer(a)(58)),["Cons",color(mediumGrey)(spacer(a)(1)),["Nil"]]]),["Cons",b,["Cons",width(a)(g),["Nil"]]]])}}for(Elm.i in Elm)eval("var "+Elm.i+"=Elm[Elm.i];");try{if(!(Elm.Prelude instanceof Object))throw"module not found";}catch(e){throw"Module 'Prelude' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}var h=
{};for(Elm.i in Elm.Prelude)h[Elm.i]||eval("var "+Elm.i+" = Elm.Prelude[Elm.i];");try{if(!(Elm.Website.ColorScheme instanceof Object))throw"module not found";}catch(b){throw"Module 'Website.ColorScheme' is missing. Compile with --make flag or load missing module in a separate JavaScript file.";}h={};for(Elm.i in Elm.Website.ColorScheme)h[Elm.i]||eval("var "+Elm.i+" = Elm.Website.ColorScheme[Elm.i];");var m=flow(right)(map(f)(["Cons",["Tuple3",Value.str("About"),Value.str("/About.elm"),accent1],["Cons",
["Tuple3",Value.str("Examples"),Value.str("/Examples.elm"),accent2],["Cons",["Tuple3",Value.str("Docs"),Value.str("/Documentation.elm"),accent3],["Cons",["Tuple3",Value.str("Download"),Value.str("/Download.elm"),accent4],["Nil"]]]]])),g=text('<div style="height:0;width:0;">&nbsp;</div><a href="javascript:var p=top.location.pathname;if(p.slice(0,5)!=\'/edit\')top.location.href=\'/edit\'+(p==\'/\'?\'/Elm.elm\':p);"> <img style="position: absolute; top: 0; right: 0; border: 0;"\n     src="/ribbon.gif"\n     alt="View Page Source"> </a><div style="height:0;width:0;">&nbsp;</div>');
return{$op:{},button:f,buttons:m,title:j,veiwSource:g,heading:a,skeleton:function(b){return function(c){var d="LT"===compare(c)(820)[0]?c-20:800,e=b(d),f=flow(down),d=a(c)(d),g=spacer(c)(10),e=container(c)(heightOf(e))(middle)(e),h=Value.append(Text.color(rgb(145)(145)(145))(toText("&copy; 2011-2013 ")),Text.link(Value.str("https://github.com/evancz"))(toText("Evan Czaplicki")));c=container(c)(50)(midBottom)(text(h));return f(["Cons",d,["Cons",g,["Cons",e,["Cons",c,["Nil"]]]]])}}}}();Elm.main=function(){return Elm.Website.Skeleton.main}}catch(e$$77){Elm.main=
function(){document.body.innerHTML=Elm.Text.monospace('<br/><h2>Your browser may not be supported. Are you using a modern browser?</h2><br/><span style="color:grey">Runtime Error in Website.Skeleton module:<br/>'+e$$77+"<br/><br/>The problem may stem from an improper usage of:<br/>Text.color, accent1, accent2, accent3, accent4, below, beside, lightGrey, mediumGrey</span>");throw e$$77;}};